### ISSUE TITLE
Crash on image Upload.

### ISSUE THREAD

**Issue by Bashta** [onfido/onfido-ios-sdk#10]
Issue occurring when uploading an image, on multipartFromData `func append(_ data: Data, withName name: String, mimeType: String)` `Alamofire 4.5.0`

**Comment by rfreitas** [comment]
Hey Bashta,

Which sdk version are you using? Where are you uploading the images, browser or server?

**Comment by Bashta** [comment]
Onfido 2.1.2 Uploading on the server.

**Comment by rfreitas** [comment]
Then you haven't turned on the create options for document/face capture? This will let the sdk upload the images for you and it will also run extra image quality validation, it's therefore recommended.

**Comment by rfreitas** [comment]
In case you have the create options turned on, can you provide a stack trace?

**Comment by anuragajwani** [comment]
Closing due to long period of inactivity.
