### ISSUE TITLE
Crash in OnfidoSEGEventNameForScreenTitle

### ISSUE THREAD

**Issue by yakobz** [onfido/onfido-ios-sdk#102]
### Version info:

- Cocoapods 1.7.0
- Onfido SDK (Release) 10.2.0
- iOS 12.3.1, 12.3.0

### Crash reports:

[com.dozens_issue_crash_a5d3a3ff37b040bd9f28adf71e51ccd4_DNE_0_v2.txt](https://github.com/onfido/onfido-ios-sdk/files/3368955/com.dozens_issue_crash_a5d3a3ff37b040bd9f28adf71e51ccd4_DNE_0_v2.txt)
[com.dozens_issue_crash_ea1ddc87a38846b9b45d1a1805bff370_DNE_1_v2.txt](https://github.com/onfido/onfido-ios-sdk/files/3368956/com.dozens_issue_crash_ea1ddc87a38846b9b45d1a1805bff370_DNE_1_v2.txt)
[com.dozens_issue_crash_b9ea0e2636214c5dabd0329608c38b6b_DNE_0_v2.txt](https://github.com/onfido/onfido-ios-sdk/files/3368957/com.dozens_issue_crash_b9ea0e2636214c5dabd0329608c38b6b_DNE_0_v2.txt)
[com.dozens_issue_crash_65031f8049d9455da16bd5d2639e8025_DNE_1_v2.txt](https://github.com/onfido/onfido-ios-sdk/files/3368958/com.dozens_issue_crash_65031f8049d9455da16bd5d2639e8025_DNE_1_v2.txt)
[com.dozens_issue_crash_fc7e74245853484588bb66501a13ef0a_DNE_0_v2.txt](https://github.com/onfido/onfido-ios-sdk/files/3368959/com.dozens_issue_crash_fc7e74245853484588bb66501a13ef0a_DNE_0_v2.txt)

**Comment by keremgund** [comment]
Hi @yakobz thanks for reporting the issue. It would be good for us to identify the problem if you can answer questions below:
1-Is there a particular screen that this issue occurs ? 
2-Are you using any cross platform tool like xamarin, react native in your project ?
3-Is there a reason to not upgrade to our latest version ? (which is 12.2 currently)

**Comment by yakobz** [comment]
Hello!
1. We can't reproduce this issue, we have found this crashlogs in
crashlytics (live application)
2. This is native iOS app (swift 5)
3. We will update out application in nearest build, but this issue
reproduced after you fix issue:
https://github.com/onfido/onfido-ios-sdk/issues/55

Thank you! Best regards!

**Comment by keremgund** [comment]
Hello @yakobz , thanks for providing those information. As Swift 5 requires Xcode 10.x to run with and Onfido SDK version 10.2  isn't compatible with that Xcode (see https://github.com/onfido/onfido-ios-sdk/blob/master/MIGRATION.md#onfido-ios-sdk-1000-migration-guide), I assume that you're not using Onfido SDK 10.2 with Swift 5 ?

**Comment by yakovshkolnikov** [comment]
Hello! In our latest release we have updated Onfido to 11.1.2 and swift 5
Previous issues was not reproduced
But we found new crashes:

seg_libzOpen
[com.dozens_issue_crash_7d2ff2f89823473ba8111f8eaa965c07_DNE_0_v2.txt](https://github.com/onfido/onfido-ios-sdk/files/3402908/com.dozens_issue_crash_7d2ff2f89823473ba8111f8eaa965c07_DNE_0_v2.txt)

automaticallyNotifiesObserversOfNonForcedSubtitleDisplayEnabled:
[com.dozens_issue_crash_4df92d0fbdc942af9f29833b31bac35e_DNE_0_v2.txt](https://github.com/onfido/onfido-ios-sdk/files/3402910/com.dozens_issue_crash_4df92d0fbdc942af9f29833b31bac35e_DNE_0_v2.txt)

**Comment by yakovshkolnikov** [comment]
> Hello! In our latest release we have updated Onfido to 11.1.2 and swift 5
> Previous issues was not reproduced
> But we found new crashes:
> 
> seg_libzOpen
> [com.dozens_issue_crash_7d2ff2f89823473ba8111f8eaa965c07_DNE_0_v2.txt](https://github.com/onfido/onfido-ios-sdk/files/3402908/com.dozens_issue_crash_7d2ff2f89823473ba8111f8eaa965c07_DNE_0_v2.txt)
> 
> automaticallyNotifiesObserversOfNonForcedSubtitleDisplayEnabled:
> [com.dozens_issue_crash_4df92d0fbdc942af9f29833b31bac35e_DNE_0_v2.txt](https://github.com/onfido/onfido-ios-sdk/files/3402910/com.dozens_issue_crash_4df92d0fbdc942af9f29833b31bac35e_DNE_0_v2.txt)

Any updates about this issue?

**Comment by keremgund** [comment]
Hello @yakovshkolnikov, first of all sorry for the late reply.
This issue is exactly the same with this one: https://github.com/onfido/onfido-ios-sdk/issues/76
Both issues are about having crash while calling `seg_libzOpen` function. We're already aware of the issue and working on the fix. You can follow other ticket to get updates about the progress on our side.
So I'm going to close this ticket and we can track this issue with the other one. 

Thanks,
Kerem
