### ISSUE TITLE
Crash on LivenessCaptureIntroViewController 

### ISSUE THREAD

**Issue by bishalg** [onfido/onfido-ios-sdk#103]
### What was the expected behaviour?
App should not crash after Document upload

### What happened instead?
App crash each time Passport Image Upload completes 

Please detail what was the actual behaviour
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/403D7F68-9B5B-4AA8-A462-92DC4645B846/Oyster.app/Frameworks/Onfido.framework> (loaded)' with name 'LivenessCaptureIntroViewController''`

### Version info:

- Cocoapods (if applicable):
pod 'Onfido', '12.1.0'
- Onfido SDK (Debug/Release):

- iOS: 12.0
- Xcode: 10.2.1
- Device/Simulator: Device ( iPhone X )
- Device/Simulator language: English

### Integration configuration:
- Normal SDK configuration. Code was working for fine for older version of SDK

### Steps to reproduce:
- App crash after the upload of Passport Image document completes.

**Comment by bishalg** [comment]
Updated to  `12.2.0`

`pod 'Onfido', '12.2.0'`

Which seems to fix the issue. If this was known issue on 12.1.0 we can close this issue. 
Thanks

**Comment by anuragajwani** [comment]
HI @bishalg,

I tested out the SDK version 12.1.0 on the SampleApp using the following:
**Version info:**
```
Cocoapods (if applicable): 1.5.3 (the version of CocoaPods not SDK)
Onfido SDK: 12.1.0
iOS: 12.3.1
Xcode: 10.2.1
Device/Simulator: iPhone XR device
Device/Simulator language: English
```
**Integration configuration:**
```
OnfidoConfig.builder()
            .withToken(token)
            .withApplicantId(applicantId)
            .withWelcomeStep()
            .withDocumentStep()
            .withFaceStep(ofVariant: .video(withConfiguration: nil))
            .build()
```
Podfile
```
target 'SampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp
  pod 'Onfido', '12.1.0'
end
```

Please find attached the SampleApp in this repo with the necessary modifications given the information provided on your integration [SampleApp.zip](https://github.com/onfido/onfido-ios-sdk/files/3402607/SampleApp.zip). Run pod install and open the xcworkspace. The integration seems to run fine after capturing passport.

Unfortunately I have not been able to reproduce your issue.

Anurag

**Comment by bishalg** [comment]
@anuragajwani  : thks for the quick support. One thing I forgot to mention was that I have used the SDK on **ReactNative App**. But as its not the issue on `v 12.2.0` I will close the issue for now.
