### ISSUE TITLE
French Translation.

### ISSUE THREAD

**Issue by trinhhoangvubk** [onfido/onfido-ios-sdk#105]
Hi team, 

As I read your document, there're 3 supported languages: English, French and Germany. 
I'm developing application for French market. I configured my language is French in setting.
The translation in app work well, but Onfido screens(welcome, choose document/id, take photo/video) still in English.
Any idea about that, thank in advance.

**Comment by trinhhoangvubk** [comment]
I also tried to download Onfido iOS app in App Store. They also didn't translate.

![IMG_3227](https://user-images.githubusercontent.com/14834472/61937288-1bb66d00-afc1-11e9-800e-9ca2b3f20fb3.PNG)
![IMG_3226](https://user-images.githubusercontent.com/14834472/61937235-f7f32700-afc0-11e9-910b-f939964f125e.PNG)
![IMG_3225](https://user-images.githubusercontent.com/14834472/61937250-fde90800-afc0-11e9-9dfb-0377d199b3e2.PNG)

**Comment by seewah** [comment]
Hi

The lack of french support is a restriction on the Onfido demo app only, because it was published as an English-only application.

Have you tested the actual SDK inside your app itself? If you configure your own app to support French, the translation should work.

Thanks

**Comment by trinhhoangvubk** [comment]
Hi seewah, 

Yes, I tested actual SDK in app itself. The whole app translation in French except Onfido.

**Comment by anuragajwani** [comment]
Does your app specify French support @trinhhoangvubk ? Are you using custom localisation? FYI the demo app doesn't support French. The demo app on the App Store will not render neither the app itself nor the SDK in French.

Please fill in the GitHub issue form so we can try to solve your problem.

Anurag

**Comment by maurovisintin** [comment]
I had the same problem,
solved it by adding
```
<key>CFBundleLocalizations</key>
    <array>
        <string>en</string>
        <string>fr</string>
		<string>es</string>
		<string>de</string>
    </array>
```
as you suggested.

**Comment by trinhhoangvubk** [comment]
Issue exists on earlier version. Looks good on latest SDK version.
