### ISSUE TITLE
Error on POD install

### ISSUE THREAD

**Issue by maniveltvl** [onfido/onfido-ios-sdk#109]
### What was the expected behaviour?

Hi, Team 
We are developing Cordova application and we trying to implement Onfido SDK. So we are using pod file to download Onfiod SDK. While adding ios platform in my app, we are getting the below issue.
Onfido SDK should compile in iOS app

### What happened instead?

While adding iOS platform, we are getting the below error

> Running command: pod install --verbose

==== pod install start ====

  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-OnfidoApp`: (``)

Resolving dependencies of `Podfile`
/Users/macmininttdata/.cocoapods/repos-art/ios-kaas/.artpodrc

Comparing resolved specification to the sandbox manifest
  A Onfido
  A SwiftyJSON
  A Swinject
  A ZSWTaggedString
  A ZSWTappableLabel

Downloading dependencies

-> Installing Onfido (8.0.0)
  > Copying Onfido from `/Users/macmininttdata/Library/Caches/CocoaPods/Pods/Release/Onfido/8.0.0-d3190` to `Pods/Onfido`

-> Installing SwiftyJSON (3.1.4)
  > Copying SwiftyJSON from `/Users/macmininttdata/Library/Caches/CocoaPods/Pods/Release/SwiftyJSON/3.1.4-c2842` to `Pods/SwiftyJSON`

-> Installing Swinject (2.2.0)
  > Copying Swinject from `/Users/macmininttdata/Library/Caches/CocoaPods/Pods/Release/Swinject/2.2.0-4ca48` to `Pods/Swinject`

-> Installing ZSWTaggedString (4.0)
  > Copying ZSWTaggedString from `/Users/macmininttdata/Library/Caches/CocoaPods/Pods/Release/ZSWTaggedString/4.0-3b06d` to `Pods/ZSWTaggedString`

-> Installing ZSWTappableLabel (2.0)
  > Copying ZSWTappableLabel from `/Users/macmininttdata/Library/Caches/CocoaPods/Pods/Release/ZSWTappableLabel/2.0-cff84` to `Pods/ZSWTappableLabel`
  - Running pre install hooks
[!] Unable to determine Swift version for the following pods:

- `SwiftyJSON` does not specify a Swift version and none of the targets (`OnfidoApp`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
- `Swinject` does not specify a Swift version and none of the targets (`OnfidoApp`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:122:in `verify_swift_pods_swift_version'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:578:in `validate_targets'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:158:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/command/install.rb:51:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

Command finished with error code 1: pod install,--verbose
Failed to install 'com.avis.onfido': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/macmininttdata/Documents/Mani/onfido/Wrapper/onfidoPoC/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
Error: pod: Command failed with exit code 

 
### Please find the below pod file which we are using here
platform :ios, '8.0'
target 'App' do
	project 'App.xcodeproj'
	pod 'Onfido'
	post_install do |installer|

		installer.pods_project.targets.each do |target|
	  
		  if target.name == 'SwiftyJSON' || target.name == 'Swinject'
	  
			target.build_configurations.each do |config|
	  
			  config.build_settings['SWIFT_VERSION'] = '4.0'
	  
			end
	  
		  end
	  
		end
	  
	  end
end

### Version info:

- Cocoapods (if applicable):1.7.2
- Onfido SDK (Debug/Release):
- iOS: 10.14.5
- Xcode:10.2.1
- Device/Simulator:
- Device/Simulator language:

**Comment by anuragajwani** [comment]
Hi @maniveltvl ,

Onfido 8.0.0 won't work with Xcode 10.2.1. Please use from Onfido 11.0.0 to 13.2.0. 
Your CocoaPods might not have access to these version as you local cache might be out of date. In that case run `pod repo update` to update your local cache. On your `Podfile` specify `pod 'Onfido', '13.2.0'` instead of just `pod 'Onfido'`.

You can remove from your Podfile:

```
post_install do |installer|
	installer.pods_project.targets.each do |target|
	  if target.name == 'SwiftyJSON' || target.name == 'Swinject'
		target.build_configurations.each do |config|
		  config.build_settings['SWIFT_VERSION'] = '4.0'
		end
	  end
	end
  end
```

These are no longer imported externally. Some of them have been removed completely.
Hope that helps,
Anurag
