### ISSUE TITLE
Module compiled with Swift 3.1 cannot be imported in Swift 3.2

### ISSUE THREAD

**Issue by dim-bon** [onfido/onfido-ios-sdk#11]
Hello,
now that we have XCode 9 GM available, we need to have an updated SDK as soon as possible.

Thank you

**Comment by seewah** [comment]
Hi we have already started looking at making the SDK Swift 3.2/4 compatible. We will post an ETA of when it will be available soon. Thanks.

**Comment by seewah** [comment]
Hi we will be making a new release of the SDK over the next couple of days to resolve this compatibility issue. Will comment again if it is ready.

**Comment by dim-bon** [comment]
Thanks, we're looking forward to hear from you on this soon

**Comment by seewah** [comment]
Hi a new version (3.0.0) has just been released, which is swift 3.2/4 and xcode 9 compatible. Thanks.
