### ISSUE TITLE
How to implement onfido to react-native

### ISSUE THREAD

**Issue by chukhlov** [onfido/onfido-ios-sdk#111]
Hello dear support. I need to use onfido on react-native.
I found https://github.com/MCROEngineering/react-native-onfido-sdk/
But this sdk does not work.
Could you help me to rewrite this module or write from scratch?

**Comment by keremgund** [comment]
Hi @chukhlov , have you checked our sample react-native app ?
You can find it here: https://github.com/onfido/onfido-sdk-react-native-sample-app
Let me know if you need further help.

Thanks,
Kerem

**Comment by anuragajwani** [comment]
Hi @chukhlov,

Looks like this is an [duplicate issue located on our Android SDK repo](https://github.com/onfido/onfido-android-sdk/issues/79). 

As mentioned that repo is not ours. Please checkout our [react native sample app](https://github.com/onfido/onfido-sdk-react-native-sample-app) as guidance to integrate your react native app to our SDK. Please open a new issue if you have trouble only integrating to our iOS SDK here.

Anurag
