### ISSUE TITLE
Onfido iOS 13 release broken

### ISSUE THREAD

**Issue by borut-t** [onfido/onfido-ios-sdk#113]
### What was the expected behaviour?

Able to install debug and release configurations for the latest version.

### What happened instead?

Version 14.0.0-rc is not compatible with release configuration.

```
[!] CocoaPods could not find compatible versions for pod "Onfido-Release":
  In Podfile:
    Onfido-Release (= 14.0.0-rc)
```

### Version info:

- Cocoapods (if applicable): 1.7.5
- Onfido SDK (Debug/Release): 14.0.0-rc
- iOS: 13
- Xcode: 11
- Device/Simulator: device
- Device/Simulator language: en

### Integration configuration:

`pod 'Onfido', '14.0.0-rc', :configurations => ['Debug']` -> working
`pod 'Onfido-Release', '14.0.0-rc', :configurations => ['Release']` -> not working

### Steps to reproduce:

Bump pod versions to the latest version `14.0.0.-rc`

**Comment by anuragajwani** [comment]
@borut-t 

As @sree127 mentioned with the link, we have moved to a single framework since 11.1.0. We have been supporting `-Release` to allow integrators to migrate to single framework. Since 14.0.0 we are no longer support `Onfido-Release`

Please change your `Podfile` to only include
`pod 'Onfido', '14.0.0-rc'`

Anura

**Comment by borut-t** [comment]
Hey @anuragajwani. Thanks for the notice. I wasn't aware of that change. Just looking at the [release](https://github.com/onfido/onfido-ios-sdk/releases/tag/11.1.0) notes and cannot find this change was mentioned. I think you should communicate such changes in the release notes down the road. I usually tend to read release notes before making an upgrade.

Anyway, it works now. Thanks to you and @sree127 🙌
