### ISSUE TITLE
Can't buil on Xcode 11

### ISSUE THREAD

**Issue by capitanomikejobs** [onfido/onfido-ios-sdk#114]
### Version info:

- Onfido SDK (Debug/Release):13.2.0
- iOS: 13
- Xcode: 11
- Device/Simulator: both
- Device/Simulator language: english

**Comment by bartzet** [comment]
Hello. 

Could you please share what errors do you get with Xcode 11?

**Comment by capitanomikejobs** [comment]
Hello,

that the error:

Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler:

**Comment by anuragajwani** [comment]
Hi @capitanomikejobs 

Onfido iOS SDK 13.2.0 is not compatible with Xcode 11. Please use Onfido iOS SDK 14.0.0-rc with Xcode 11.

https://github.com/onfido/onfido-ios-sdk/blob/master/MIGRATION.md#onfido-ios-sdk-1400-rc-migration-guide

Anurag

**Comment by capitanomikejobs** [comment]
Hello @anuragajwani thanks for the support.

Do you have idea when will available the final release?

**Comment by anuragajwani** [comment]
We are aiming to have a final release by early next week.

Anurag

**Comment by ignasbagdonas** [comment]
We're also waiting XCode 11 and Swift 5 support

**Comment by anuragajwani** [comment]
@ignasbagdonas we have released yesterday version 14.0.0 which is built with Xcode 11 GM seed 2. We already had 14.0.0-rc prior to this release compatible with Xcode 11 GM seed 1 & 2.

**Comment by ignasbagdonas** [comment]
Yes, but I need Onfido Framework with Swift 5.1. Now I can't use it with Xamarin.
Error: Onfido Framework do not match installed Swift version. Framework: 4.2. Installed: 5.1. Change your Xcode or library version. (citybee.iOS)
