### ISSUE TITLE
Onfido 14.0.0 crashes on iOS 11

### ISSUE THREAD

**Issue by SergejLogis** [onfido/onfido-ios-sdk#117]
### What was the expected behaviour?

App launch successfully.

### What happened instead?

App crashes at the module loading phase.

### Version info:

- Cocoapods (if applicable): 1.8.0
- Onfido SDK (Debug/Release): 14.0.0
- iOS: 11.4
- Xcode: 11.2 BETA
- Device/Simulator: iPhone 8 simulator
- Device/Simulator language: EN

### Integration configuration:
```
        let builder = OnfidoConfig.builder()
            .withToken(onfidoToken)
            .withApplicantId(applicantID)
            .withDocumentStep(ofType: onfidoType, andCountryCode: country.code)            
            .withCustomLocalization()
```

### Steps to reproduce:

Update Onfido to 14.0.0 and launch app on simulator. It crashes with the following error:
```
dyld: Library not loaded: @rpath/libswiftCoreMedia.dylib
  Referenced from: /Users/sergej/Library/Developer/CoreSimulator/Devices/52643085-CACB-4364-95BB-627EC018DB43/data/Containers/Bundle/Application/696D0FB9-5670-4E6D-B8CB-09E2379EDF55/TransferGo.app/Frameworks/Onfido.framework/Onfido
  Reason: no suitable image found.  Did find:
	/usr/lib/swift/libswiftCoreMedia.dylib: mach-o, but not built for iOS simulator
	/usr/lib/swift/libswiftCoreMedia.dylib: mach-o, but not built for iOS simulator
```
**P.S.** Can't test on a real divice, don't have any running iOS 11...

**Comment by anuragajwani** [comment]
we have seen a similar issue recently which was also fixed by the reporter.

https://github.com/onfido/onfido-ios-sdk/issues/115

Please let me know if this fixes your issue.

Thanks,
Anurag

**Comment by SergejLogis** [comment]
Thanks, Anurag! 
Manually adding `libswiftAVFoundation.tbd` to Embedded Libraries solved the issue on iOS 11.
