### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by rackstar** [onfido/onfido-ios-sdk#119]
What was the expected behavior?
Onfido SDK running like it ran on Xcode 10.0.2 using Swift 5.0
Please detail what the expected behavior was
After upgrading to Xcode 11.2 using Swift 5.1.2
After pod update, Onfido SDK compiles and works like before the upgrade

What happened instead?
Instead, I got an error:
Onfido SDK: Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.2 compiler
Please detail what was the actual behavior

Version info:
Cocoapods (if applicable): /
Onfido SDK (Debug/Release): Debug Version 13.0.0
iOS: 13
Xcode: 11.2
Device/Simulator: iPhone XS
Device/Simulator language: Swift 5.1.2
Steps to reproduce:
Please describe in as much detail as possible on how to reproduce the problem
Just upgrade to Xcode 11.2 and Swift 5.1.2 try to compile a project that has Onfido SDK as cocoapod

**Comment by rackstar** [comment]
This is similar to an issue that was raise before https://github.com/onfido/onfido-ios-sdk/issues/116, but was then closed. 

Has there been any resolution to this issue?

**Comment by keremgund** [comment]
Hi @rackstar, if you're using Xcode 11.2 then you should use 14.0.0 iOS SDK version or above. 
We've mentioned that requirement in our release information:
https://github.com/onfido/onfido-ios-sdk/releases/tag/14.0.0-rc

Please let me know if you need further help.

Thanks,
Kerem

**Comment by rackstar** [comment]
Yep, I can confirm this works. Thanks for the help
