### ISSUE TITLE
Extra argument 'allowAnalytics' in call

### ISSUE THREAD

**Issue by Ricktter** [onfido/onfido-ios-sdk#12]
I´m getting this error **"Extra argument 'allowAnalytics' in call"** in this line
`self.onfidoFlow = OnfidoFlow(apiToken: "YOUR_TOKEN_HERE", allowAnalytics: false)` 
of your SampleApp and I can´t find where fix it.

Help

**Comment by dawiddylowicz** [comment]
Hi @Ricktter. Thanks for pointing it out. We have updated the SampleApp to respect version 4.0.1. Please let us know if it works for you now.

**Comment by Ricktter** [comment]
It works, thanks a lot
