### ISSUE TITLE
Onfido liveness disappear before I have a chance to complete the numbers.

### ISSUE THREAD

**Issue by gavaliswapnil** [onfido/onfido-ios-sdk#120]
### What was the expected behaviour?

I have noticed is that when the onfido liveness check is occurring the voice part where I have to say numbers seems to disappear before I have a chance to complete the statement.  

### Version info:

- Cocoapods (if applicable):yes
- Onfido SDK (Debug/Release):Release
- iOS: 12.4
- Xcode:10.3
- Device: iPhone 7
- react-native node module

### Integration configuration:

    ONFlowConfigBuilder *configBuilder = [ONFlowConfig builder];
    [configBuilder withToken:token];
    [configBuilder withApplicantId:applicantId];
    [configBuilder withDocumentStep];

    Builder *faceStepVariantBuilder = [ONFaceStepVariantConfig builder];
    [faceStepVariantBuilder withVideoCaptureWithConfig:[[VideoStepConfiguration alloc] initWithShowIntroVideo: YES]];
 
    NSError *faceVariantStepConfigError = NULL;
    ONFaceStepVariantConfig *faceStepVariant = [faceStepVariantBuilder buildAndReturnError: &faceVariantStepConfigError]; 

    [configBuilder withFaceStepOfVariant:faceStepVariant];
    NSError *configError = NULL;

    ONFlowConfig *config = [configBuilder buildAndReturnError:&configError];

**Comment by ramprasad-parajuli** [comment]
@gavaliswapnil Could you please provide us with the onfido sdk version number?

**Comment by gavaliswapnil** [comment]
> @gavaliswapnil Could you please provide us with the onfido sdk version number?

14.0.0

**Comment by keremgund** [comment]
Hi @gavaliswapnil, 
Onfido iOS SDK 14.0.0 version is compatible with Xcode 11.x versions. 
As far as I see from the issue description, you have told that you're using Xcode 10.3 with 14.0.0 Onfido SDK.
Could you double check those version numbers ?
Also, it would be really helpful for us if you can record and share the video with us to show the issue.  

Thanks,
Kerem

**Comment by gavaliswapnil** [comment]
> Hi @gavaliswapnil,
> Onfido iOS SDK 14.0.0 version is compatible with Xcode 11.x versions.
> As far as I see from the issue description, you have told that you're using Xcode 10.3 with 14.0.0 Onfido SDK.
> Could you double check those version numbers ?
> Also, it would be really helpful for us if you can record and share the video with us to show the issue.
> 
> Thanks,
> Kerem
I am using Xcode 10.3 with 14.0.0 Onfido SDK. 
below is a video link:
https://drive.google.com/open?id=1y1wLChrBNsqh0o2guq0CuMI7UZ99Obcw

**Comment by keremgund** [comment]
Hi @gavaliswapnil ,
Sorry, I meant iphone screen recording.

Kerem

**Comment by gavaliswapnil** [comment]
> Hi @gavaliswapnil ,
> Sorry, I meant iphone screen recording.
> 
> Kerem

Actually, it happen randomly.

**Comment by keremgund** [comment]
Hi @gavaliswapnil 
We have tried to integrate SampleApp on Xcode 10.3 with 14.0.0 Onfido SDK and we got an error as I expected, see the screenshot please.

![image](https://user-images.githubusercontent.com/49163858/69152648-b5f07280-0ad4-11ea-8110-6a92f58ad4f7.png)

So, can you please confirm those versions ? 

Also, despite of the fact that it happens randomly, it's important for us to have screen recording to understand the issue. If you can't take a screen recording, I will need more details about what exactly you mean by "seems to disappear". 

Thanks,
Kerem

**Comment by gavaliswapnil** [comment]
> Hi @gavaliswapnil
> We have tried to integrate SampleApp on Xcode 10.3 with 14.0.0 Onfido SDK and we got an error as I expected, see the screenshot please.
> 
> ![image](https://user-images.githubusercontent.com/49163858/69152648-b5f07280-0ad4-11ea-8110-6a92f58ad4f7.png)
> 
> So, can you please confirm those versions ?
> 
> Also, despite of the fact that it happens randomly, it's important for us to have screen recording to understand the issue. If you can't take a screen recording, I will need more details about what exactly you mean by "seems to disappear".
> 
> Thanks,
> Kerem

Actually I am using react-native node module. its contains objective c code. but Xcode didn't show any compile error on the screen.

**Comment by keremgund** [comment]
Hi @gavaliswapnil ,
First of all, I think it would be good to check your integration with comparing sample project here: https://github.com/onfido/onfido-sdk-react-native-sample-app

If you still don't see any issue related with integration, we need to have screen recording to understand the issue. You have said that it happens randomly, but it's crucial for us to see the issue otherwise it's not possible to make further investigation as we're not able to reproduce the same issue.

Also, it's worth to try to upgrade Onfido SDK version to 16.0.0 and check whether the issue still exists.

Thanks,
Kerem

**Comment by keremgund** [comment]
Closing the issue due to lack of response. Please open new one if you need support.
