### ISSUE TITLE
withDocumentStep should allow specific document types

### ISSUE THREAD

**Issue by benqo** [onfido/onfido-ios-sdk#123]
The **withDocumentStep** function only supports one or all document types to be allowed. It should also be possible to specify an array of supported documents, e.g. **withDocumentStep(ofTypes: [Onfido.DocumentType])**

### Version info:

- Cocoapods: 16.0.0

**Comment by anuragajwani** [comment]
Hi @benqo ,

Thanks for raising the issue. We currently don't support document types being specified by the integrator to be captured during the document step process.

I will add this to the feature request and open a ticket internally. We will update with more information as we get it.

Sorry about the inconvenience,
Anurag

**Comment by MatthewPringle** [comment]
Is there a way to do this in iOS as we only want Passport and Driving Licence for the UK.

We have been able to easily do it in the Javascript SDK

**Comment by whenislunch** [comment]
Any update on this? We want to exclude proof of residence from the document step as we do not accept this document.

**Comment by MatthewPringle** [comment]
@whenislunch in the end I'm allowing the user to select which documents to upload before opening Onfido. Seems like the wrong way but I could not find a different way of doing it.

I find it odd how their iOS, Android and Javascript UIs differ in terms of options and how it is presented to the user.

**Comment by davecoffin** [comment]
Agreed, this was very confusing...you should at least update your documentation to indicate that you can either use any or one document type.

**Comment by MatthewPringle** [comment]
Has this feature ever been looked at?

**Comment by abozaidibrahimON** [comment]
@MatthewPringle, thanks; this feature is already shipped, 
please check [documentation](https://github.com/onfido/onfido-ios-sdk#flow-customization)  under
Customize the document type selection screen
