### ISSUE TITLE
Cannot be used with Xcode 9.1

### ISSUE THREAD

**Issue by mluisbrown** [onfido/onfido-ios-sdk#13]
When importing Onfido using Xcode 9.1 you get the error message:

`Module compiled with Swift 4.0 cannot be imported in Swift 3.2.2: ....Pods/Onfido/Onfido.framework/Modules/Onfido.swiftmodule/x86_64.swiftmodule`

I have tried this with both `3.0.0` and `4.0.1`. They are both built with the Swift compiler from Xcode 9. Binary compatibility between Swift 3.2.x and Swift 4.0.x is only guaranteed if both have been built by the same version of the compiler.

**Comment by anuragajwani** [comment]
Hi @mluisbrown,

We are aiming to release a new version of the framework tomorrow with the latest compiler that is packaged with Xcode 9.1.

Sorry for the inconvenience,
Anurag

**Comment by anuragajwani** [comment]
@mluisbrown the new version support Xcode 9.1 will be released on Monday to allow some time for reliable testing.

Sorry for the additional inconvenience,
Anurag

**Comment by mluisbrown** [comment]
Thanks @anuragajwani 👍

**Comment by anuragajwani** [comment]
@mluisbrown We have released version 5.0.0 of the SDK to support Swift 3.2.2 and Swift 4.0.2

**Comment by mluisbrown** [comment]
Thanks @anuragajwani All fine now 👍
