### ISSUE TITLE
App crashes with specific document step in iOS

### ISSUE THREAD

**Issue by trdevendran** [onfido/onfido-ios-sdk#132]
Hi, I'm working on a react-native app with the native code as mentioned below but getting app crash,

### What was the expected behaviour?
I was tried to open document capture for specified document type such passport or driving license or International ID instead of choose document type with default document step list with Onfido SDK.

### What happened instead?
If we need to implement our customised flow instead of document step with Onfido SDK then we are not supposed to use the latest withSDKToken, because applicantID should be not be passed with withSDKToken function. If we aren't passing applicantID then customised flow getting exception and so I've used the deprecated method.

This screenshot contains withSDKToken() and with ApplicantID. You can see the exception as below:
<img width="993" alt="Screenshot 2020-01-09 at 1 16 39 PM" src="https://user-images.githubusercontent.com/12223179/72250182-01c91f00-3621-11ea-93f1-c67f8c3f4d0d.png">

This screenshot contains withSDKToken() and with customized document step without applicantID. You can see the exception as below:
<img width="998" alt="Screenshot 2020-01-08 at 8 30 44 PM" src="https://user-images.githubusercontent.com/12223179/72250301-4654ba80-3621-11ea-8175-40579e015dc2.png">

### Version info:

- Cocoapods: 1.7.2
- Onfido SDK (Debug): 16.1.0
- iOS: 13.3
- Xcode:11.3
- Simulator: 11 Pro

### Integration configuration:
```
@objc(OnfidoSDK)
class OnfidoSDK: NSObject {
  @objc func startSDK(_ token: String, type: Int, applicantId: String,
                      resolver resolve: @escaping RCTResponseSenderBlock,
                      rejecter reject: @escaping RCTResponseSenderBlock) -> Void {
    DispatchQueue.main.async {
      self.run(withToken: token, type: type, applicantId: applicantId, resolver: resolve, rejecter: reject)
    }
  }
  
  private func run(withToken token: String, type: Int, applicantId: String,
                   resolver resolve: @escaping RCTResponseSenderBlock,
                   rejecter reject: @escaping RCTResponseSenderBlock) {

    var docType = DocumentType.nationalIdentityCard
    if type == 1 {
      docType = DocumentType.passport
    } else if type == 2 {
      docType = DocumentType.drivingLicence
    }
    let config = try! OnfidoConfig.builder()
    .withToken(token)
    .withApplicantId(applicantId)
    .withDocumentStep(ofType: docType, andCountryCode: "EE")
    .withFaceStep(ofVariant: .photo(withConfiguration: nil))
    .build()
    
    let onfidoFlow = OnfidoFlow(withConfiguration: config)
      .with(responseHandler: {[weak self] response in
        switch response {
          case let .error(error):
            self?.dismiss()
            reject([error.localizedDescription])
          case .success(_):
            self?.dismiss()
            resolve(["Sucess"])
          case .cancel:
            self?.dismiss()
        default:
            reject(["Unknown Error"])
        }
      })
    do {
      let onfidoRun = try onfidoFlow.run()
      UIApplication.shared.windows.first?.rootViewController?.present(onfidoRun, animated: true)
    } catch {
      // iOS simulator does not work because of camera
      showAlert(message: "Couldn't start Onfido flow...(iOS Simultor does not work)")
    }
  }
```

### Developer Note:
I know well that applicantID is not supposed to be used but just ensuring the cases here. I'm able to make it work when I used deprecated methods as below but need to know the root cause of this issue with latest functions.
     .withToken(token)
    .withApplicantId(applicantId)
    .withDocumentStep(ofType: docType, andCountryCode: "EE")

### Steps to reproduce:
 Exception throws when above function(startSDK) is getting called.

Thanks for supporting!

**Comment by anuragajwani** [comment]
Hi @trdevendran 

There are two ways to tell the SDK against which applicant to upload the images:

1. Specifying the applicant id by `withApplicantId(_:)`. In this case we must authenticate with Onfido's backend server using a mobile token (`withToken(_:)`).
2. Specifying both the applicant id and authentication using SDK token. In this scenario you have to generate a token using the endpoint `/sdk_token` (see https://github.com/onfido/onfido-ios-sdk#31-sdk-tokens). The generated `/sdk_token` encompasses both token and applicant. **Highly recommended**.

Thus if you use SDK token you are giving us both token and applicant id in a single string. However if you do not generate an SDK token then you must provide to us the mobile and token and the applicant id.

That being said the crash you have encountered is expected.

The mobile token mechanism has been deprecated to allow integrators to migrate to the new SDK token mechanism. If you are generating SDK tokens then there is no need to call applicant id. However if you are using mobile token (generated through the Onfido dashboard) then you must supply applicant id.

I would encourage you to have a read https://github.com/onfido/onfido-ios-sdk#31-sdk-tokens as at some point we will cut off access to mobile token from future SDK releases.

Hope that helps,
Anurag

**Comment by trdevendran** [comment]
This issue has been resolved when I use JWT(which is generated with an API call of Onfido) with the function of **withSDKToken**
