### ISSUE TITLE
Crash on runtime for a few users (Fatal Exception: NSGenericException)

### ISSUE THREAD

**Issue by iangmaia** [onfido/onfido-ios-sdk#137]
### What was the expected behaviour?

Onfido SDK hopefully shouldn't crash.

### What happened instead?

We're receiving via our crash reporting tools some crashes from the Onfido SDK. They don't happen very often, but have been happening consistently for a while.

This is what is crashing:

```
Fatal Exception: NSGenericException
*** -[AVCaptureSession stopRunning] stopRunning may not be called between calls to beginConfiguration and commitConfiguration
```

This is the full stack of the crash report:

<img width="680" alt="Screenshot 2020-02-20 at 09 56 18" src="https://user-images.githubusercontent.com/2152244/74917155-5cdff580-53c7-11ea-8988-04ecf0f7c85f.png">

### Version info:

- Onfido SDK (Debug/Release): 16.1.0 (Carthage)
- iOS: 12 and 13
- Xcode: 11.1
- Device/Simulator: Various
- Device/Simulator language: Various, but mostly nl-NL

### Steps to reproduce:

We could not exactly reproduce this, but perhaps from the crash report it is possible to investigate.

**Comment by keremgund** [comment]
Hi @iangmaia 
Thanks for reporting the issue. We will investigate the it and keep giving update here.

Kerem

**Comment by keremgund** [comment]
Hi @iangmaia ,
We have been trying to reproduce the same crash but unfortunately couldn't reproduce it so far. 
To be able to identify this issue better, could you provide information below to us ?

- Whats your SDK flow configuration ? (i.e Doc + Selfie or Doc + Liveness)
- Crash message you have shared in description and the one in screenshot are actually different. 
Could you clarify which message is related with this crash 

`*** -[AVCaptureSession stopRunning] stopRunning may not be called between calls to beginConfiguration and commitConfiguration
`
or 

`no active/enabled connections.`

- You have told that device/OS version varies, but wanted to ask it again. Is there any common OS/device version for this crash ?

Thanks,
Kerem

**Comment by keremgund** [comment]
Closing the issue due to lack of response.
Please open new one if you still need support.

Thanks,
Kerem
