### ISSUE TITLE
User cannot choose to capture folded paper documents for French driving license

### ISSUE THREAD

**Issue by jeremie-l** [onfido/onfido-ios-sdk#139]
### What was the expected behaviour?

In the Release Notes for 16.1.0 it says:
"UI: User can choose to capture folded paper documents for French driving license and italian identity document"

When I add a document step for french Driving licence for the country France, I should have a popup asking if I have a Plastic Card or Folder Paper, and the correct UI should be displayed.

`.withDocumentStep(ofType: .drivingLicence, andCountryCode: "FR")`

### What happened instead?

I have no popup asking me for Plastic Card or Folder Paper, all I can do is take a picture for a Plastic Card driving licence.

If I add just add:
`.withDocumentStep()`
and select Driving Licence and France, I have a popup

### Version info:

- Onfido SDK:
16.1.0

**Comment by raulhurtoi** [comment]
Hello,

I am a Product Support engineer here at Onfido and I will be assisting with your query today. 

Please note that when you pass the "andCountryCode" parameter it needs to be under the 3 letter ISO code format. In your case, this would be "FRA". I have tested this on my end and the option for the foldable document is displayed when the country code consists of 3 letters. 

Please let me know if there is anything else I can help you with.

Regards,
Raul

**Comment by raulhurtoi** [comment]
Hello,

Please note that I also passed your feedback to the appropriate team and we are going to update our documentation on this matter.

Regards,
Raul

**Comment by jeremie-l** [comment]
Ok, thanks for the info
