### ISSUE TITLE
Type field of DocumentResult is "unknown" only for configs with residencePermit

### ISSUE THREAD

**Issue by martin-lalev** [onfido/onfido-ios-sdk#142]
### What was the expected behaviour?

Configuring `OnfidoBuilder` with `DocumentType` of `residencePermit` should result in `DocumentResult` with `type` field equal to  `"residencePermit"`. 

### What happened instead?

The `type` of `DocumentResult` is `"unknown"`

### Version info:

- Cocoapods (if applicable): 1.8.3
- Onfido SDK (Debug/Release): 16.1.0
- iOS: 13.2.2
- Xcode: 11.2.1
- Device/Simulator: iPhone 11 Simulator
- Device/Simulator language: en

### Integration configuration:

```
            var builder = OnfidoConfig.builder()
                .withToken(apiToken)
                .withApplicantId(applicantId)
                .withCustomLocalization()
                .withDocumentStep(ofType: .residencePermit, andCountryCode: "POL")

            let onfidoFlow = OnfidoFlow(withConfiguration: try builder.build())
                .with(responseHandler: responseHandler, dismissFlowOnCompletion: false)

            let onfidoRun = try onfidoFlow.run()
```

### Steps to reproduce:

Run the OnfidoFlow with the configuration above in sumulator. In the success response, the documents have type = unknown. 

### Additional notes:

At first I thought that this was because of the black pictures coming from simulator, however the `type` is correct for other `DocumentType`s

**Comment by anuragajwani** [comment]
Hi @martin-lalev,

The document type on the response is from the server. I have relayed this information to the team to clarify this information.

Sorry for the confusion,
Anurag

**Comment by martin-lalev** [comment]
Hey, looks like this was fixed on Android
https://github.com/onfido/onfido-android-sdk/issues/103
However it is highly probable that this fix is now causing:
https://github.com/onfido/onfido-android-sdk/issues/120

**Comment by keremgund** [comment]
Hello @martin-lalev ,
Although we show residence permit as document type on SDK, our document classification on backend doesn't have support for residence permit yet. 
As SDK returns backend classification to the client, seeing "undefined" is expected behaviour for now. 

Sorry for the late reply and inconvenience,
Kerem

**Comment by martin-lalev** [comment]
Hey thanks for your reply.

I just wanted to make sure this is also communicated with the Android and backend team and any work on those issues: https://github.com/onfido/onfido-android-sdk/issues/120 and https://github.com/onfido/onfido-android-sdk/issues/103 ) , won't introduce a new issue on iOS. Note that at the end of the /120 it was stated that some new version would be released.

**Comment by keremgund** [comment]
Yes we're all aligned with android and backend in terms of this issue. So my last statement won't be changed with the next android release. Android and iOS will be aligned in terms of returning document types.

Kerem
