### ISSUE TITLE
Onfido Flow crashing for small percentage of users after taking a picture

### ISSUE THREAD

**Issue by martin-lalev** [onfido/onfido-ios-sdk#143]
### What was the expected behaviour?

Onfido flow should not crash

### What happened instead?

For a few users, Onfido crashes with the following crash log:

```
0  Onfido                         0x105c8ce88 $s6Onfido15FlowCoordinatorC29registerClosuresWithContainer33_27E525F934E286498456E59DEC260473LLyyFAA25NavigationControllerProxyVAA8Resolver_pcfU_ySo06UIViewN0C_SbtcfU_ + 164
1  Onfido                         0x105c68634 $s6Onfido30DocumentCaptureSideCoordinatorC010showCameraC6Screen33_B2854CC17D8CD42A16F8C976C2A7CFCFLLyyF + 312
2  Onfido                         0x105c6363c $s6Onfido26DocumentCaptureCoordinatorC07captureB033_3FA25FCB81C41764B346C75F743B18B1LL03forB11TypeAndSideyAA0bopQ0O_tF + 292
3  Onfido                         0x105c63f9c $s6Onfido26DocumentCaptureCoordinatorC20capturedSuccessfully19documentTypeAndSide04withC7ResultsyAA0bhiJ0O_AA0B6ResultVtF + 188
4  Onfido                         0x105c68bcc $s6Onfido30DocumentCaptureSideCoordinatorC6upload33_B2854CC17D8CD42A16F8C976C2A7CFCFLL7capture8validate18withSuccessHandler0s14UploadProgressU008andErrorU0yAA5FrameV_SbyycySfcys0Y0_pctFyAA0B6ResultVcfU_ + 140
5  Onfido                         0x105bebfdc $s6Onfido21ApiDocumentRepositoryC3add8document14withValidation03forC11TypeAndSide0G17CompletionHandler0g14UploadProgressN0010andFailureN0yAA5FrameV_SbAA0cjkL0OyAA0C6ResultVcySfcys5Error_pctFyAPcfU_TA + 40
6  Onfido                         0x105c4fba4 $s6Onfido07DefaultA3ApiC14handleResponse33_0116CBBC882D682CC6461F2D18380CF8LL03apiE021withCompletionHandler010andFailureO0013resendRequestO0yAC0cE0AELLV_yxXEys5Error_pSg_q_SgtcyyctSeRzSeR_r0_lF + 1036
7  Onfido                         0x105c4f758 $s6Onfido07DefaultA3ApiC6upload0D4Data6toPath21withCompletionHandler010andFailureJ00K6Upload0K15MaybeParametersyAA0mE0V_SSyxcys5Error_pSg_q_SgtcySfcSDySSypGSgtSeRzSeR_r0_lFy10Foundation0E0VSg_So13NSURLResponseCSgANtcfU1_yycfU_ + 400
8  Onfido                         0x105c53030 $s6Onfido07DefaultA3ApiC6upload0D4Data6toPath21withCompletionHandler010andFailureJ00K6Upload0K15MaybeParametersyAA0mE0V_SSyxcys5Error_pSg_q_SgtcySfcSDySSypGSgtSeRzSeR_r0_lFy10Foundation0E0VSg_So13NSURLResponseCSgANtcfU1_yycfU_TA + 72
9  Onfido                         0x105bf99b0 $sIeg_IeyB_TR + 28
```

The crashes are a very small percentage. They appear from iOS 12 and above for various devices. One user reported this was happening even after they logged in/out of the app and updating it.

### Version info:

- Cocoapods (if applicable): --
- Onfido SDK (Debug/Release): 16.1.0
- iOS: 12+ and 13+
- Xcode: --
- Device/Simulator: Various devices
- Device/Simulator language: seems to be `en`

### Steps to reproduce:

Seems to be an edge case, which we cannot reproduce. One user sent a video where:
- Onfido flow was being presented with driving license
- The user takes a picture - random one, not of actual license
- After a delay of about 1 second the app crashes

**Comment by ramprasad-parajuli** [comment]
Hi @martin-lalev 

Thanks for letting us know. We will look into this and will update this issue when we have more info.

**Comment by chadanuk** [comment]
@ramprasad-parajuli  A client of ours (using the sdk through the cordova bridge in the app we built) Has reported something similar but he thinks the order of the video flow actually impacts this, see below...

It might be that this is unrelated but it "feels" similar.

"This happens on every attempt when the SDK sequence is Selfie>Speak>Look Over Left Shoulder, but doesn't happen on sequence Selfie>Look Over Left Shoulder>Speak."

**Comment by ramprasad-parajuli** [comment]
@chadanuk Thank you for the suggestion. I have let our team know and we will look into it.

**Comment by anuragajwani** [comment]
@chadanuk 

thanks for sharing the steps to reproduce. We will look into the issue and update you as soon as we have something

Thanks,
Anurag

**Comment by anuragajwani** [comment]
@chadanuk 

does the crash happen on completion of the liveness video? i.e. on capture or during/completion of video upload?

**Comment by keremgund** [comment]
Closing the issue due to lack of response. 
Please open new one if you still need support.

Thanks,
Kerem
