### ISSUE TITLE
Strings file not updated to reflect new release

### ISSUE THREAD

**Issue by anandwahed** [onfido/onfido-ios-sdk#144]
### What was the expected behaviour?

The `Localizable.strings` file should reflect the changes shown in the migration guide to the latest version of the SDK(17.0.0)

### What happened instead?

The `Localizable.strings` file seems to have been updated 3 months back and the latest keys mentioned in the SDK 17.0.0 are not present.

### Version info:

- Onfido SDK (Debug/Release): 17.0.0

**Comment by keremgund** [comment]
Hi @anandwahed ,
Thanks for reporting the issue. I also confirmed that there was a issue about updating Localizable.strings file. I will let you know once we apply and deliver the fix.

Sorry for the inconvenience,
Kerem

**Comment by keremgund** [comment]
Hi again, just wanted to give you an update. 
We have fixed the issue and the fix will be delivered as a part of next release. 
I will let you know once we release the fix.

Kerem

**Comment by keremgund** [comment]
Hi @anandwahed, we have published 18.0.0 version which contains fix for this issue.
Please upgrade your SDK version to 18.0.0 and let me know the result.

Thanks,
Kerem

**Comment by keremgund** [comment]
Closing the issue due to lack of response, please open new one if you need further support.

Kerem
