### ISSUE TITLE
Swift Package Manager support?

### ISSUE THREAD

**Issue by xMythicx** [onfido/onfido-ios-sdk#145]
Support for Swift Package Manager.

**Comment by anuragajwani** [comment]
Hi @xMythicx 

Swift package manager does not support binary distribution yet as far as I understand. The support for binaries proposal has been accepted but I don’t think it’s been developed + merged. Even less released.

If there is any information I have missed please let me know.

You can follow the proposal:
https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md

Anurag
