### ISSUE TITLE
Do we need to provide a country code in order to make a document step?

### ISSUE THREAD

**Issue by shayoke** [onfido/onfido-ios-sdk#147]
It's unclear if a country code is required in order to create a document step when using the iOS SDK.

The README has the example:
```
let config = try! OnfidoConfig.builder()
...
    .withDocumentStep(ofType: .drivingLicence, andCountryCode: "GBR")
...
```
However the [Android SDK](https://github.com/onfido/onfido-android-sdk) has the `CountryAlternatives.NO_COUNTRY` option to pass in and according to [api.onfido.com/v3](https://documentation.onfido.com/#documents) the `issuing_country` field is also optional.

Passing in an empty string in the `andCountryCode` field appears to work fine for passport and driving license document types, however this is not documented.

Please let us know if we can pass "NO_COUNTRY" or an empty string into this field, and if there are any potential errors we could face not using this value.

Thank you.

- Onfido SDK (Debug/Release): Release/16.0.0
- iOS: 11.0+
- Xcode: 11.1+

**Comment by ramprasad-parajuli** [comment]
@shayoke The example in the readme section you provided is to showcase different ways to configure the document step. You could configure the document step like below:
```
let config = try! OnfidoConfig.builder()
    .withSDKToken("YOUR_SDK_TOKEN_HERE")
    .withWelcomeStep()
    .withDocumentStep()
    .withFaceStep(ofVariant: .photo(withConfiguration: nil)) // specify the face capture variant here
    .build()
```
If you use the above configuration, then the user will have the option to choose the document type they want to upload and the country selection screen will be displayed as well.
We have documented the above configuration here - https://github.com/onfido/onfido-ios-sdk#swift-10

**Comment by shayoke** [comment]
@ramprasad-parajuli - thanks for getting back to me!

We would ideally like the end user to have to only input information if it's necessary. 

You have given me two options: 
1. Specify the document type and the country code
2. Make the user manually enter the country and document type

As I mentioned above, the other two SDK's have the option to not specify the country and only specify the document type, but that is not a documented feature - apparently on iOS only. 

Sending an empty string to the `countryCode` field also appears to work correctly - I can specify `.passport` or `.drivingLicence` and the dedicated UI for each is presented as expected.

What happens in the SDK when the document type is selected and the country code is not? Are there any potential issues using the SDK in this way?

**Comment by ramprasad-parajuli** [comment]
@shayoke you are correct, the user will see a dedicated UI screen (camera) when sending an empty string to the countryCode field and specifying a document type.
I will discuss it with our team regarding the above behavior and to include it in our iOS SDK documentation page.

> What happens in the SDK when the document type is selected and the country code is not? Are there any potential issues using the SDK in this way?
There are no potential issues or implications if a country code is not mentioned as after the document is uploaded and the flow is completed, the Onfido Engine will classify the document and the extract the issuing_country after processing the document and it does not depend on the uploaded document object for the issuing_country.

I hope this helps. Let me know if you have additional questions or concerns.

**Comment by shayoke** [comment]
> There are no potential issues or implications if a country code is not mentioned as after the document is uploaded and the flow is completed, the Onfido Engine will classify the document and the extract the issuing_country after processing the document and it does not depend on the uploaded document object for the issuing_country.

That's great, thank you very much. We'll pass an empty string into that field moving forward - it would be great to see this documented as well!
