### ISSUE TITLE
No loading spinner to indicate the user has uploaded a document or selfie.

### ISSUE THREAD

**Issue by eip-curve** [onfido/onfido-ios-sdk#148]
### What was the expected behaviour?

On version 17.0.0, running from simulator (iPhone 11) or device (iPhone 6s) (on sandbox environment), whether it be a picture of an ID or the selfie picture, when the user taps the "my *ID* is readable" or "my selfie is clear" button, the user should see immediate feedback such as a loading indicator that shows them the picture is attempting to upload to the server.

### What happened instead?

When "my *ID* is readable" or "my selfie is clear" button are tapped there is no loading spinner or anything to indicate that something is in progress/that the user is uploading the picture upon button tap.

### Version info:
Xcode: 11.1
Device: iPhone 6s 12.1.2
Simulator: iPhone 11 13.1
 
I'm not sure if I've missed anything or don't know why this happens. Should there be a spinner or some sort of indicator? I only get an "uploading" progress bar at the very end, right before the user sees the next screen.

**Comment by anuragajwani** [comment]
Hi @eip-curve,

I am able to reproduce this issue. Yes the upload progress bar should appear immediately. We will look into the issue and let you know once fixed.

Thank,
Anurag

**Comment by keremgund** [comment]
Hello @eip-curve  ,
I'm glad to say that we have just released 18.1.1 version which contains fix for this issue.
Let us know if you think problem still persists.

Kerem

**Comment by eip-curve** [comment]
Hi @keremgund 
I have tested it and it seems like it works for when you are uploading a selfie.

I have tested both of these and there is no loading indicator on both of these:
- Uploading the front of a drivers license
- Uploading the back of a drivers license

I haven't tested any other documents as I don't have any samples to do so.
