### ISSUE TITLE
how to best handle testing in the simulator?

### ISSUE THREAD

**Issue by ekimia** [onfido/onfido-ios-sdk#149]
### What was the expected behaviour?

A way to simulate a photo being taken

### What happened instead?
Stuck on a camera feed with no camera

Please detail what was the actual behaviour

### Version info:
- All the latest

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

### Steps to reproduce:

Open the flow on the ios sim

**Comment by ramprasad-parajuli** [comment]
@ekimia 

Thank you for flagging the issue to us.

The reason why the selfie step does not allow you to move forward is that we have recently added face detection on the selfie confirmation screen in the iOS version 17.0.0. We are already aware of this behavior with the emulators and are working on the fix now and will publish it as soon as possible. 

I will let you know once the fix has been implemented and released. Thank you for your patience.

**Comment by ekimia** [comment]
@ramprasad-parajuli i mean just when scanning a document when in the simulator, given there isnt a camera.

**Comment by anuragajwani** [comment]
@ekimia 

Currently you can capture empty image on simulator. On documents you can proceed after second attempt. On selfie however from 17.0.0 requires a face in the image otherwise it fails.

We don't currently support stubbing images on simulators. Additionally simulators can't make use of Macs camera.

**Comment by anuragajwani** [comment]
@ekimia https://github.com/onfido/onfido-ios-sdk/issues/146 is an issue around selfie specifically, updates on that thread might help your objective

**Comment by ekimia** [comment]
@anuragajwani how can i go for capturing an empty image? Would be very useful to have in the readme too!

**Comment by ramprasad-parajuli** [comment]
Hi @ekimia 
I'm glad to say that we have just released an 18.0.0 version which contains a fix for this problem.
Please check it out and let us know about the result.

**Comment by anuragajwani** [comment]
Hi @ekimia 

Has issue been solved in SDK version 18.0.0? We don't have any mechanism to stub/mock capturing images on the SDK on simulators for now. We have nothing planned yet.

Let me know if you are able to proceed on simulators with 18.0.0.

Thanks,
Anurag

**Comment by keremgund** [comment]
Closing the issue due to lack of response, please open new one if you need further support.

Thanks,
Kerem

**Comment by maurovisintin** [comment]
If you pick Passport as document the sdk seems to automatically take the picture when the document is in the frame.
In the simulator this never happens so you're stuck.

For other documents the sdk allows you to take the picture manually with the camera button so you can proceed.

**Comment by anuragajwani** [comment]
@maurovisintin are you UI testing the SDK? Or are you just going through the flow manually on a simulator?

**Comment by maurovisintin** [comment]
Going through the flow manually on a simulator
