### ISSUE TITLE
Hanging when switching the camera to take a picture of the back of the ID

### ISSUE THREAD

**Issue by ekimia** [onfido/onfido-ios-sdk#150]
### What was the expected behaviour?

There isnt any lag when asking the user to take a photo of the back

### What happened instead?

It hangs for seconds before the camera viewport shows

### Version info:

- Cocoapods (if applicable):
- Onfido SDK (Debug/Release): Release, latest
- iOS: 11.3
- Xcode: 11.3.1
- Device/Simulator: Device
- Device/Simulator language: English

### Integration configuration:

Basic configuration showing all screens minus face detection

### Steps to reproduce:

Try scanning an ID

**Comment by anuragajwani** [comment]
Hi @ekimia,

What do you mean basic configuration? do you do intro + doc + selfie ?

Anurag

**Comment by ekimia** [comment]
just doc, we pass in the drivers license type then it exits. When the UI switches to take a photo of the back, that's when the lag occurs.

**Comment by anuragajwani** [comment]
will look into it and update this thread once I have more information

**Comment by ekimia** [comment]
@anuragajwani thank you, let me know if you'd like a video to see as well.

**Comment by ekimia** [comment]
any update on this?

**Comment by anuragajwani** [comment]
@ekimia are you presenting a camera view before the SDK? I suspect that this happening when the camera is presented prior to the SDK and the camera hasn't stop running.

**Comment by anuragajwani** [comment]
@ekimia I haven't been able to reproduce this issue unfortunately. Can you reproduce consistently ? If so could you please share steps or sample do so please?

**Comment by keremgund** [comment]
Closing the issue due to lack of response, please open new one if you need support.

Kerem
