### ISSUE TITLE
[iOS 13] Close by swipe not call withResponseHandler

### ISSUE THREAD

**Issue by Bardiamist** [onfido/onfido-ios-sdk#154]
### What was the expected behaviour?

`withResponseHandler` should be called and `response.userCanceled` should be true.

### What happened instead?

`withResponseHandler` doesn't call.

### Version info:

- Cocoapods (if applicable): 1.9.1
- Onfido SDK (Debug/Release): 18.1.0 (Debug)
- iOS: 13.4.1
- Xcode: 11.4.1 (11E503a)
- Device/Simulator: Simulator
- Device/Simulator language: English

### Integration configuration:

```
[onFlow withResponseHandler:^(ONFlowResponse *response) {
        NSLog(@"withResponseHandler called");
```

### Steps to reproduce:

If on iOS 13 close Onfido by swipe from top to bottom (instead back button press) then `withResponseHandler` will not called (no "withResponseHandler called" in logs).

**Comment by anuragajwani** [comment]
Hi @Bardiamist,

I assume you are using the default `modalPresentationStyle` (basically you're not setting it) on the `UIViewController` returned by the Onfido SDK. On iOS 13 the default changes from `fullScreen` to `pageSheet`.

If that is the case then the Onfido iOS SDK does not support that modal presentations style. 

By the looks of it we haven't been explicit about this on the README. The comment on formSheet presentation on the SampleApp is only for iPads.

I have created a ticket to make this more explicit on our documentation as well as SampleApp. I will update this thread when we have any progress on this matter.

Sorry for the inconvenience caused,
Anurag

**Comment by Bardiamist** [comment]
Ok, I added
```
[onfidoController setModalPresentationStyle:UIModalPresentationFullScreen];
```
but strange that you use back arrrow icon instead cross icon then.
