### ISSUE TITLE
Received "Connection Lost" error

### ISSUE THREAD

**Issue by ImmanuelKannan** [onfido/onfido-ios-sdk#157]
### What was the expected behaviour?
Successfully uploading passport image.

### What happened instead?
Received a 'Connection Lost: There was a network error. Please check your connection' error alert when uploading passport. The network was stable, however.

### Version info:

- Onfido SDK (Debug/Release): 16.1
- iOS: 12.2
- Device/Simulator: iPhone 7

**Comment by andra-radu** [comment]
hi @ImmanuelKannan thank you for flagging the issue. Could you please let me know which token are you making use of to initialise the SDK?

**Comment by keremgund** [comment]
Hi @ImmanuelKannan,
I'm afraid we need more information to be able to proceed on this issue.  It would be great if you can answer questions below:

1- Is that issue intermittent or happening constantly ? 
2- Were you able to upload document at the end ? 
3- Do you have device logs belong to incident time to share with us ?
4- How did you confirm that "network connection was stable" ?
5- Do you have any certificate pinning configuration for the SDK ?

Thanks,
Kerem

**Comment by keremgund** [comment]
Closing the ticket due to lack of response. 
Please open new one if you need further support.

Thanks,
Kerem
