### ISSUE TITLE
Cannot take photo of back of Identity Card

### ISSUE THREAD

**Issue by ImmanuelKannan** [onfido/onfido-ios-sdk#158]
### What was the expected behaviour?

Should be able to successfully take a photo of the back of a National Identity Card.

### What happened instead?

The user sees a black screen only when trying to take a photo of the back of the National Identity Card. The front of the card was successfully captured.

![onfido_issue](https://user-images.githubusercontent.com/12892230/83740724-d2778500-a689-11ea-9a39-0a7df4ebd25d.png)

### Version info:

- Onfido SDK (Debug/Release): 16.1
- iOS: 13.3.1
- Device/Simulator: iPhone XS

**Comment by keremgund** [comment]
Hello @ImmanuelKannan ,
Thanks for reporting the issue. We have started to investigate this. 
I will inform you once had enough information to share.

Thanks,
Kerem

**Comment by keremgund** [comment]
@ImmanuelKannan Does your app establish connection to the device camera ?

**Comment by ImmanuelKannan** [comment]
> @ImmanuelKannan Does your app establish connection to the device camera ?

Hi @keremgund thanks for responding! Hmm, I’m not too sure what you mean, do you mind clarifying?

**Comment by keremgund** [comment]
Sure, Does your app require access to the camera at any time (apart from Onfido SDK) ? This issue could happen while both Onfido SDK and app try to access camera.

Kerem

**Comment by keremgund** [comment]
Closing the ticket due to lack of response. 
Please open new one if you need further support.

Thanks,
Kerem
