### ISSUE TITLE
SDK 5.1.0 Migration Guide

### ISSUE THREAD

**Issue by frootloops** [onfido/onfido-ios-sdk#16]
Hello,

I see you have deprecated `OnfidoConfig.builder().withApplicant(applicant)` and `responseHandler`. So can you update README with according to the changes and also can you explain reasons behind those changes?

Thanks,
Arsen

**Comment by rfreitas** [comment]
Hey Arsen,

We did mention it on the Migration Guide (https://github.com/onfido/onfido-ios-sdk/blob/master/MIGRATION.md#onfido-sdk-510-migration-guide) and updated the changed.

The reason behind the changes is two folded:

1. After talking with some customers, it seemed to us that creating an applicant on the backend and creating a 1:1 link with their user entity simplifies integration.
2. In the future we can move to JWTs which can be scoped to applicants, making the process more secure.
