### ISSUE TITLE
Add option to skip face detection on test devices

### ISSUE THREAD

**Issue by josepmc** [onfido/onfido-ios-sdk#160]
### Intro

Up to version 16 of the SDK, one was able to 'skip'/'submit anything as' face detection. Version 17 included a new face detection feature that will only allow the user to proceed should he upload a valid face.
This was recorded earlier as #149 .

### What is the expected behaviour?

We can configure (either via SDK options or similar) the face detection feature, so that it can be disabled in non-release builds.

### What happened instead?

When using real devices in device farms (e.g. BrowserStack), we don't have the possibility to change the image that the device gets. This effectively means that the SDK is unusable for testing anything other than a simulator.

### Steps to reproduce:

- Create a free account with BrowserStack
- Upload an app that uses the Onfido SDK
- Try to complete the SDK's steps

**Comment by anuragajwani** [comment]
Hi @josepmc,

We don't currently have any mechanism of circumventing face validation. We're looking into the issue and will get back to you when we have more information.

Anurag

**Comment by josepmc** [comment]
@anuragajwani Have you had a chance to discuss this with the team? As said, this issue is a serious blocker as it effectively means we need to circumvent Onfido whenever we want to do testing.

**Comment by anuragajwani** [comment]
@josepmc I have relayed the information to the team. Is it possible for you to avoid testing the Onfido SDK on devices for now?

**Comment by josepmc** [comment]
@anuragajwani Sadly not, it's pretty much integrated on the entire stack. We would need to do major work if we are to circumvent this (e.g. setting up a server to do Onfido for us, which is not what we should have).

**Comment by anuragajwani** [comment]
@josepmc I have updated the team with your status.

**Comment by anuragajwani** [comment]
@josepmc are you creating a check in Onfido as part of your testing?

**Comment by josepmc** [comment]
@anuragajwani yes, we do the full flow. In the iOS simulator and Android that will work without issues, but in iOS (non-sim) the face id is applied and it will sadly not work.

**Comment by anuragajwani** [comment]
Ok so just to double confirm you are creating a check on the Onfido backend when testing iOS simulator and Android but not iOS device. 

I am repeating this because I am mostly interested in whether you test the Onfido integration including the Onfido check creation in the backend. I understand that you are unable to complete the SDK flow on iOS device.

**Comment by keremgund** [comment]
Hi @josepmc , could you please answer @anuragajwani 's question so we can keep to investigate this problem ?

Thanks,
Kerem

**Comment by josepmc** [comment]
@keremgund The issue here is that we do have a full integration with Onfido (which we're unable to supplant/remove). In the simulator, we can easily continue because we have automated the onfido flow, but in the real device the face id check keeps us from progressing.

**Comment by keremgund** [comment]
Hi @josepmc,

I got your point now. But I'm afraid we can't provide this kind of functionality in short term as being able to skip client side validations bring security concerns. 

At the moment I can only suggest you to call SDK's success delegate function manually on device whenever you want to skip face or other type or detections. 

Thanks,
Kerem
