### ISSUE TITLE
Custom localization doesn't see default languages

### ISSUE THREAD

**Issue by JGanol** [onfido/onfido-ios-sdk#162]
### What was the expected behaviour?

Both custom and default localizations work.

### What happened instead?

Using Onfido prior to v18.x we had Dutch language localization added via OnfidoConfig.builder().withCustomLocalization(...) and for English default Onfido strings were used. After updating to v18.1 & v18.2 only Dutch is picked, no other localizations seems to be working.

### Version info:

- Cocoapods (if applicable): 1.8.4
- Onfido SDK (Debug/Release): 18.2.0
- iOS: 13
- Xcode: 11.3
- Device/Simulator: any
- Device/Simulator language: nl/en/fr

### Integration configuration:

```
OnfidoConfig.builder()
.withSDKToken(payload.onfidoToken)
.withCertificatePinning(certificatePinningConfiguration)
.withDocumentStep(ofType: documentType)
.withFaceStep(ofVariant: .photo(withConfiguration: nil))
.withAppearance(appearance.onfidoAppearance)
.withCustomLocalization(andTableName: "SdkLocalizable", in: Bundle(for: type(of: self)))
.build()
```

### Steps to reproduce:

Just start the flow, all strings are missing.

**Comment by anuragajwani** [comment]
@JGanol 

Just clear out some assumption before testing.

App supports:
- English
- Dutch
- French

(Example) Device preferred localisation is (in order):
- English
- Dutch

SDK shows Dutch language.

Is that correct?

**Comment by JGanol** [comment]
Hi @anuragajwani,
App supports: en/fr/nl/de
Device preferred localization: en/fr/nl/...
In this case our app picks EN. Onfido sdk picks NL, if we set up Dutch localization via withCustomLocalization.
But if we don't set up any localization customization, Onfido sdk is able to switch language, so in this case it will show EN.

**Comment by anuragajwani** [comment]
Hi @JGanol 

I just tested this out and everything seems to working fine on the SampleApp. Here is what I did:
1. Added support for Dutch, French and German (app base language is English)
2. Changed the SampelApp's "Verify Me!" button to display the language selected by the system i.e. "English", "French", etc..
3. Added Localizable.strings (this will be read by the SDK) file inside the app for all of the support languages (English, French, Dutch, German)
-- note: I have only override 1 key `"onfido_welcome_view_title" = "App {LANGUAGE}";`
4. Added `.withCustomLocalisation()` to the SDK config
5. Configured device preferred language (en, fr and nl in this order)
6. generate an SDK Token, replace the token string and run the app.

![Screenshot 2020-07-08 at 18 17 56](https://user-images.githubusercontent.com/7071488/86949942-5ae4bc00-c147-11ea-93b9-abf840ae6741.png)
![Screenshot 2020-07-08 at 18 18 24](https://user-images.githubusercontent.com/7071488/86949992-6b953200-c147-11ea-8dc0-7ef5aeba6c6c.png)
![Screenshot 2020-07-08 at 18 18 54](https://user-images.githubusercontent.com/7071488/86950033-7cde3e80-c147-11ea-952f-c1ce8f672fd0.png)
![Screenshot 2020-07-08 at 18 21 18](https://user-images.githubusercontent.com/7071488/86950233-d2b2e680-c147-11ea-8c9d-a026a7b4c49e.png)
![IMG_0002](https://user-images.githubusercontent.com/7071488/86950303-e8c0a700-c147-11ea-9319-35d6a32b12c6.PNG)

I have added a zip file with 2 videos:
1. where the preferred language is English -> app chooses English -> sdk chooses English
2. where the preferred language is dutch -> app chooses dutch -> sdk displays the dutch override from the app

I have also included the SampleApp with the modifications. Please remember to generate an sdk token if you plan to test the SampleApp. Also you might need to change the bundle/app identifier.

[localisation_test_github.zip](https://github.com/onfido/onfido-ios-sdk/files/4892241/localisation_test_github.zip)

[SampleApp.zip](https://github.com/onfido/onfido-ios-sdk/files/4892249/SampleApp.zip)

**Comment by anuragajwani** [comment]
Hi @JGanol 

Does the above clears out your issue?

**Comment by JGanol** [comment]
@anuragajwani 

It took me a while but i managed to create two demos, one working and one not, which you can use for investigating the issue. Two projects consist of a DemoFrm & DemoApp, and the only difference for them is that SDKLocalizable.strings in one project contain only Dutch (which doesn't work if you have English chosen) and another contains both Dutch and an empty English. 
In our real project even empty English doesn't help. But let's concentrate on demo first, maybe the roots are the same. 

For working projects please add your onfido token and update signature for running on device.

Best regards,
Julia

[OnfidoDemo_2020_v18.3.zip](https://github.com/onfido/onfido-ios-sdk/files/4927693/OnfidoDemo_2020_v18.3.zip)

**Comment by anuragajwani** [comment]
@JGanol 

Thanks for sharing the DemoApp, it definitely helps. I can reproduce the issue now. I have created a ticket and will update you when we make some progress.

Sorry for the inconvenience caused,
Anurag

**Comment by aitorct** [comment]
It's happening to us as well, we have a custom localization file for Catalan, and it always shows the Onfido SDK in Catalan no matter the language the phone has been set.
Hope this can be fixed soon!

**Comment by anuragajwani** [comment]
@JGanol we have the fix in our development branch now and its awaiting release. I'll update you once we have released.

**Comment by anuragajwani** [comment]
@JGanol @aitorct 

We have released the fix for this issue in versions [18.3.2](https://github.com/onfido/onfido-ios-sdk/blob/master/CHANGELOG.md#1832---2020-08-06).

Please let us know if there are any issues, otherwise we can close this ticket.

**Comment by JGanol** [comment]
@anuragajwani ,
I tested version 18.3.2 and unfortunately it didn't work out for me. I can see native EN/FR, that are coming from Onfido when I switch languages. But now I cannot get NL, which I add like this (described in the ticket):
builder.withCustomLocalization(andTableName: "SdkLocalizable", in: Bundle(for: type(of: self)))
Do you need any demo app from my side?

**Comment by anuragajwani** [comment]
HI @JGanol 

I will look into it again today and tomorrow. Sorry for the inconvenience caused.

Anurag

**Comment by anuragajwani** [comment]
Hi @JGanol 

I have identified the issue. The share project has the app set to Dutch (Netherlands) or "nl-NL" whereas DemoFrm support Dutch or "nl". We now account for region-less localisation in the latest fix. You can find the potential fix in version [18.3.3-rc](https://github.com/onfido/onfido-ios-sdk/releases/tag/18.3.3-rc).

I have tested the solution against the project you provided this time instead of recreating the problem on our end. Last time I assumed that both projects were set to the Dutch (Netherlands) language hence why I missed this problem.

Could you please test 18.3.3-rc? We will be preparing a release soon. Please don't use 18.3.3-rc in production as we haven't done the necessary quality checks.

Sorry for the inconvenience,
Anurag

**Comment by JGanol** [comment]
Hi @anuragajwani,
I tried to embed 18.3.3-rc framework (as it is not released i couldn't use pods), but get an error that module cannot be imported.
Best regards,
Julia

**Comment by anuragajwani** [comment]
Hi @JGanol 

which version of Xcode are you using?

**Comment by JGanol** [comment]
@anuragajwani ,
yes, we reverted to xcode 11.3 because of some 3rd party dependency issues :(
Will try on xcode 11.5.
I remember you were also using 11.3 recently.

**Comment by anuragajwani** [comment]
@JGanol we are using 11.5 now

**Comment by JGanol** [comment]
Hi @anuragajwani, great news, i checked this release candidate - it works!

**Comment by anuragajwani** [comment]
@JGanol release 18.3.3 is now out. About Xcode version we are still using 11.3 on CI but 11.5 on development machines. Sorry about the confusion.

**Comment by anuragajwani** [comment]
@JGanol is this issue resolved?

**Comment by JGanol** [comment]
@anuragajwani , yes, thank you very much for fixing it!

**Comment by anuragajwani** [comment]
glad to hear that 😄
