### ISSUE TITLE
Onfido SDK crashing with "NSInvalidArgumentException: *** -[AVCapturePhotoOutput capturePhotoWithSettings:delegate" on iPhone SE

### ISSUE THREAD

**Issue by badikumar** [onfido/onfido-ios-sdk#163]
### What was the expected behaviour?

Do not crash the app and handle it gracefully.

### What happened instead?

App crashed

### Version info:

- Cocoapods (if applicable):
- Onfido SDK (Debug/Release): 18.0.0
- iOS: 13.5.1
- Xcode:
- Device/Simulator: iPhone SE
- Device/Simulator language:

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

### Steps to reproduce:

Please describe in as much detail as possible on how to reproduce the problem

iPhone SE running iOS 13.5.1 and press "Capture" (didTapCapture) button to experience crash with the following crash log:

NSInvalidArgumentException: *** -[AVCapturePhotoOutput capturePhotoWithSettings:delegate:] No active and enabled video connection
  CoreFoundation      0x1b97c4794  <redacted>
  libobjc.A           0x1b94e6bcc  objc_exception_throw
  AVFoundation        0x1c3afddbc  <redacted>
  Onfido              0x1011013b4  seg_libzOpen
  Onfido              0x1011d7074  seg_libzOpen
  Onfido              0x1011d1ff4  seg_libzOpen
  UIKitCore           0x1bd86c78c  <redacted>
  valr                0x100815ecc  facebook::react::JSIExecutor::defaultTimeoutInvoker
  UIKitCore           0x1bd27cfc8  <redacted>
  UIKitCore           0x1bd27d320  <redacted>
  UIKitCore           0x1bd27c344  <redacted>
  UIKitCore           0x1bd8a64fc  <redacted>
  UIKitCore           0x1bd8a7cc4  <redacted>
  UIKitCore           0x1bd88394c  <redacted>
  UIKitCore           0x1bd9049d0  <redacted>
  UIKitCore           0x1bd90754c  <redacted>
  UIKitCore           0x1bd8ff1c8  <redacted>
  CoreFoundation      0x1b9742c18  <redacted>
  CoreFoundation      0x1b9742b70  <redacted>
  CoreFoundation      0x1b97422f8  <redacted>
  CoreFoundation      0x1b973d328  <redacted>
  CoreFoundation      0x1b973cce8  CFRunLoopRunSpecific
  GraphicsServices    0x1c388738c  GSEventRunModal
  UIKitCore           0x1bd86b444  UIApplicationMain
  valr                0x1005e3510  <redacted>
  libdyld             0x1b95c48f0  <redacted>
IMAGES LOADED

MORE INFO:
device
*iPhone SE*
level
*fatal*
mechanism
*nsexception*
os
*iOS 13.5.1*
os.name
*iOS*
os.rooted
*no*
transaction
*Onfido.DocumentCaptureViewController*

![image](https://user-images.githubusercontent.com/17410263/85990476-63741e80-b9f2-11ea-913b-716dde90106f.png)

**Comment by anuragajwani** [comment]
Hi @badikumar 

Do you have the steps to reproduce this crash?

Anurag

**Comment by badikumar** [comment]
Hi, yes.

iPhone SE running iOS 13.5.1 and press "Capture" (didTapCapture) button to experience crash.

**Comment by anuragajwani** [comment]
Whilst I don't have a iPhone SE on 13.5.1 I have tried multiple devices and they all seem to work fine. If you any way we can consistently reproduce this crash in an example project that would be helpful.

Do you get the crash on the SampleApp? If you don't there might be something in your app that we haven't accounted for.

**Comment by keremgund** [comment]
Closing the issue due to lack of response. Please open new one if your problem persists.
