### ISSUE TITLE
UINavigationController's title does not get updated 

### ISSUE THREAD

**Issue by clapslock** [onfido/onfido-ios-sdk#170]
### What was the expected behaviour?

NavigationController's title gets updated to `"onfido_country_selection_toolbar_title" = "Select issuing country"`

### What happened instead?

NavigationController's is not updated. Value from the previous screen persists. (`"Verify your identity"`)
<img width="600" alt="Screen Shot 2020-07-27 at 10 05 04" src="https://user-images.githubusercontent.com/24473612/88518517-e76cf680-cff0-11ea-8287-2502eb3a1d87.png">

### Version info:

- Cocoapods (if applicable):
- Onfido SDK (Debug/Release):
- iOS: 13.5
- Xcode: 11.5
- Device/Simulator: iPhone 11
- Device/Simulator language: English (US)

### Steps to reproduce:

1. Launch Sample App 
2. Select Driver's License 
3. There's an incorrect copy used for the Select Issuing country screen's title

**Comment by anuragajwani** [comment]
Hi @clapslock 

The key `onfido_country_selection_toolbar_title` is used for the title (the big main label) and not for the navigation bar controller. I understand that the key naming is very confusing and I understand the expectation. We have some work in flight to rename the keys to make it clear where these keys are used and for more granular custom localisation.

To override the value of the navigation bar the key used is `onfido_welcome_view_toolbar_title`.

I'll update this issue once its awaiting release.

Sorry for the inconvenience,
Anurag

**Comment by clapslock** [comment]
That would be great @anuragajwani 🙂 

Would it also be possible for you to take into account keys used in Android Onfido SDK when the refactor happens? 
@AzimoLabs we share all translation keys between Android and iOS. I'm not saying they have to map 1:1 on both platforms (that would probably be impossible), but it would be nice if cases like `onfido_welcome_view_toolbar_title` where key exists on both platforms with different translations didn't happen. 

Thanks!

**Comment by anuragajwani** [comment]
@clapslock yes that is part of the plan already

**Comment by anuragajwani** [comment]
@clapslock Im glad to announce that we are now in the process of releasing improvement to the key names. We are doing so for all 3 SDKs (iOS, Android and Web). We are bringing key naming consistency where possible and renaming the keys so they are more explicit as to where these are used.

For now iOS will be the first to release (18.8.0). We are including a script to help you easily migrate from the old keys from 18.7.0 to 18.8.0.

Estimated release is early next week.

**Comment by anuragajwani** [comment]
Hi @clapslock 

we have release [18.8.0](https://github.com/onfido/onfido-ios-sdk/blob/master/CHANGELOG.md#1880---2020-10-13) which includes a renaming of most keys. The key names is now more explicit and the sdk is more cusotmizable (decoupled keys used in multiple screens).

Now to customise only the title on the navigation bar on the country selections screen override `onfido_app_title_country_select`.

If you have any issues please let us know. Otherwise if we have solved the issue please close the ticket.

Thanks,
Anurag
