### ISSUE TITLE
Error with Swift 4 / Pod Install

### ISSUE THREAD

**Issue by olliem36** [onfido/onfido-ios-sdk#18]
When I install the SDK via cocoa Pods I get the following error on build:

...Pods/Onfido/Onfido.framework/Onfido compiled with older version of Swift language (3.0) than previous files (4.0) file '...Pods/Onfido/Onfido.framework/Onfido' for architecture x86_64

I added to Podfile for my app target:

`pod 'Onfido'`

My Swift Language Version is set to 4.0. I'm also unable to manually set Onfido Target in the Pods project to Swift 4, it doesn't have a bundle identifier, presumably because of the above error.

Thanks in advance for your help!

**Comment by anuragajwani** [comment]
Hi @olliem36,

Which version of the `Onfido iOS SDK` did you install?

Anurag Ajwani

**Comment by olliem36** [comment]
Hi @anuragajwani,

Thanks for your response, I have just resolved the issue and wanted to post my findings here if it helps anyone else:

Cocoa pods was installing v 1.0 if i didn't explicitly set a version number. So, this was my first step:

`pod 'Onfido', '~> 5.3'`

However, because Onfido had version restrictions on other dependencies I was using I ran into another issue:

```
- `Alamofire` required by `Podfile`
- `Alamofire (= 4.6.0)` required by `Podfile.lock`
- `Alamofire (~> 4.5)` required by `AlamofireImage (3.3.0)`
- `Alamofire (~> 4.5)` required by `AlamofireNetworkActivityIndicator (2.2.0)`
- `Alamofire (< 4.5)` required by `Onfido (5.0.2)`
```

My solution was to remove `AlamofireImage` and use my own image downloader and remove `AlamofireNetworkActivityIndicator` altogether. This meant I could downgrade my Alamofire package to a version < 4.5
