### ISSUE TITLE
Crash on creating a new DrivingLicenceConfiguration

### ISSUE THREAD

**Issue by shayoke** [onfido/onfido-ios-sdk#185]
### What was the expected behaviour?

Creating a document step without any parameters:

```swift
        let documentStepConfiguration = DrivingLicenceConfiguration()
```

should create a driving license configuration to be used when setting up the Onfido flow.

### What happened instead?

This causes a `EXC_BAD_INSTRUCTION` with the error:

(when using the Sample App):
```
Onfido/DrivingLicenceConfiguration.swift: 11: 14: Fatal error: Use of unimplemented initializer 'init()' for class 'Onfido.DrivingLicenceConfiguration'
2020-09-28 14:34:34.100532+0100 SampleApp[60357:754851] Onfido/DrivingLicenceConfiguration.swift: 11: 14: Fatal error: Use of unimplemented initializer 'init()' for class 'Onfido.DrivingLicenceConfiguration'
```

### Version info:

- Cocoapods (if applicable): N/A
- Onfido SDK (Debug/Release): 18.6.0
- iOS: 13
- Xcode: 11.4
- Device/Simulator: Simulator
- Device/Simulator language: Swift

### Integration configuration:

The full code to cause a crash is: 

```swift        
let documentStepConfiguration = DrivingLicenceConfiguration()
```

Intended use: 
```swift

       let documentStepConfiguration = DrivingLicenceConfiguration()

        let config = try! OnfidoConfig.builder()
            .withSDKToken(sdkToken)
            .withWelcomeStep()
            .withDocumentStep(ofType: .drivingLicence(config: documentStepConfiguration))
            .withFaceStep(ofVariant: .photo(withConfiguration: nil))
            .build()
```

### Steps to reproduce:

Add the line above. 

### Workaround

Right now we have the following code in the app as a workaround: 
```
        let documentStepConfiguration = DrivingLicenceConfiguration(country: "")
```

And this appears to work.

**Comment by keremgund** [comment]
Hi @shayoke ,
If you don't want to set any custom configuration for drivingLicence doc type, then simply pass config as nil. You don't need to instantiate new object and pass it. There is no non-param initialiser for DrivingLicenceConfiguration class, so this is expected behaviour. (I just checked README.md and didn't find any example refers to creating `DrivingLicenceConfiguration()`)

Kerem

**Comment by shayoke** [comment]
Hi, thanks for getting back to us so quickly! We've made the change and started testing it now. We'll update here if there are any other issues found, but so far it appears to work fine on the simulator.
