### ISSUE TITLE
Disable "Select issuing country" selection list

### ISSUE THREAD

**Issue by ricfrank** [onfido/onfido-ios-sdk#188]
### What was the expected behaviour?

Is there anyway to disable the "Select issuing country" selection list ?

![screenshot](https://user-images.githubusercontent.com/892169/95448646-f57db280-0963-11eb-953d-5fdec9fe0e54.png)

**Comment by andra-radu** [comment]
Hi @ricfrank,
Unfortunately there is no way to disable the country selection. This is shown based on document type.
Please accept my apologies for the inconvenience caused. If you have any further questions or concerns please do not hesitate to contact us. I would be more than glad to assist you.

Kind regards, 
Andra

**Comment by keremgund** [comment]
Also this screenshot doesn't seem belong to iOS SDK, maybe https://github.com/onfido/onfido-sdk-ui ?
