### ISSUE TITLE
Warning: OnfidoSEGAnalyticsConfiguration.h:13:1: 'assign' property of object type may become a dangling reference; consider using 'unsafe_unretained'

### ISSUE THREAD

**Issue by lmmenge** [onfido/onfido-ios-sdk#199]
### What was the expected behaviour?

When integrating Onfido 18.10.1 into our project, I'd expect the Onfido framework to not have compiler warnings.

### What happened instead?

The following compiler warning is triggered:
```
/(...)/Onfido.framework/Headers/OnfidoSEGAnalyticsConfiguration.h:13:1:
'assign' property of object type may become a dangling reference; consider using 'unsafe_unretained'
```
### Version info:

- Cocoapods (if applicable): Not applicable
- Onfido SDK (Debug/Release): 18.10.1 (Debug)
- iOS: 14.2
- Xcode: 12.2
- Device/Simulator: Not applicable
- Device/Simulator language: Not applicable

### Integration configuration:

Our project has more warnings than usual enabled

### Steps to reproduce:

This seems related to `-Wobjc-property-assign-on-object-type`.

**Comment by keremgund** [comment]
Hello @lmmenge ,
I couldn't reproduce the issue with running/building SampleApp on github which points to 18.10.1 SDK version. 
Could you tell me how do you integrate with Onfido SDK, or even better to share example project which we can reproduce the issue.

Thanks,
Kerem

**Comment by keremgund** [comment]
Closing the issue due to lack of response.
Please open new one if you need further assistance.

Thanks,
Kerem

**Comment by lmmenge** [comment]
@keremgund sorry for the enormous delay in this.

Yes I still have these warnings. I've created a sample repository here https://github.com/lmmenge/onfido-double-quote which you can open and build in Xcode 13. There are multiple warnings, but you can filter the list, and if you search for `assign`, you should find it. If the warnings appear up once, then disappear, deleting your `DerivedData` folder should do the trick to bring them back.

<img width="1392" alt="Screen Shot 2021-10-16 at 16 20 14" src="https://user-images.githubusercontent.com/51199/137591048-50395f21-9110-492c-b9d4-2e0d29b9041c.png">
