### ISSUE TITLE
fileURL in uploadDocument/uploadLivePhoto

### ISSUE THREAD

**Issue by francisjervis** [onfido/onfido-ios-sdk#2]
I can't get images to upload (and can't see the source to see how you did it, either). Getting a crash with this code, apparently because UIImagePickerControllerReferenceURL is nil - having to include boilerplate code to get an NSURL to upload a newly captured image is a pain, the SDK should really handle this internally (ie accept a UIImage as one of the arguments instead of its URL), I think.

```
func imagePickerController(picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : AnyObject]) {

    let imageURL = info[UIImagePickerControllerReferenceURL] as! NSURL

    print (imageURL)


    OnfidoAPI.uploadDocument(curUsr["idHash"] as! String, "passport", imageURL, complete: { (document) in

        print (document)

        }) { (error) in
            print (error)
    }

}
```

Edit: I have still not been able to fix this satisfactorily. Uploading the image (eg to AWS) in order to get a URL to pass to the API is not an acceptable solution, the document images can/should be encoded and sent to your endpoint directly from the app. This echoes my comment on the web SDK requiring images to be sent to my server first...

However, when I specify the URL of a hosted image, I get a "NSLocalizedFailureReason=The file URL does not point to a file URL" error, which appears to be an Alamofire error: https://github.com/Alamofire/Alamofire/issues/1379

**Comment by ndcg91** [comment]
First save the image to disk and then convert it back to url, finally upload ussing alamofire


    func imagePickerController(picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : AnyObject]) {
        //get the image
        let image = info[UIImagePickerControllerOriginalImage] as! UIImage
       //get the image as nsdata to save later to disk
        let imageData = UIImageJPEGRepresentation(image, 1.0)

        //saving to disk
       let localPath = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true)
      let filePath = localPath[0] as! String
      let finalPath = filePath.stringByAppendingString("/" + "a_name_for_your_img.... ussually I usse NSUUID() if i dont have anything better" + ".jpeg")
      imageData.writeToFile(finalPath,automatically:true)
      
      //finally get the image URL
      let imageURL = NSURL(fileURLWithPath: finalPath)

      //Remove the local saved image if needed....


        OnfidoAPI.uploadDocument(curUsr["idHash"] as! String, "passport", imageURL, complete: { (document) in

            print (document)

            }) { (error) in
                print (error)
        }

    }

**Comment by francisjervis** [comment]
As I noted, this is undesirable because of the extra code required to save the file (plus security considerations with doing that). This can be avoided, however, using the following approach which accepts an in-memory UIImage (note that the specification of "application/png" in the API docs is incorrect, and only "image/png" works):


        let pngData = UIImagePNGRepresentation(cardImage)

        let url = NSURL(string:"https://api.onfido.com/v2/applicants/\(userOnfidoId)/documents")

        let headers = ["Authorization": "Token token=YOUR_ONFIDO_TOKEN"]

        let typeData = ("passport").dataUsingEncoding(NSUTF8StringEncoding)!

        upload(.POST, url!, headers: headers, multipartFormData: { (MultipartFormData) in
            MultipartFormData.appendBodyPart(data: typeData, name: "type")
            MultipartFormData.appendBodyPart(data: pngData!, name: "file", fileName: "document\(userApplicationId).png", mimeType: "image/png")


            }, encodingMemoryThreshold: Manager.MultipartFormDataEncodingMemoryThreshold,
               encodingCompletion: {encodingResult in

                print (encodingResult)

                switch encodingResult {

                case .Success(let upload, _, _):

                    upload.responseJSON { response in

                        print (response)


                    } case .Failure(let error):
                        print(error)
                }
                
            }

        )
        

        paymentViewController.dismissViewControllerAnimated(true, completion: nil)

**Comment by anuragajwani** [comment]
@francisjervis the support for OnfidoApi wrapper on the SDK has been dropped now. Are you still interested in an OnfidoApi wrapper? We might extract it into its own pod ...

**Comment by anuragajwani** [comment]
Closing issue due to a lack of response
