### ISSUE TITLE
The release binary of 5.4.0 prevents archiving & exporting.

### ISSUE THREAD

**Issue by andersio** [onfido/onfido-ios-sdk#20]
This is a 5.4.0 specific issue. 5.3.0 works for us. According to the build log:

> Error Domain=IDEFoundationErrorDomain Code=1 "Info.plist of “MyApp.app/Frameworks/Onfido.framework” specifies a simulator platform for the CFBundleSupportedPlatforms key" UserInfo={NSLocalizedDescription=Info.plist of “ MyApp.app/Frameworks/Onfido.framework” specifies a simulator platform for the CFBundleSupportedPlatforms key}

**Comment by anuragajwani** [comment]
@andersio I am guessing that the error you are seeing is with the `Onfido-Release` pod upon iTunes Connect submission, in that case the issue has been fixed. Please remove all cached frameworks of `Onfido-Release` and run `pod install` again. 

Sorry for the inconvenience,
Anurag

**Comment by anuragajwani** [comment]
@andersio are you still encountering this error?

**Comment by rfreitas** [comment]
Closing the issue due to lack of response.
