### ISSUE TITLE
Swift conflict versions - 5.3 and 5.3.1

### ISSUE THREAD

**Issue by JGanol** [onfido/onfido-ios-sdk#201]
### What was the expected behaviour?

XCode 12.2 should be able to build module Onfido.

### What happened instead?

XCode 12.2 throws an error: 
failed to build module 'Onfido' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'

### Version info:

- Cocoapods (if applicable): 1.11.0
- Onfido SDK (Debug/Release): 18.10.1
- iOS: > 11
- Xcode: 12.2
- Device/Simulator: -
- Device/Simulator language: -

### Steps to reproduce:

Onfido is added via cocoapods. The previous version of Onfido that worked was 18.3.

**Comment by Steveybrown** [comment]
See the same issue - oddly seems to just be when trying to build for tests.

**Comment by anuragajwani** [comment]
Hi @JGanol

I tested iOS SDK version `18.10.1` using Xcode 12.2 and was not able to reproduce the issue. I used the SampleApp that is provided in this repo.

```
➜  SampleApp: pod install
Analyzing dependencies
Downloading dependencies
Installing Onfido 18.10.1 (was 18.1.0)
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

![Screenshot 2020-12-09 at 16 34 57](https://user-images.githubusercontent.com/7071488/101658016-7a587b80-3a3c-11eb-9f36-b93d2baa8d15.png)

Could you try to reproduce this issue with the SampleApp please? If you don't get any issues with the SampleApp then is there something unique about the configuration of your project that might be leading to this problem?

Anurag

**Comment by JGanol** [comment]
I have a demo example to reproduce the issue. To see the problem, please install pods and run a build via fastlane (I have attached a script) from the project folder: "fastlane ios acceptance". The build fails for a simulator. But is ok for a device.

[Onfido18_10__faslane_sim.zip](https://github.com/onfido/onfido-ios-sdk/files/5673547/Onfido18_10__faslane_sim.zip)

**Comment by JGanol** [comment]
Hi @anuragajwani, are you able to reproduce on your side?

**Comment by anuragajwani** [comment]
Hi @JGanol,

I'll test it out today however if it works through Xcode then that makes me think it's a fastlane integration issue. If the problem is on how fastlane performs the xcodebuild then this might be an issue with fast lane instead.

**Comment by Nargle30** [comment]
Hi, is there any progress? Can the problem be in the Xcode configuration?

**Comment by anuragajwani** [comment]
Sorry for not replying and testing this earlier @JGanol  the project supplied has a xcworkspace missing reference to the Pods the xcproj. No Podfile has been included.

@Nargle30 I'm not sure what the problem as we do not use fast lane. However fast lane is a third party tool not supported by Apple. If it works using only Apple tools then the problem lies with the third party tool. I wish I could be of more help here but I haven't been using fast lane in many many years now.

**Comment by alexanderjarvis** [comment]
This is not a fast lane issue, can confirm I have the same issue without fastlane (onfido/react-native-sdk).

**Comment by alexanderjarvis** [comment]
I think this needs to be in the pod spec:

```
 "pod_target_xcconfig": {
    "EXCLUDED_ARCHS[sdk=iphonesimulator*]": "arm64"
  },
  "user_target_xcconfig": {
    "EXCLUDED_ARCHS[sdk=iphonesimulator*]": "arm64"
  },
```

Same as Zendesk.

The actual error is (a line above the one posted in this issue): `error: unable to load standard library for target 'arm64-apple-ios10.0'`

**Comment by Nargle30** [comment]
@alexanderjarvis, hi!
There is a separate issue for react-native as well: https://github.com/onfido/react-native-sdk/issues/21
Currently, I mostly have a monologue with myself there.. If you want to participate - welcome :) 

Hopefully someone will provide support there, since i've contacted customer service recently

**Comment by alexanderjarvis** [comment]
You can fix this in your project by adding:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
     end
   end
end
```

to your Podfile.

**Comment by anuragajwani** [comment]
thanks for sharing @alexanderjarvis 😄

**Comment by JGanol** [comment]
Hi @anuragajwani,
It took me a while to come back to this issue.

Fix, proposed by alexanderjarvis, doesn't work.

Also, I checked it without fastlane, running a command:
_xcodebuild -scheme "DemoFrm" -derivedDataPath build -sdk iphonesimulator clean build -configuration Release -destination='iOS Simulator' -workspace "DemoFrm.xcworkspace"_
The issue is still present, this is not a fastlane problem.

I am attaching an archive with a podfile. Hope it will help.

[Onfido_fastlane_2021_02_10.zip](https://github.com/onfido/onfido-ios-sdk/files/5959081/Onfido_fastlane_2021_02_10.zip)

Kind regards,
Julia

**Comment by anuragajwani** [comment]
thanks @JGanol I can now reproduce this. I can confirm this only happens with the Release config at this point. I am investigating this now.

**Comment by anuragajwani** [comment]
@JGanol the problem does not occur when using the Release configuration for devices though. I suspect Xcode configures Release config only for devices.

**Comment by anuragajwani** [comment]
@JGanol found the problem and the solution. But default it seems that Xcode only support devices architectures on the default Release config. This building for simulator fails as Xcode does not extract the binaries and interfaces for the simulator from the framework.

The solution is to add the simulators as support architecture for the Release config. I have added x86_64 architecture support which is simulators running on intel based Macs. See screenshot:
![Screenshot 2021-02-10 at 17 15 43](https://user-images.githubusercontent.com/7071488/107545820-9d7de380-6bc3-11eb-839d-b95746145a26.png)

I was able to build no problem through Xcode however your xcodebuild command needs to add another parameter to specify the architecture too. By default it seems to be building the DemoFrm framework for i386 too. See screenshot.
![Screenshot 2021-02-10 at 17 14 41](https://user-images.githubusercontent.com/7071488/107545682-77f0da00-6bc3-11eb-91f6-6322fb1f1f38.png).

This fix here is to specify building only x86_64 architecture:
```bash
xcodebuild -scheme "DemoFrm" -derivedDataPath build -sdk iphonesimulator -arch x86_64 clean build -configuration Release -destination='iOS Simulator' -workspace "DemoFrm.xcworkspace
```
See success build screenshot:
![Screenshot 2021-02-10 at 17 16 28](https://user-images.githubusercontent.com/7071488/107545904-b71f2b00-6bc3-11eb-9b8f-866fdb33d927.png)

I have attached the DemoFrm project with the fix.

[Onfido_fastlane_2021_02_10_FIX.zip](https://github.com/onfido/onfido-ios-sdk/files/5960064/Onfido_fastlane_2021_02_10_FIX.zip)

Let me know if this answers/fixes your problem.

Thanks,
Anurag

**Comment by JGanol** [comment]
Hi @anuragajwani,
Thank you very much for your quick response and help. It finally works! The issue can be closed.
Kind regards,
Julia

**Comment by anuragajwani** [comment]
that's great news @JGanol 🎉 I am glad I was able to help solve your problem 🙂

**Comment by mtimofiiv** [comment]
@anuragajwani is there any way around this issue besides modifying the `xcodebuild` command? We're using [Expo's EAS](https://expo.io/eas) and all of a sudden, builds are broken. I don't believe we can customise the command fastlane runs on EAS's servers.

**Comment by anuragajwani** [comment]
what do you mean "all of a sudden"? something must have changed either on the project config or on Expo's EAS side. I am unfamiliar with this service and building for simulators using Release config is not standard practise.

As I am not too fluent with Fastlane and unfamiliar with Expo EAS here is my jab at solving the problem:
- Expo EAS uses Fastlane gym
- The command options is configurable if a file named `Gymfile` is included
- Gymfile options are customisable with these [parameters](https://docs.fastlane.tools/actions/gym/#parameters)
- Gymfile does not include archs parameter however it does include xcconfig param
- An xcconfig file can include the archs config for a specific profile. You can find some guides on the variables you can set on xcconfig [here](https://pewpewthespells.com/blog/buildsettings.html).

So:

1. create an xcconfig file
2. specify x86_64 as well as the standard archs for release config
3. create or modify gym file to include xcconfig param

I hope this helps. As this sits outside standard iOS and with third party tools I am unable to be of more help than just reading documentation.

**Comment by mtimofiiv** [comment]
> what do you mean "all of a sudden"?

Builds were working as of last week. Either EAS changed something or something changed in this module.

> I hope this helps. As this sits outside standard iOS and with third party tools I am unable to be of more help than just reading documentation.

Thanks so much! I'll give this a try.

**Comment by anuragajwani** [comment]
if you haven't upgraded the module version then nothing has changed. However if you have upgraded the module version well that is the change.

If you have changed the module version then which was the previous version and what's the new version?
