### ISSUE TITLE
NFC Feature is causing app rejection in app store

### ISSUE THREAD

**Issue by mdesjardins** [onfido/onfido-ios-sdk#204]
### What was the expected behaviour?

After upgrading Onfido, we would be accepted by the Apple App Store as out app always has. We have no intention of using the NFC feature. Worse, our app is translated to Italian, so we can't go back to a version before 18.7, because all of the localization keys changed in version 18.6. This is a very very big problem for us as we are already in code freeze for the holiday season.

### What happened instead?

<img width="699" alt="image" src="https://user-images.githubusercontent.com/19634/101985087-b1ed4080-3c53-11eb-98c1-60091fc7e2a8.png">

### Version info:

- Cocoapods (if applicable): 1.10.0
- Onfido SDK (Debug/Release): 18.9
- iOS: All
- Xcode: 11

### Integration configuration:

Please disregard the comment about the other Onfido issue we are having w/r/t Italian translations, it is unrelated to this problem.

```
                                    :(NSString*) sdkToken {
    // Create the configuration object that directs the onfido flow
    ONFlowConfigBuilder *configBuilder = [ONFlowConfig builder];
    // these two fields are required to upload documents
    [configBuilder withToken:sdkToken];
    [configBuilder withApplicantId: applicantId];
    [configBuilder withWelcomeStep];
    // this tells the onfido sdk want the user to include the document upload step
    [configBuilder withDocumentStep];
    
    // we provide Italian translations, which aren't available out-of-the-box. This tells Onfido
    // that it needs to look for them. Note that if you call this function for every language, then
    // Onfido tries to find custom strings for *all* languages that you support, and it will fail
    // (intermittently, making it even more fun) and use "missing" strings. This is why we only
    // invoke this if the language is Italian, which isn't ideal, but works for now. Going to open
    // an issue w/ Onfido, because I doubt that this is how it's supposed to work.
    NSString* language = [[NSLocale preferredLanguages] objectAtIndex:0];
    if ([language hasPrefix:@"it"]) {
      [configBuilder withCustomLocalization];
    }
    
    ONAppearance *appearance = [[ONAppearance alloc]
                                initWithPrimaryColor:[UIColor onfidoPrimaryColor]
                                primaryTitleColor:[UIColor onfidoPrimaryTitleColor]
                                primaryBackgroundPressedColor:[UIColor onfidoPrimaryBackgroundPressedColor]
                                secondaryBackgroundPressedColor:[UIColor onfidoSecondaryBackgroundPressedColor]
                                fontRegular:[UIFont onfidoFontName]
                                fontBold:[UIFont onfidoFontName]
                                supportDarkMode:FALSE];
    
    [configBuilder withAppearance:appearance];
    
    NSError *configError = NULL;
    ONFlowConfig *config = [configBuilder buildAndReturnError:&configError];
    if (configError != NULL) {
        return nil;
    }
    return config;
```

### Steps to reproduce:

Submit an app to the app store with Onfido 18.7+

**Comment by kushal-onfido** [comment]
Hi @mdesjardins 

Could you please follow the suggestions provided in [this issue](https://github.com/onfido/onfido-ios-sdk/issues/195) and it should solve the issue for you? Please write back to us if you still see any issue.

Thank you.

**Comment by keremgund** [comment]
Closing the issue due to lack of response.
Please open new one if you need further assistance.

Thanks,
Kerem
