### ISSUE TITLE
OnfidoConfig.build() function raises an error when applicant ID and SDK token are provided in version 16.1.0

### ISSUE THREAD

**Issue by Iyuna** [onfido/onfido-ios-sdk#205]
### What was the expected behaviour?

We didn't receive this kind of error when we released in May with Onfido SDK version 16.1.0. Since then we haven't updated SDK version in production. We expect our users to be able to verify their government IDs. However, they receive an error now.

### What happened instead?

Users are not able to verify their IDs now as SDK returns an error OnfidoConfigError.applicantProvidedWithSDKToken. This error seems to be ok for the recent SDK version. Although, we're using an old one and expect Onfido to be backward compatible. 

### Version info:

- Cocoapods (if applicable): 1.9.3
- Onfido SDK (Debug/Release): 16.1.0
- iOS: 14.2
- Xcode: 12.2
- Device/Simulator: iPhone 11
- Device/Simulator language: Russian 

### Integration configuration:
```
let applicant = Applicant.new(
        firstName: firstName,
        lastName:  lastName,
        email: user.email ?? "",
        dateOfBirth: user.birthday,
        country: user.address?.country,
        idNumbers: [],
        addresses: []
)
let shouldUseLiveness = user.settings?.onfidoLiveness ?? false
let variant: Onfido.FaceStepVariant = shouldUseLiveness ? .video(withConfiguration: nil) : .photo(withConfiguration: nil)

do {
        let config = try OnfidoConfig.builder()
        .withSDKToken(Environment.shared.onFidoApiKey)
        .withApplicant(applicant)
        .withDocumentStep()
        .withFaceStep(ofVariant: variant)
        .build()

        onfidoFlow = OnfidoFlow(withConfiguration: config).with(responseHandler: { [weak self] response in
                ...
        }  
} catch {
        reportNonFatalError(error)
        showError(error.localizedDescription)
        // error is raised here
        return
}
```

### Steps to reproduce:

Open Onfido flow

**Comment by keremgund** [comment]
Hi @Iyuna ,
We have mentioned this in our [documentation](https://github.com/onfido/onfido-ios-sdk/tree/16.1.0#3-configuring-sdk-with-tokens)

As SDK token itself already binds to applicant, SDK token and applicant configurations are mutually exclusive. You can either configure SDK with mobile token + applicant (id or object) or just SDK token (without any applicant related config).

Thanks,
Kerem

**Comment by Iyuna** [comment]
Hi @keremgund,
Thank you for the quick response.
Yes, your documentation is quite understandable. However, it relates to the latest library version. We're using not the latest version. Our SDK token is still a fixed string value provided in plist file as it used to be before. The point is that everything used to work ok when we released the application. Now the app is crashing when Onfido flow starts and we're not able to release a new app version quickly with the latest Onfido SDK. However, we still need our users to be able to verify their identity. 
Is it possible to implement this kind of backward compatibility on your side?

**Comment by keremgund** [comment]
Hi @Iyuna ,
The documentation link I've shared belongs to 16.1.0 version, not the latest one. In terms of backward compatibility, SDK token feature has been introduced with supporting backward compatibility already. So I've a hunch that at some point you changed your integration from mobile token to SDK token by keeping applicant configuration call. If you want to keep applicant configuration on the client side then I suggest you to change 
`        .withSDKToken(Environment.shared.onFidoApiKey)
`call to
`        .withToken(Environment.shared.onFidoApiKey)
`
Please note that withToken() function is deprecated so for the long-term solution I advise you to use SDK token.
 
Thanks,
Kerem

**Comment by Iyuna** [comment]
Hi @keremgund,

Everything you said makes total sense to me. I think we should change `withSDKToken` function call to `withToken` as you suggested until we implement full SDK token support. However, my concern is that it used to work when we released the app. Now it stopped working without us implementing any changes. Not only didn't we receive `applicantProvidedWithSDKToken` error in our release candidate so that we can fix this issue before the release, but also Onfido worked just fine in our production app. Now we have to update the app so that Onfido works again which we can't do in the nearest future.

Please, let me know if we can do something on our side to make Onfido work again without releasing a new app version.

Best,
Iryna

**Comment by keremgund** [comment]
Hi @Iyuna 
I just checked our release history and found out that as part of the 13.0.0 version we've released the SDK token feature and also introduced a new configuration error called `applicantProvidedWithSDKToken `. Please see the [documentation for 13.0.0](https://github.com/onfido/onfido-ios-sdk/tree/13.0.0#configuration-errors)
So there shouldn't be any time that you have the ability to configure SDK with calling withSDKToken function along with `withApplicant()` and get no run time error.

Thanks,
Kerem

**Comment by Iyuna** [comment]
Hi @keremgund 
Yes, this sounds fair. But obviously there was such time as we always pass the full regression test before the release and it worked just fine. Nevertheless, we can prove nothing now as it's not working now. 

Thanks for your time for the investigations!
