### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by shaps80** [onfido/onfido-ios-sdk#207]
It would be great if an XCFramework could be built so we can use this on Apple Silicon. At the moment out of 15 libraries, this is the only one that's stopping me from running on my new Mac ;)

### What was the expected behaviour?

A framework that will work on Apple Silicon

### What happened instead?

The framework cannot be used when developing on a Apple Silicon

### Version info:

- Carthage
- Onfido SDK 9.0.0
- iOS 14
- Xcode 12

### Integration configuration:

Nothing special.

### Steps to reproduce:

Add Carthage via the pre-compiled binary or Carthage.
Add the framework to Xcode and Embed and Sign
Build the project

The result is obviously that the framework wasn't built for this Mac.

**Comment by keremgund** [comment]
Hi @shaps80, 
XCframework support will be added as part of SPM feature, which we have an open issue for that: https://github.com/onfido/onfido-ios-sdk/issues/182

Would that be possible for you to track the progress within that ticket?

Thanks,
Kerem
