### ISSUE TITLE
Document upload fails when app goes to background

### ISSUE THREAD

**Issue by akshitzaveri** [onfido/onfido-ios-sdk#209]
### What was the expected behaviour?

The document should have been uploaded successfully

### What happened instead?

The document upload failed

```
Optional(Onfido.OnfidoFlowError.exception(withError: Optional(Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={_kCFStreamErrorCodeKey=53, NSUnderlyingError=0x280249b00 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x282f95400 [0x1ecce0660]>{length = 16, capacity = 16, bytes = 0x100201bb6350cf2e0000000000000000}, _kCFStreamErrorCodeKey=53, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <A9E38BBD-8FBC-4544-8C7C-912D02C1DAE9>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <A9E38BBD-8FBC-4544-8C7C-912D02C1DAE9>.<1>"
), NSLocalizedDescription=The network connection was lost., NSErrorFailingURLStringKey=https://api.onfido.com/v3/documents, NSErrorFailingURLKey=https://api.onfido.com/v3/documents, _kCFStreamErrorDomainKey=1}), withMessage: nil))
```

### Version info:

- Cocoapods (if applicable): 19.0.0
- Onfido SDK (Debug/Release): Release
- iOS: 14.3
- Xcode: 12.3
- Device/Simulator: Device
- Device/Simulator language: English

### Integration configuration:

```
let config = try OnfidoConfig.builder()
    .withSDKToken(response.sdkToken)
    .withWelcomeStep()
    .withDocumentStep(ofType: .nationalIdentityCard(config: .init(country: Nationality.india.symbol)))
    .build()

let onfidoFlow = OnfidoFlow(withConfiguration: config)
    .with(responseHandler: responseHandler)

let controller = try onfidoFlow.run()
controller.present(controller, animated: true, completion: nil)
```

### Steps to reproduce:

Capture the document and as soon as it begins to upload, put the app to background. Open the app after 5 seconds and the app shows document upload failed error.

**Comment by anuragajwani** [comment]
Hi @akshitzaveri 

I have tried our SDK multiple times backgrounding right after commencing the upload (I also used Network Link Conditioner to make the upload slower). In all my attempts the SDK resumes upload without any errors.

Could you please share a video showing the problem please?

**Comment by akshitzaveri** [comment]
@anuragajwani Unfortunately I can't share the video of the app due to compliance reasons. I will find an alternate way soon.

**Comment by keremgund** [comment]
Closing the issue due to lack of response. Please open new one with providing video recording or any other possible way you mentioned to help us understand the issue better.

Thanks,
Kerem
