### ISSUE TITLE
Upload Document Error : 

### ISSUE THREAD

**Issue by asifiosdeveloper** [onfido/onfido-ios-sdk#210]
### What was the expected behaviour?
Success response after uploading document
Please detail what the expected behaviour was
Uploaded a nationalID of United Arab Emirates with sdkToken :

```
let config = try! OnfidoConfig.builder()
            .withSDKToken(token)
            .withAppearance(appearance)
            .withDocumentStep()
            .withFaceStep(ofVariant: .photo(withConfiguration: nil))
            .build()
        
        let onfidoFlow = OnfidoFlow(withConfiguration: config)
            .with(responseHandler: responseHandler)
        
        do {
            let onfidoRun = try onfidoFlow.run()
            
            onfidoRun.modalPresentationStyle = modalPresentationStyle
            self.present(onfidoRun, animated: true, completion: nil)
        } catch let error {
            // cannot execute the flow
            print("Error")
        }
```
### What happened instead?

Got the onfidoAPI Error : 

```
upload(OnfidoApiError {
    id = NULL,
    type = bad_referrer,
    message = Unexpected referrer: , please check the referrer used to generate the token,
    fields = {}
})
```

Please detail what was the actual behaviour

After uploading document the ViewController dismissed and got the error response. 
sdkToken generated successfully from the backend side.
Tried on both simulator and device
### Version info:

- Cocoapods (if applicable): 18.3.1
- Onfido SDK (Debug/Release): Debug
- iOS: 14.3
- Xcode:12.3
- Device/Simulator: Tried on Both
- Device/Simulator language: English

**Comment by kushal-onfido** [comment]
Hi @asifiosdeveloper 
`401 bad_referrer` Error points to invalid referrer used to [generate the SDK token](https://documentation.onfido.com/#generate-sdk-token). You may refer to Error codes [here](https://documentation.onfido.com/#errors). Could you please review the Referrer argument as mentioned [here](https://documentation.onfido.com/#the-referrer-argument)? 

In case the issue persists, please share the applicant ID and your registered email ID with us by sending an email at api@onfido.com and we'll look into this further.

**Comment by asifiosdeveloper** [comment]
The client app info was missing from the backend side while creating sdkToken which caused issue. it is updated and working fine now. Thank you so much.
