### ISSUE TITLE
App store rejection because of NFC feature.

### ISSUE THREAD

**Issue by Keuha** [onfido/onfido-ios-sdk#215]
### What was the expected behaviour?

We tried to submit a new app to the store using Onfido SDK `18.8.0` Should have been approuve or at least Onfido should not cause issues.

Not using NFC feature should not cause a rejection.

### What happened instead?

The app has been rejected for NFC usage without calling `.withPassportNFCReadBetaFeatureEnabled()` during the Onfido configuration.

I tried to upload the video kindly provided in this comment https://github.com/onfido/onfido-ios-sdk/issues/195#issuecomment-722347875

But once again been reject with the following answer 

<img width="878" alt="Capture d’écran 2021-01-26 à 08 58 39" src="https://user-images.githubusercontent.com/3855308/105816512-b166fa00-5fb4-11eb-8da9-33c4dea6b3a2.png">

I tried to activate the NFC feature by calling `.withPassportNFCReadBetaFeatureEnabled()`  (see integration configuration)

But I've been unable to trigger the feature in order to provide a video to the review team. 

Is there any way to unactivate the NFC feature ? or to programatically trigger the NFC reader for video purpose ? 

thanks ! 

### Version info:

- Cocoapods (if applicable): 1.10.0
- Onfido SDK (Debug/Release): 18.8.0
- iOS: 14.3
- Xcode: 12.3
- Device: iphone 12 mini
- Device language: French

### Integration configuration:

Current integration

```
 try? OnfidoConfig.builder()
                .withSDKToken(token, expireHandler: {
                   [...]
                })
                .withAppearance(self.onfidoAppearance())
                .withFaceStep(ofVariant: .photo(withConfiguration: nil))
                .withDocumentStep()
                .build()
```

### Steps to reproduce:

Submit a new app on the store using onfido 18.8.0

EDIT : 

As a temporare fix, we decided to roll back to 17.0.0 since it seems to have no NFC feature

**Comment by andra-radu** [comment]
Hello @Keuha,

NFC reading process is off by default. If you would like to turn it on, please follow the steps provided here:
https://github.com/onfido/onfido-ios-sdk/#enabling-epassport-nfc-extraction-beta
If you have any questions or concerns please let us know.

**Comment by Keuha** [comment]
Hi @andra-radu I might have miss explain my problem.

the thing is I do not use NFC at all, however Apple Review teams ask me to provide a video about why and how do I use NFC in my app. So i tried to activate it to show the usage but fail, ok that's a thing. 

But my goal here is to be able to submit my app with NFC off and still being accepted by Apple Review teams

**Comment by keremgund** [comment]
Hi @Keuha 
This is similar problem mentioned here: https://github.com/onfido/onfido-ios-sdk/issues/195
You can use the same video shared in [this](https://github.com/onfido/onfido-ios-sdk/issues/195#issuecomment-722347875) comment and pass the review process.

In the mean time we're working on better solution for these kind of problems.
Kerem

**Comment by keremgund** [comment]
Sorry just noticed your statement in first message now. The video recording is already belong to real device, not simulator. Could you ask them whether they need not the screen recording but the recording of the iphone with different device so they can clearly see the device itself ?

**Comment by Keuha** [comment]
Hi @keremgund 
According to the full message I received, It seems they want to see a record of the device performing a scan and not only the screen capture. so basically the full process of scanning a passport NFC with a device.

**Comment by keremgund** [comment]
Ok, thanks for confirming. We're working on preparing necessary video. 
I will back to you shortly.

Sorry for the inconvenience,
Kerem

**Comment by Keuha** [comment]
@keremgund amazing.
Thank you all for the effort you're putting in support !

**Comment by keremgund** [comment]
Hi @Keuha 
Could you please download this video and share with Apple. Please let us know whether they accepted or not.

https://user-images.githubusercontent.com/49163858/105852992-16364a80-5fdd-11eb-96d0-0f73f8949552.mov

**Comment by Keuha** [comment]
Hi ! Just to let you know that I won't be able to submit a new build for the next 10 days. 
I guess you can close the PR for now and I'll re open it to let you know the result.

**Comment by neelmit** [comment]
@Keuha were you able to successfully get your App approved by Apple without including the NFC tag scan feature? We're facing the same issue and we DO NOT want to enable NFC, so wondering what next steps to take here. Appreciate your input. Thanks!

**Comment by finchmoney** [comment]
@Keuha  were you able to successfully get your App approved by Apple without including the NFC tag scan feature? We're facing the same issue and we DO NOT want to enable NFC, so wondering what next steps to take here. Appreciate your input. Thanks!

**Comment by finchmoney** [comment]
@keremgund same question to you as the @Keuha, can you advice here on what to do next? Thanks!

**Comment by shaps80** [comment]
@finchmoney in case its helpful to know. I was equally concerned so I used the video that was originally posted on #195.

I added a comment to Apple during the submission and passed through approval without any query or rejection at all 👍

I've seen similar reports from others that the video was enough to get through the approval. We've since gone through several approvals without issue.

**Comment by finchmoney** [comment]
@shaps80 likewise! We also did a combination of providing that NFC video from [#195](https://github.com/onfido/onfido-ios-sdk/issues/195), giving a comment that we don't use Onfido optional NFC feature, and also provided a video demo of our app. That worked for us. 

Thanks!

**Comment by keremgund** [comment]
Hey all,
We will be updating README.MD to mention about potential app rejection by Apple because of NFC and share the link of the video above. Hence, I'm closing this issue for now as it seems everybody managed to pass app review process with the video recording.

**Comment by mszaro** [comment]
We were rejected today despite including the passport verification video suggested at https://github.com/onfido/onfido-ios-sdk/issues/215#issuecomment-767553245, because Apple wants to see usage of the NFC functionality specifically within our application, and the OnFido clip of course doesn't show our particular application.

**Comment by heeween** [comment]
is it because we check the 'NFC Tag Reading' service in AppId configuration?
I met the same problem. I will try to unselected the 'NFC Tag Reading' checkbox. And I will see if I can pass through the approval.
