### ISSUE TITLE
User is unable to take a selfie

### ISSUE THREAD

**Issue by shaps80** [onfido/onfido-ios-sdk#227]
### What was the expected behaviour?

The user should be able to take a selfie while keeping their head still inside of the Oval

### What happened instead?

The user's face is clear and inside of the Oval, but the button remains permanently disabled, preventing the user from continuing.

### Steps to reproduce:

I haven't been able to personally reproduce however I did note that out of the user's (so far) that have reported this issue, they were all using an iPhone XR running iOS 14.4. I wonder if this could be device specific. Since I don't have that device I don't have a way to test this atm. Any support would be appreciated.

----

EDIT:
Scratch that idea, another report now but the customer was using an iPhone 11 ¯\_(ツ)_/¯

**Comment by andra-radu** [comment]
Hi @shaps80,

Could you please share with us the following information to be able to further investigate?

Version info:
* Cocoapods (if applicable):
* Onfido SDK (Debug/Release):
* iOS:
* Xcode:
* Device/Simulator language:

Integration configuration:
Please add code snippet(s) of your integration with the Onfido SDK and all customizations of it.

**Comment by shaps80** [comment]
We currently include the framework manually until your M1 support for SPM is completed. @anuragajwani is working on this on another Issue 👍 

As for the configuration, we are using the following:

```swift
Onfido.OnfidoConfig.builder()
                .withSDKToken(sdkToken)
                .withWelcomeStep()
                .withFaceStep(ofVariant: .photo(withConfiguration: nil))

OnfidoFlow(withConfiguration: config)
                .with(responseHandler: { ... })
```
```

**Comment by keremgund** [comment]
Hi @shaps80 ,
The logic is to disable the button till camera device is in "ready" state. So in this case it seems somehow user's camera doesn't return ready to state to proceed with capture. Could you ask them to try different application which requires to use the camera and tell whether it works or not ?

Thanks,
Kerem

**Comment by shaps80** [comment]
Interesting, ok I'll follow up and find out thanks.

**Comment by shaps80** [comment]
@keremgund sorry for extremely late reply, but we've encountered this issue again and the user was successfully able to use their camera in other apps. The button in the Onfido view just never appears.

**Comment by egarni** [comment]
Hello,

We're also getting a lot of reports from users regarding this bug. here are reports from users we got recently:

> It won’t allow me to upload my passport or drivers license and when it gets to Take Selfie (under driver licence option) it won’t move beyond that screen.
> I am using an iPhone X.

> Camera screen for taking selfie (camera is on and working) but when he clicks the button to take it, the buttons greys out and he is unable to proceed.

> I am trying to take a selfie with OnFido, but the button to take the picture seems to be broken. I click on the button (I see it enabled) and then it gets greyed out and the picture is not taken and I can’t press again. Any ideas what’s going on? I tried twice already, using different method (passport, ID card).

I was not able to reproduce it myself but the reports keep coming.

**Comment by Styren** [comment]
We are also receiving reports about users facing the same issue.

**Comment by shaps80** [comment]
Yeah I concur with everything above. Same issues across multiple users, definitely feels like a bug to me @keremgund.

**Comment by shaps80** [comment]
@keremgund / @anuragajwani – just an FYI, we since we've had a tonne of users _recently_ with this issue I've asked our support to track iOS versions and it seems a lot of users have reported issues in iOS 14.5 specifically (might be others as well though). Asking the same users to upgrade to iOS 14.6 seemed to 'resolve' the issue?

Not sure if this was just a red herring, but thought I'd share on the off chance you can reproduce, I don't personally have a setup to test this myself sorry.

@Styren / @egarni in case this helps you as well 👆but again, could have just been a coincidence ¯\_(ツ)_/¯

**Comment by anuragajwani** [comment]
Hi @shaps80 @Styren ,

Sorry for the delayed response. Are you still seeing this issue? Does 14.6 seem to resolve the issue?

**Comment by shaps80** [comment]
It hasn't come up again recently, so potentially its resolved. Gotta admit I don't like guessing in these situations but I have nothing else to go on right now 👍 Feel free to close this issue if you want @anuragajwani
