### ISSUE TITLE
Error when installing v21.1.0 via Swift Package Manager

### ISSUE THREAD

**Issue by harryblam** [onfido/onfido-ios-sdk#229]
### What was the expected behaviour?
I'm trying to install version 21.1.0 via Swift Package Manager. When pulling it down into my project via my Package.swift file, i'm seeing a 301 failed to download build error. 

As a side note: I have seen that the binary download link in the Onfido Package.swift changed in version 20.1.0. When I update my file to reference this version, the error no longer appears. I'm currently therefore able to use this as a workaround. 

Please see below steps to reproduce. 

### What happened instead?
Ran into a 301 error when SPM goes to download the binary. 

### Version info:

- Cocoapods (if applicable): Nope, using swift package manager
- Onfido SDK (Debug/Release): 21.1.0
- iOS: 14.1
- Xcode: 12.4 (12D4e)
- Device/Simulator: Simulator
- Device/Simulator language: en

### Integration configuration:
Not really applicable my project is failing to build the dependency. 

### Steps to reproduce:
1. Include the Onfido 21.1.0 dep in my Package.swift file (see below code snippet)
`.package(name: "Onfido", url: "https://github.com/onfido/onfido-ios-sdk.git", from: "21.1.0")`
2. Resolve package dependencies from Xcode
3. Observe error appear when downloading the binary (see below screenshot)
![Screenshot 2021-03-30 at 15 51 22](https://user-images.githubusercontent.com/2333536/113003630-33b99900-9173-11eb-9a2a-75b4ff3575ef.png)
4. Update the version number in my Package.swift file to reference the older 20.1.0 release
`.package(name: "Onfido", url: "https://github.com/onfido/onfido-ios-sdk.git", from: "20.1.0")`
5. Resolve package dependencies from Xcode
6. See project is building and the error from #3 no longer appears

**Comment by anuragajwani** [comment]
@harryblam 

I can reproduce the issue. We'll fix it asap.

Sorry for the inconveniences caused,
Anurag

**Comment by anuragajwani** [comment]
@harryblam 

We have fixed the url link for iOS SDK version [21.3.0](https://github.com/onfido/onfido-ios-sdk/blob/master/CHANGELOG.md#2130---2021-04-06).

Please let us know if you have any further issues or If it is fixed so we can close the issue.

Thanks in advance 😄

**Comment by harryblam** [comment]
Just tested, all looks good to me @anuragajwani - I can build v21.3.0 from my Package.swift file 👍 

Thanks for quick turnaround on this!

**Comment by anuragajwani** [comment]
that is greats news 😄 thanks @harryblam 

Sorry for the inconveniences caused.
