### ISSUE TITLE
How to fetch OnfidoResult from OnfidoResponse

### ISSUE THREAD

**Issue by rahulshah007** [onfido/onfido-ios-sdk#23]
swift 3.2 ,xcode 9
i need  to pass this value Onfido.DocumentResult, Onfido.ApplicantResult),Onfido.FaceResult in api parameters
 /* -d 'reports[][name]=document' \
         -d 'reports[][name]=facial_similarity' \
         -d 'reports[][variant]=standard'*/

for check call
 String.init(format: "https://api.onfido.com/v2/applicants/%@/checks", applicantId)

please tell me how to fetch OnfidoResult details from OnfidoResponse

**Comment by anuragajwani** [comment]
Hi @rahulshah007, I don't quite follow what exactly are you trying to extract from the upload results. Is is the applicantId? 

We have a small snippet on how to extract from results array which is the payload of `OnfidoResponse.success([OnfidoResult])` [here](https://github.com/onfido/onfido-ios-sdk#capture-result-payload)

I could further help if I could understand what exactly are you trying to extract 🙂

Anurag

**Comment by rahulshah007** [comment]
Hello sir,

**step 1**. I have fetched "OnfidoResponse" from "OnfidoFlow(withConfiguration: config)
            .with(responseHandler: responseHandler)" .

**step 2**. Now i want to implement( 

 https://api.onfido.com/v2/applicants/cb779561-dae0-48cd-89a5-22ed1ebbd13f/checks

)for that , I have required 

/* -d 'reports[][name]=document' \
         -d 'reports[][name]=facial_similarity' \
         -d 'reports[][variant]=standard'*/
these three parameter 

**step 3**: now question is how to fetch these three value from  OnfidoResponse->OnfidoResult ??
**step 4**. Please provide code in  swift 3.2 

i know below code  is something related but i want the same parsing details in swift 3.2

ex:-let applicant: Optional<OnfidoResult> = results.filter({ result in
  if case OnfidoResult.applicant = result { return true }
  return false
}).f

OnfidoResponse.success([OnfidoResult]) please provide proper code for swift 3.2  

Received Response:- success([Onfido.OnfidoResult.document(Document { 
	 id=100a66b8-aab4-4686-8124-14b460b3e29e 
	 href=/v2/applicants/752ff581-e2b1-4e98-9f00-9af85b057740/documents/100a66b8-aab4-4686-8124-14b460b3e29e 
	 created_at=nil 
	 file_name=onfido-document-1522146163.40457.jpg 
	 file_type=jpg 
	 file_size=952731 
	 type=driving_licence 
	 side=front 
}), Onfido.OnfidoResult.document(Document { 
	 id=d30eba3c-f55d-43f6-b3e3-89871b97e9e7 
	 href=/v2/applicants/752ff581-e2b1-4e98-9f00-9af85b057740/documents/d30eba3c-f55d-43f6-b3e3-89871b97e9e7 
	 created_at=nil 
	 file_name=onfido-document-1522146176.75898.jpg 
	 file_type=jpg 
	 file_size=973878 
	 type=driving_licence 
	 side=back 
}), Onfido.OnfidoResult.face(FaceResult { 
	id=Optional("4077b5b7-ea99-4d5f-9f2e-e0394311a95d") 
	href=Optional("/v2/live_photos/4077b5b7-ea99-4d5f-9f2e-e0394311a95d") 
	created_at=nil 
	file_name=Optional("onfido-face-1522146188.91397.jpg") 
	file_type=Optional("image/jpeg") 
	file_size=Optional(384784) 
})])

**Comment by rahulshah007** [comment]
Hello sir,

step 1. I have fetched "OnfidoResponse" from "OnfidoFlow(withConfiguration: config)
.with(responseHandler: responseHandler)" .

step 2. Now i want to implement(

https://api.onfido.com/v2/applicants/cb779561-dae0-48cd-89a5-22ed1ebbd13f/checks

)for that , I have required

/* -d 'reports[][name]=document' 
-d 'reports[][name]=facial_similarity' 
-d 'reports[][variant]=standard'*/
these three parameter

step 3: now question is how to fetch these three value from OnfidoResponse->OnfidoResult ??
step 4. Please provide code in swift 3.2

i know below code is something related but i want the same parsing details in swift 3.2

ex:-let applicant: Optional = results.filter({ result in
if case OnfidoResult.applicant = result { return true }
return false
}).f

OnfidoResponse.success([OnfidoResult]) please provide proper code for swift 3.2

Every time i got syntax error "OnfidoResponse' has no member Results" Hope now you will understand what i want to say.

**Comment by rahulshah007** [comment]
Hello sir,
please reply

**Comment by anuragajwani** [comment]
```
-d 'reports[][name]=document'
-d 'reports[][name]=facial_similarity'
-d 'reports[][variant]=standard'
```

The `document`, `facial_similarity` and face similarity variants are not specified based on the result of the flow but rather the report that you wish to generate.

**Comment by rahulshah007** [comment]
Hello sir,
Can you please  tell me how to make "check" call in swift ?

**Comment by rfreitas** [comment]
We recommend doing that call on your backend. Essentially passing to your backend only the essential, which is the applicant id and letting the backend initiate the check.

**Comment by rahulshah007** [comment]
Hello sir

params:-
 ["first_name": "Tejal", "last_name": "iOSUser"]
Headers :- 
["Accept": "application/json", "Authorization": "Token 
token=test_DKghji7nXWMqvdiGwDotCJWPxN7O979H"]
url:-
https://api.onfido.com/v2/applicants/65c0958c-369d-4a2b-b681-6934f1dc6273/checks
Response:-
SUCCESS: {
    error =     {
        fields =         {
            base =             (
                "Specify report or a package ids, not both."
            );
            "check_type" =             (
                "can't be blank"
            );
        };
        message = "There was a validation error on this request";
        type = "validation_error";
    };
}

**Comment by rahulshah007** [comment]
["type": "express", "first_name": "Tejal", "last_name": "iOSUser"]
["Accept": "application/json", "Authorization": "Token token=test_DKghji7nXWMqvdiGwDotCJWPxN7O979H"]
https://api.onfido.com/v2/applicants/3127a54c-2278-423c-aafa-84e8ddc327ae/checks
SUCCESS: {
    error =     {
        fields =         {
            base =             (
                "Specify report or a package ids, not both."
            );
        };
        message = "There was a validation error on this request";
        type = "validation_error";
    };
}

**Comment by rahulshah007** [comment]
Can you please check my above call and please provide me proper solution?

**Comment by alanjc7** [comment]
At this stage, you are [creating the check](https://documentation.onfido.com/#create-check).
You need to specify both the check type and an array of the reports you would like to be included in the check. You should not pass `first_name` and `last_name` to this endpoint (the applicant already exists).

Example body:
```
'type=express' \
'reports[][name]=document' \
'reports[][name]=facial_similarity' \
'reports[][variant]=standard' \
```

**Comment by rahulshah007** [comment]
yah for that reason i asked question in first comment  how to fetch OnFidoResult class from OnFidoResponse
because document and facial_similarity object available in  OnFidoResult class.
now question is "i am unable to fetch that object  of OnFidoResult from OnFidoResponse.
so how can i get document object. because it is required in params.

'type=express' \
'reports[][name]=document' \
'reports[][name]=facial_similarity' \
'reports[][variant]=standard' \

**Comment by alanjc7** [comment]
'document' and 'facial_similarity' are the names of the reports (strings) - not the document and live_photo objects you have created using the SDK

**Comment by rahulshah007** [comment]
Hello ,
Still getting below error
error =     {
        fields =         {
            base =             (
                "Specify report or a package ids, not both."
            );
        };
        message = "There was a validation error on this request";
        type = "validation_error";

in Android you had given "ONFidoApi " for check driving licence check call.
Can you tell me in ios how to make call for checkdriving licence ?

**Comment by rahulshah007** [comment]
let applicant: Parameters = [
          
            "type":"express",
           "reports[][name]" : "facial_similarity",
        ]
        let headers: HTTPHeaders = [
            "Authorization": "Token token=\(self.api_Token)",
            "Accept": "application/json"
        ]
        
        
        print(applicant)
        print(headers)
        
        // please adjust your schedule accordingly
        let strUrl =  String.init(format: "https://api.onfido.com/v2/applicants/%@/checks", applicationId)
        print(strUrl)
    
        Alamofire.request(
            strUrl,
            method: .post,
            parameters: applicant,
            encoding: JSONEncoding.default,
            headers: headers).responseJSON { (response: DataResponse<Any>) in
                print(response)....................

Request:- 
["type": "express", "reports[][name]" : "facial_similarity"]
["Authorization": "Token token=test_d0dBA_b50LpMf-zRDfznR1iQ8uyvKTPc"]
https://api.onfido.com/v2/applicants/2d49e1e7-63e1-4dcb-b454-9cdf1bc6a50f/checks
Response :- 

SUCCESS: {
    error =     {
        fields =         {
            base =             (
                "Specify report or a package ids, not both."
            );
        };
        message = "There was a validation error on this request";
        type = "validation_error";
    };
}
statusCodeOptional(422)

**Comment by rahulshah007** [comment]
check my above code and can you please tell me what is the wrong?

**Comment by rfreitas** [comment]
Hi @rahulshah007,
We don't supply an api to make checks on iOS, because we don't recommend doing it on the device.
The android SDK also doesn't have that api, it simply depends on the onfido api java client, which is what you are accessing and which does have an api for checks. We don't have an onfido api swift client.

Also, I recommend you redact any tokens from further public messages.
If you need to share more details I recommend opening a ticket with our private tech support: api@onfido.com .

I'm closing this ticket for now.

**Comment by rahulshah007** [comment]
https://stackoverflow.com/questions/48830460/onfido-sandbox-error-422-unprocessable-entity-validation

I have same issue . Please give solution for that issue

**Comment by rfreitas** [comment]
This is not the recommended approach.

```
let parameters: Parameters = [
                "type":"express",
                "reports": [
                    ["name": "document"]
                ]
            ]
            
            let headers: HTTPHeaders = [
                "Authorization": "Token token=\(token)",
                "Accept": "application/json"
            ]
            
            let progressView = MBProgressHUD.showAdded(to: self.view, animated: true)
            progressView.label.text = "Creating check"
            
            let request = Alamofire.request("https://api.onfido.com/v2/applicants/\(applicantResult.id!)/checks",
                method: .post, parameters: parameters, encoding: JSONEncoding.default, headers: headers).responseJSON { response in
                progressView.hide(animated: true)
                debugPrint(response)
            }

**Comment by rfreitas** [comment]
```
let parameters: Parameters = [
                "type":"express",
                "reports": [
                    ["name": "document"]
                ]
            ]
            
            let headers: HTTPHeaders = [
                "Authorization": "Token token=\(token)",
                "Accept": "application/json"
            ]
            
            let request = Alamofire.request("https://api.onfido.com/v2/applicants/\(applicantResult.id!)/checks",
                method: .post, parameters: parameters, encoding: JSONEncoding.default, headers: headers).responseJSON { response in
                debugPrint(response)
            }
```
