### ISSUE TITLE
withUserConsentStep not found

### ISSUE THREAD

**Issue by mdcuk34** [onfido/onfido-ios-sdk#234]
### What was the expected behaviour?
The following code errors with: `Value of type 'OnfidoConfig.Builder' has no member 'withUserConsentStep'`:
```
var onfidoConfig = OnfidoConfig.builder()
    .withSDKToken(sdkToken)
    .withAppearance(appearance)
    .withConsentStep()
```

The docs [here](https://documentation.onfido.com/sdk/ios/21.1.0#swift-10) suggest this should enable the US Consent screen.

_Please let me know if you think this is better suited for the React Native repo, as this was directly related to Native code I felt this was the appropriate place to post._

### What happened instead?
- `Value of type 'OnfidoConfig.Builder' has no member 'withUserConsentStep'`

### Version info:
- Onfido SDK (Debug/Release): 20.1.0
- React Native SDK Version: 1.3.3

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

### Steps to reproduce:

- Integrate the onfido-react-native-sdk library into a React Native app.
- Try and edit the `onfido-react-native-sdk/OnfidoSdk.swift` file to include the `withConsentStep`. 
- Try and build the app.

**Comment by andra-radu** [comment]
hi @mdcuk34 It looks like document has been updated with wrong function name. 
The function should be withUserConsentStep()  rather than withConsentStep() . 
I have communicated this with the team to update doc. 
In the mean time can you please use withUserConsentStep ?

**Comment by mdcuk34** [comment]
> hi @mdcuk34 It looks like document has been updated with wrong function name.
> The function should be withUserConsentStep() rather than withConsentStep() .
> I have communicated this with the team to update doc.
> In the mean time can you please use withUserConsentStep ?

Hey @andra-radu, thanks for the note... unfortunately `withUserConsentStep` is also throwing the same error when used instead of `withConsentStep`. Here is the error again: `Value of type 'OnfidoConfig.Builder' has no member 'withUserConsentStep'`

**Comment by andra-radu** [comment]
Hi @mdcuk34 I'm currently checking with our SDK team and I will get back to you as soon as I will hear back from them.

**Comment by mdcuk34** [comment]
Thanks @andra-radu, did you have any luck?

**Comment by keremgund** [comment]
Hi @mdcuk34 , 
Thanks for reporting the issue. I've just checked the error and noticed that [latest RN SDK version](https://github.com/onfido/react-native-sdk/releases/tag/v1.3.3) doesn't point to the iOS SDK that has user consent screen. Thats why you're getting this error. 
I can see that you're trying to edit the OnfidoSdk.swift file manually but please note that it's not supported way of integration.
Given the root cause of the error, it's better to close this issue and open new one on  [RN repo](https://github.com/onfido/react-native-sdk) We can follow up progress there.

Thanks,
Kerem

**Comment by mdcuk34** [comment]
Thanks for getting in touch @keremgund! No problem, I've opened up another [issue](https://github.com/onfido/react-native-sdk/issues/33) in the React Native SDK repo to address this. Speak soon.
