### ISSUE TITLE
onfidoFlow.run() crash with Swinject 2.3.0

### ISSUE THREAD

**Issue by tuxfamily** [onfido/onfido-ios-sdk#25]
Hello.

After a `pod update`, I was unable to run the flow with SDK 5.4, 5.5 and 5.6 (I didn't test the fresh 6.0).

I found that the guilty is Swinject 2.3.0 and fixed the issue by adding 
`pod 'Swinject', '< 2.3.0'` to my Podfile.

Probably something to put in your Podspecs... :)

Cédric.

**Comment by anuragajwani** [comment]
Hello @tuxfamily,

Thanks for raising the issue, we are aware of this and have issued a fix on the SDK version 6.0.0. The new version is Swift 4.1 and 3.3 compatible.

Thanks,
Anurag
