### ISSUE TITLE
Getting a lot of erros with "Face not detected"

### ISSUE THREAD

**Issue by tnmendes** [onfido/onfido-ios-sdk#255]
### What was the expected behaviour?

I am getting a lot of errors regarding "Face not detected", which is happing to me and other users using our app. I am not sure if is because of black and white photos.

![IMG_18E421D8E4CD-1](https://user-images.githubusercontent.com/9822076/138264100-df8eda0a-98e4-4c5d-b752-ecb6d26233ba.jpeg)

By the way, we are using API V2. Can that be the cause? 
I also using SDK 18.1.0 is this the latest version supported by the API v2? 

### What happened instead?

Getting error with Face not detected.

### Version info:

- Onfido SDK (Debug/Release): 18.1.0
- iOS: 15, 14
- Xcode: 13.0
- Device/Simulator: iPhone SE 2Gen, iPhone 12 Pro, iPhone XS, etc
- Device/Simulator language:
- API V2

### Integration configuration:

`OnfidoConfig.builder()
        .withSDKToken(authorization)
        .withFaceStep(ofVariant: faceStep) // photo or video
        .withAppearance(self.getOnfidoAppearance()) // UI customisation
        .withDocumentStep(ofType: documentType) // Flow customisation, documents select
            .withCustomLocalization()
        .build()`

`let appearance = Appearance(primaryColor: Theme.Color.Btn.blueLeft, primaryTitleColor: Theme.Color.white, primaryBackgroundPressedColor: Theme.Color.Btn.blueLeft.withAlphaComponent(0.7), secondaryBackgroundPressedColor: Theme.Color.Text.grey, fontRegular: "OpenSans-Regular", fontBold: "OpenSans-Bold", supportDarkMode: false)`

### Steps to reproduce:

Just do normal flow document + selfie

**Comment by tnmendes** [comment]
This issue is happing with Portugueses passport, Swedish Passport, and Swedish ID card that have black and white images.

**Comment by mattsputnikdigital** [comment]
We have also encountered this issue and also driving licences (UK) having the 3 attempts with the "Glare detected" message. Potentially because the licence is pink and there is a hologram on the back.

**Comment by mikeger** [comment]
@tnmendes it's merged now, please try again. The configuration is coming from the service side, so re-running the app would be sufficient.
