### ISSUE TITLE
Getting a lot of errors with "Glare detected"

### ISSUE THREAD

**Issue by mattsputnikdigital** [onfido/onfido-ios-sdk#256]
As per this report https://github.com/onfido/onfido-ios-sdk/issues/255

On the latest Onfido release 23.0.0, but 22 as well, and tested on iOS 14 and 15 with iPhone X we have has a lot of reports that the user is asked to take 3 pictures of the front ( or back ) of their UK driving licence because of glare being detected.

This may be because the driving licence is laminated pink and the back as a foil / hologram which is always shiny.

Would it be possible to reduce the sensitivity a little bit?

**Comment by onfido-ios-team** [comment]
Hi @mattsputnikdigital 
As per report  #255 you mentioned, it was fixed in iOS 15.1. and on 
mikeger has merged the PR yesterday for Onfido SDK 23.0.1 
This issue should be fixed now. 

The configuration is coming from the service side, so re-running the app would be sufficient.
