### ISSUE TITLE
Carthage spec not updated for v23

### ISSUE THREAD

**Issue by pieterjan-vandegaer-kbc** [onfido/onfido-ios-sdk#257]
Hi,

Could the carthage spec be updated to include the latest sdk?
Currently it supports up to v19.

Thank you

**Comment by damian-kolasinski** [comment]
@anuragajwani do you guys plan on bumping Carthage json?

**Comment by seewah** [comment]
Hi we stopped supporting Carthage from version 20.0.0 onward (almost a year ago) and the carthage file here is only maintained for the older versions (pre 20.0.0). Unfortunately, we don't have any plan to reinstate Carthage support at the moment, especially with the increasing popularity of the other dependency frameworks
