### ISSUE TITLE
Invalid NFC string keys

### ISSUE THREAD

**Issue by samrayner** [onfido/onfido-ios-sdk#259]
These keys in Localizable.strings (all languages) are invalid due to the colon:
onfido_nfc_intro:title_passport
onfido_nfc_intro:title_card

This causes build errors for us as we generate enums off them using SwiftGen.

Thanks!

**Comment by anuragajwani** [comment]
@samrayner we have issued a fix on release 23.1.0.

https://github.com/onfido/onfido-ios-sdk/pull/261/files#diff-4f9b255276e88e16b95a32f763a400394a68641d001a40e535080a945fb9e4ebL316

https://github.com/onfido/onfido-ios-sdk/pull/261/files#diff-4f9b255276e88e16b95a32f763a400394a68641d001a40e535080a945fb9e4ebL324

This release is already available through Cocoapods. We'll soon finalise the release. For now can you test it out with the new release please?

**Comment by anuragajwani** [comment]
closing issue due to a lack of response
