### ISSUE TITLE
NFC Related Crashes

### ISSUE THREAD

**Issue by AndreasVerhoeven** [onfido/onfido-ios-sdk#262]
### What was the expected behaviour?

No crashes.

### What happened instead?

We get a crash in the Onfido library 

### Version info:

- Cocoapods (if applicable): no
- Onfido SDK (Debug/Release): 23.0.1 release
- iOS: iOS 12 <-> iOS 15
- Xcode: 13.1
- Device/Simulator: device
- Device/Simulator language: n/a

### Steps to reproduce:

We see multiple crashers per day related to Onfido's NFC integration - so far we've seen 5000 crashes related to to NFC, most of them crashing on exceptions like:

```
[__NSXPCInterfaceProxy_NFCHardwareManagerInterface areFeaturesSupported:callback:]: unrecognized selector sent to instance 0x28141f7f0
```

Although it seems like this is caused by an iOS framework issue, it might be appropriate to guard this in your SDK by wrapping it in an Obj-C code block that catches the exception and at least stops Onfido from crashing our app.

**Comment by mikeger** [comment]
Hey @AndreasVerhoeven ! Thanks for the report. Can you check if the entitlements are set correctly for your app? I am talking about those: https://github.com/onfido/onfido-ios-sdk#4-app-permissions
My suspicion is that when we are trying to use NFC to read the passport iOS is killing your app because the entitlements are not sufficient.

**Comment by mikeger** [comment]
CC @anuragajwani

**Comment by mattsputnikdigital** [comment]
We are seeing crashes as well and are not using the functionality.

__hidden#23848_ - Line 189
isNFCReadAvailableForDevice() + 189

Fatal Exception: NSInvalidArgumentException
-[__NSXPCInterfaceProxy_NFCHardwareManagerInterface areFeaturesSupported:completion:]: unrecognized selector sent to instance 0x2809eea80

**Comment by mikeger** [comment]
Hey @mattsputnikdigital , thanks for reaching out, the SDK still has the NFC code in it, which means that you need to have a `NFCReaderUsageDescription` [defined](https://github.com/onfido/onfido-ios-sdk#4-app-permissions) in your Info.plist, even if you are not using it. For the moment as the SDK is monolithic it's not possible to separate the NFC functionality.

**Comment by mattsputnikdigital** [comment]
@mikeger The app was fine for 99.9% of users with only 2 phones experiencing the crash. I did include that permission as I didn't want Apple thinking I was using the NFC code, and they allowed the app to release without it.

I have included it now, but I find it odd no phones were crashing apart from those 2 instances.

**Comment by mikeger** [comment]
Very interesting, can you share the anonymized stack trace of the crashing thread and maybe the exact phone models and OS versions for those two phones? You can send the stack trace to mike.gerasymenko at onfido.com

**Comment by mattsputnikdigital** [comment]
@mikeger sent!

**Comment by bengilroy** [comment]
@mikeger We saw crashes from this problem last week and thought updating to SDK version `24.2.0` and adding `NFCReaderUsageDescription` to our Info.plist would fix it but we're still seeing crashes for the following:
```
NSInvalidArgumentException: -[__NSXPCInterfaceProxy_NFCHardwareManagerInterface areFeaturesSupported:completion:]: unrecognized selector sent to instance 0x282f3a4e0
```
Please can you fix this as a priority? We are not using the NFC features & have followed documentation/steps above but still suffering the consequences of it being included in the SDK (as well as having to provide the NFC usage video for app review). Let me know if you need any further information for debugging. Currently seeing the crash occur on a variety of devices & iOS versions (15.2.1, 14.3, 14.6, 14.7.1) so doesn't seem specific to particular device/OS.

**Comment by mikeger** [comment]
Hey @bengilroy , thanks for sharing this, let me take a look on the problem ASAP. Can you also forward the anonymized crash logs to mike.gerasymenko at onfido.com?
Is it possible to crash the application during the debugging session, or you are so far only observing the crash logs coming from your telemetry?

**Comment by JackTudor96** [comment]
Hi @mikeger I'll drop you an email, I work with @bengilroy

**Comment by mikeger** [comment]
Hey folks @AndreasVerhoeven @bengilroy @mattsputnikdigital 
We had no way to de-symbolicate the crashes provided since they were generated based on the Bitcode-recompiled verison of Onfido framework. Now we released the [newest version](https://github.com/onfido/onfido-ios-sdk/releases/tag/24.3.0) with dSYMs included. Shall you use this version, you would submit your app with the dSYMs that would be used on the Apple end to create the de-symbolicated version of crash reports automatically and on your end.
Please give it a try and don't hesitate to provide us with the updated crash logs, which would give us a clue about what is going wrong with the SDK. Thanks!

**Comment by mikeger** [comment]
Hey folks, in order to keep the repo tidy, since there is no more activity here, I would give this issue another week to stay open and, if all is good then, would mark it resolved.

**Comment by tb-rendity** [comment]
Hello @mikeger. When triaging our bug reports I have found this specific crash. 
We have used the NFC permission `NFCReaderUsageDescription`

It is only one User who has experienced this issue so far. But I noticed that other users of your framework have experienced this issue so I have included this here.

@mikeger please give an acknowledgement that you have seen this issue. I wish to assist your team further to solve the issue. 


`Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x92d0c __exceptionPreprocess
1  libobjc.A.dylib                0x14ee4 objc_exception_throw
2  CoreFoundation                 0x163750 +[NSObject(NSObject) _copyDescription]
3  CoreFoundation                 0x2c60c ___forwarding___
4  CoreFoundation                 0x2b81c _CF_forwarding_prep_0
5  CoreNFC                        0x26148 -[NFCHardwareManager areFeaturesSupported:outError:]
6  CoreNFC                        0x24254 +[NFCReaderSession featureAvailable:]
7  Onfido                         0x164138 isNFCReadAvailableForDevice + 199 (NFCFlowCoordinator.swift:199)
8  Onfido                         0xcb900 uploadDocumentCapture + 258 (DocumentCaptureCoordinator.swift:258)
9  Onfido                         0xd6238 <name omitted> + 203 (DocumentCaptureSideCoordinator.swift:203)
10 Onfido                         0x1a5cc <name omitted> (<compiler-generated>)
11 Onfido                         0x1a5cc <name omitted> (<compiler-generated>)
12 UIKitCore                      0x384634 -[UIPresentationController transitionDidFinish:]
13 UIKitCore                      0x447e0 -[_UICurrentContextPresentationController transitionDidFinish:]
14 UIKitCore                      0x88fe44 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.437
15 UIKitCore                      0x22a964 -[_UIViewControllerTransitionContext completeTransition:]
16 UIKitCore                      0x30bc84 -[_UIAfterCACommitBlock run]
17 UIKitCore                      0x22733c -[_UIAfterCACommitQueue flush]
18 libdispatch.dylib              0x63094 _dispatch_call_block_and_release
19 libdispatch.dylib              0x64094 _dispatch_client_callout
20 libdispatch.dylib              0x10d44 _dispatch_main_queue_drain
21 libdispatch.dylib              0x10994 _dispatch_main_queue_callback_4CF$VARIANT$mp
22 CoreFoundation                 0x4e0c4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
23 CoreFoundation                 0xb5e8 __CFRunLoopRun
24 CoreFoundation                 0x1e240 CFRunLoopRunSpecific
25 GraphicsServices               0x1988 GSEventRunModal
26 UIKitCore                      0x4e541c -[UIApplication _run]
27 UIKitCore                      0x27eb88 UIApplicationMain
28 libswiftUIKit.dylib            0x27ee4 UIApplicationMain(_:_:_:_:)
29 Rendity                        0x6158 main (PushState.swift)
30 ???                            0x104f743d0 (Missing)`

**Comment by davidgdoll** [comment]
Hi all, I'm currently having the same issue, any updates?
