### ISSUE TITLE
fatalError  in Onfido/DocumentCaptureCoordinator.swift

### ISSUE THREAD

**Issue by AndreasVerhoeven** [onfido/onfido-ios-sdk#263]
### What was the expected behaviour?

No crashes.

### What happened instead?

We get several crashes a day related to a fatalError in Onfido/DocumentCaptureCoordinator.swift

### Version info:

- Cocoapods (if applicable): no
- Onfido SDK (Debug/Release): 23.0.1 release
- iOS: n/a
- Xcode: 13.1
- Device/Simulator: device
- Device/Simulator language: n/a

### Steps to reproduce:
Run Onfido's DocumentCapture code. Our users are getting a fatalError often - we've seen around a 1000 cases so far:

<img width="1456" alt="Screenshot 2021-11-09 at 15 34 05" src="https://user-images.githubusercontent.com/168214/140943429-3793dadb-f91b-49b4-a981-479f5e977adc.png">

**Comment by mikeger** [comment]
Hey @AndreasVerhoeven ! Thanks for the report, it is very valuable. Can you share with me the crash log, so we can desymbolicate it? Feel free to exclude the threads that are not crashing and any code from your end. I am mostly concerned about the addresses seen in the crashed thread in the Onfido.framework. My email is mike.gerasymenko at onfido.com

**Comment by AndreasVerhoeven** [comment]
Hi @mikeger, I'll send you the crash logs in a bit. After checking with hopper and comparing base addresses, it seems the crash is happening on the line with `Missing upload request to retry upload` in `Onfido.DocumentCaptureCoordinator.retryTapped(_:)`

**Comment by mikeger** [comment]
Hey @AndreasVerhoeven , thanks for checking it in-depth. We have the dSYMs for the libraries we are shipping, so if you would provide (anonymized) crash log of the crashing thread in text form we should be able to nail down the issue relatively easily.
For now, I've checked the code, it is the part of the NFC handling code, it goes like that:
```swift
    func retryTapped() {
        guard let uploadRequest = self.uploadRequest else {
            self.didError(OnfidoFlowError.exception(withError: nil, withMessage: "Missing upload request to retry upload"))
            return
        }
        ...
```
I've tested what happens when this is triggered and the SDK returned the error to the application.

**Comment by AndreasVerhoeven** [comment]
@mikeger I've sent you a sample of the crashlogs we have for this issue again to mike.gerasymenko at onfido.com . Please let me know if you received them, since the previous batch I sent never seem to have ended up in your mailbox :)

**Comment by anuragajwani** [comment]
@AndreasVerhoeven we have added some more defensive code in iOS SDK 24.1.0 which should prevent the crash. However it won't prevent the SDK sending you an error. For now can you adopt the new version and log the exception message please? This will help us to zero in on the actual issue.

Additionally could you also log the user journey using [user analytics](https://github.com/onfido/onfido-ios-sdk#user-analytics) please?

**Comment by mikeger** [comment]
@AndreasVerhoeven did the fix work for you, or further investigation is needed?

**Comment by gurpreet-onfido** [comment]
Hello @AndreasVerhoeven I hope you are doing well! Could you please confirm if the fix worked for you or if you need any additional help?

Kind regards,
Gurpreet Singh

**Comment by vguerci** [comment]
Closing as no answer, feel free to re-open if needed, thank you.

**Comment by acecilia** [comment]
For future reference. I am experiencing also multiple crashes in crashlytics that I can not reproduce and that seem to come from DocumentCaptureCoordinator:

```
Crashed: com.apple.main-thread
0  libswiftCore.dylib             0x39cd0 _assertionFailure(_:_:file:line:flags:) + 656
1  Onfido                         0xcee78 _hidden#15751_ + 198 (__hidden#15911_:198)
2  Onfido                         0xcfac4 _hidden#15758_ + 311 (__hidden#15911_:311)
3  Onfido                         0xd6b98 DocumentCaptureSideCoordinator.proceedWithUploadedImage() + 169 (__hidden#16296_:169)
4  Onfido                         0xdcff4 DocumentCaptureViewController.proceed() + 299 (__hidden#16687_:299)
``` 

The additional information for the crash says `Onfido/DocumentCaptureCoordinator.swift:198: Fatal error`.
The onfido version I am using is `22.1.0`.

I will try to update the SDK
