### ISSUE TITLE
No User Analytics events

### ISSUE THREAD

**Issue by Bardiamist** [onfido/onfido-ios-sdk#271]
### What was the expected behaviour?

See User Analytics events

### What happened instead?

I don't see any User Analytics event

### Version info:

- Cocoapods (if applicable): 1.11.2
- Onfido SDK (Debug/Release): 24.2.0 (debug)
- iOS: 15.2 and 15.2.1
- Xcode: 13.2.1
- Device/Simulator: Simulator (iPhone 13) and Device (iPhone 13 Pro)
- Device/Simulator language: English (US)

### Integration configuration:

<details>
  <summary>Implementation</summary>

//
//  Onfido.m
//  valr
//
//  Created by Dmitriy Shishkin on 13.03.2020.
//  Copyright © 2020 Facebook. All rights reserved.
//

#import <UIKit/UIKit.h>

#import "OnfidoSDK.h"
#import <Onfido/Onfido-Swift.h>

@interface OnfidoSDK () {
    RCTResponseSenderBlock _resolve;
    RCTResponseSenderBlock _reject;
}
@end

@implementation OnfidoSDK
{
  bool hasListeners;
}

RCT_EXPORT_MODULE()

- (NSArray<NSString *> *)supportedEvents {
  return @[@"OnfidoEvent"];
}

// Will be called when this module's first listener is added.
-(void)startObserving {
    hasListeners = YES;
    // Set up any upstream listeners or background tasks as necessary
}

// Will be called when this module's last listener is removed, or on dealloc.
-(void)stopObserving {
    hasListeners = NO;
    // Remove upstream listeners, stop unnecessary background tasks
}

RCT_EXPORT_METHOD(startSDK:(NSString *)token
                  applicantId:(NSString *)andApplicantId
                  resolver:(RCTResponseSenderBlock)resolve
                  rejecter:(RCTResponseSenderBlock)reject)
{
  OnfidoSDK *onfido = [[OnfidoSDK alloc] initWithResolver:resolve andRejecter:reject];
  dispatch_async(dispatch_get_main_queue(), ^{
    [onfido runWithToken:token andApplicantId:andApplicantId resolver:resolve rejecter:reject];
  });
}

- (id)initWithResolver:(RCTResponseSenderBlock)resolve andRejecter:(RCTResponseSenderBlock)reject {
  self = [super init];

  if (self) {
    _resolve = resolve;
    _reject = reject;
  }

  return self;
}

- (void)runWithToken:(NSString *)token
      andApplicantId:(NSString *)applicantId
            resolver:(RCTResponseSenderBlock)resolve
            rejecter:(RCTResponseSenderBlock)reject
{
  ONFlowConfigBuilder *configBuilder = [ONFlowConfig builder];

  [configBuilder withSdkToken:token expireHandler:^(void (^ handler)(NSString * expireHandler)) {
    [self dismiss];
  }];
  
  [configBuilder withDocumentStep];
  
  NSError *faceVariantConfigError;
  Builder *faceVariantBuilder = [ONFaceStepVariantConfig builder];
  VideoStepConfiguration *videoStepConfiguration = [[VideoStepConfiguration alloc]
                                                    initWithShowIntroVideo:YES
                                                    manualLivenessCapture:NO];
  [faceVariantBuilder withVideoCaptureWithConfig:videoStepConfiguration];
  [configBuilder withFaceStepOfVariant:[faceVariantBuilder buildAndReturnError:&faceVariantConfigError]];

  if (faceVariantConfigError == NULL) {
    NSError *configError = NULL;
    ONFlowConfig *config = [configBuilder buildAndReturnError:&configError];

    if (configError == NULL) {
      ONFlow *onFlow = [[ONFlow alloc] initWithFlowConfiguration:config];
      
      NSLog(@"Init: %@", config);
      
      [onFlow withEventHandler:^(Event * _Nonnull event) {
        NSLog(@"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!%@", event);
      }];
      
      [onFlow withResponseHandler:^(ONFlowResponse *response) {
        if (response.userCanceled) {
          [self dismiss];
          self->_reject(@[@"USER_LEFT_ACTIVITY"]);
        } else if (response.results) {
          [self dismiss];
          self->_resolve(@[applicantId]);
        } else if (response.error) {
          [self dismiss];
          self->_reject(@[response.error.localizedDescription]);
        }
      }];
    
      NSError *runError = NULL;
      UIViewController *onfidoController = [onFlow runAndReturnError:&runError];

      if (runError == NULL) {
        UIWindow *window = [UIApplication sharedApplication].windows[0];
        if (window) {
          UIViewController *rootViewController = [window rootViewController];
          if (rootViewController) {
            [onfidoController setModalPresentationStyle:UIModalPresentationFullScreen];
            [rootViewController presentViewController:onfidoController animated:YES completion:nil];
          } else {
            NSLog(@"Onfido rootViewController not found");
          }
        } else {
          NSLog(@"Onfido window not found");
        }
      } else {
        NSLog(@"Onfido runError: %@", runError);
      }
    } else {
      NSLog(@"Onfido configError: %@", configError.localizedDescription);
    }
  } else {
    NSLog(@"Onfido variantConfigError: %@", faceVariantConfigError.localizedDescription);
  }
}

-(void)dismiss {
  UIWindow *window = [UIApplication sharedApplication].windows[0];
  if (window) {
    UIViewController *rootViewController = [window rootViewController];
    if (rootViewController) {
      UIViewController *presentedViewController = [rootViewController presentedViewController];
      if (presentedViewController) {
        [presentedViewController dismissViewControllerAnimated:YES completion:nil];
      }
    }
  }
}

@end

</details>

### Steps to reproduce:

I added `withEventHandler` https://github.com/onfido/onfido-ios-sdk#user-analytics (why no Objective-C docs?)
Made full user verification
No any log from `withEventHandler` in result

**Comment by keremgund** [comment]
Hey @Bardiamist 
Thanks for reporting the issue. I'm happy to say that the issue has been fixed now and will be delivered as part of the next release.
I will let you know from here once the next version is out.

Kerem

**Comment by keremgund** [comment]
No, it's not sorry. It was an LTS release which had a limited number of
changes. The next regular release will contain the fix and you can spot it
on changelog.

Kerem

**Comment by kushal-onfido** [comment]
Hi @Bardiamist We have released a new version [24.3.0](https://github.com/onfido/onfido-ios-sdk/releases/tag/24.3.0) containing the fix to this issue. Please try this out and let us know in case of any issues.
Thanks!

**Comment by Bardiamist** [comment]
Thanks, I'll check it later
