### ISSUE TITLE
Github slack notifications not installed

### ISSUE THREAD

**Issue by alrocha** [onfido/onfido-ios-sdk#275]
Hello, when trying to add the slack notifications for github repo using
`/github subscribe onfido/onfido-ios-sdk releases` I get the following error saying that the app is not installed in the repo.

![image](https://user-images.githubusercontent.com/8307263/155231492-bd185dd7-96cd-4964-8940-d26558c91f39.png)

Could be possible to install it? I think just using this link as I could see in the docs https://github.com/apps/slack/installations/new
Thanks in advance!

**Comment by seewah** [comment]
Hi unfortunately as the slack app requires write access to the repo, we cannot enable it. However, you can probably build a slack notification using our RSS feed: https://github.com/onfido/onfido-ios-sdk/releases.atom. You can find more details here: https://slack.com/intl/en-gb/help/articles/218688467-Add-RSS-feeds-to-Slack

thanks

See Wah
