### ISSUE TITLE
ONFIDO_NO_LOCALIZED_VALUE error

### ISSUE THREAD

**Issue by faranmemon** [onfido/onfido-ios-sdk#276]
### What was the expected behaviour?
SDK should load default strings and should only update whatever is provided in our own localizable.strings file. 

### What happened instead?

Instead of showing proper texts, it shows **ONFIDO_NO_LOCALIZED_VALUE** text. 

### Version info:
- Cocoapods (if applicable): 1.11.2
- Onfido SDK (Debug/Release): debug
- iOS: 15.2.1
- Xcode: 13.2.1
- Device/Simulator: iPhone SE 2020
- Device/Simulator language: English

### Integration configuration:

Added this key in our localizable.strings file.
`"onfido_doc_capture_header_id_front" = "NIC - Front";
`
```
guard let config = try? OnfidoConfig.builder()
        .withSDKToken(sdk_token)
        .withAppearance(appearance)
        .withDocumentStep(ofType: documentType)
        .withFaceStep(ofVariant: .photo(withConfiguration: PhotoStepConfiguration(showSelfieIntroScreen: true)))
        .withCustomLocalization()
        .build() else {
            print("Error orccured")
            return
        }
```

**Comment by andra-radu** [comment]
Hello @faranmemon - Just to confirm if my understanding upon your query is correct;  you want to change one localized key, you've created the custom localization, but only included one changed key in it, expecting the SDK to fallback to default strings if they are not present into the custom bundle? If that's the case, I'm afraid this is not how the SDK works, if there is a custom bundle it’s reading the strings from there only, without the fallback.

**Comment by faranmemon** [comment]
Thanks, @andra-radu  for the clarifications. Yes, I was assuming the same. 
Since there's no option to achieve this, I think it's better to close this ticket.
