### ISSUE TITLE
Pod build fails 

### ISSUE THREAD

**Issue by mzealey** [onfido/onfido-ios-sdk#28]
Hi there, I've installed as a Framework Pod and when I try to compile my app I get an error stating `Include of non-modular header inside framework module 'Onfido'` in the line in Onfido.h that says:

```
#import <Onfido/GlareDetection.h>
```

I'm not wanting objc module anyway as I'll only be accessing from swift but it's still stopping me from building...

**Comment by mzealey** [comment]
Changing that to

```
#import "GlareDetection.h"
```

seems to fix it?

**Comment by anuragajwani** [comment]
Are issues https://github.com/onfido/onfido-ios-sdk/issues/28, https://github.com/onfido/onfido-ios-sdk/issues/29, https://github.com/onfido/onfido-ios-sdk/issues/30 related?
