### ISSUE TITLE
Fatal error when starting Onfido Flow on something related to the In-house Analytics

### ISSUE THREAD

**Issue by grsouza** [onfido/onfido-ios-sdk#281]
### What was the expected behaviour?

To start the Onfido flow

### What happened instead?

A crash on something related to the `internal analytics` of the Onfido SDK.

This is the fatal error message:
```
Onfido/InHouseAnalytics.swift:45: Fatal error: In-house analytics failed to track an event: InHouseAnalyticsEventPayload(event: "DOCUMENT_CONFIRMATION", eventUuid: "8626298D-65DA-40A1-A4B9-4977595A99E2", eventTime: "", source: "sdk", applicantUuid: "", clientUuid: "", sessionUuid: "", properties: ["event_type": "screen", "document_format": "passport", "step": "document"], sourceMetadata: Onfido.InHouseAnalyticsEventPayload.SourceMetaData(platform: "iOS SDK", version: "24.4.0", sdkEnvironment: nil), eventMetadata: Onfido.InHouseAnalyticsEventPayload.EventMetaData(os: "iOS", osVersion: ""), sdkConfig: Onfido.InHouseAnalyticsEventPayload.SdkConfig(expectedSteps: "document,face - type: photo", sdkToken: "UAaNtJm6qP42NW43HUioHkuz3yo7egZC", stepsConfig: [])) with error: The operation couldn’t be completed. (Onfido.ApiError error 0.)
```

### Version info:

- Onfido SDK (Debug/Release): 24.4.0 Debug mode
- iOS: 15.3
- Xcode: 13.3
- Device/Simulator: iPhone 13 Simulator
- Device/Simulator language: en_US

### Integration configuration:

This is the code snippet for creating the OnfidoConfig.

```swift
try OnfidoConfig.builder()
            .withAppearance(appearance)
            .withSDKToken(sdkToken)
            .withWelcomeStep()
            .withDocumentStep()
            .withFaceStep(ofVariant: .photo(withConfiguration: nil))
            .build()
```

### Steps to reproduce:

I've used a proxy for inspecting what's happening and this is what I get.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/5923044/159509346-0025e2c1-9b4c-4bfa-bdfe-831ab116cfe1.png">

**Comment by seewah** [comment]
thanks for reporting. it is only affecting debug build.
this has been fixed now, and will be released over the next couple of weeks.

**Comment by grsouza** [comment]
Does this has been fixed on https://github.com/onfido/onfido-ios-sdk/releases/tag/24.5.0 ?

**Comment by grsouza** [comment]
I've just tested and can confirm it's now fixed.
