### ISSUE TITLE
SwiftUI - Onfido Flow builder crashes on .run()

### ISSUE THREAD

**Issue by tb-rendity** [onfido/onfido-ios-sdk#282]
### What was the expected behaviour?
Onfido was supposed to start up the process

### What happened instead?

Onfido Flow factory crashes the app on onfidoFlow.run()
Below is the debug snippet. I am struggling to comprehend why this is failing

```
Swinject: Resolution failed. Expected registration:
	{ Service: (Event) -> (), Factory: (Resolver) -> (Event) -> () }
Available registrations:
"Segment analytics tracked: FLOW with properties: [\"state\": \"START\", \"localisation\": \"Bundle: file:///var/containers/Bundle/Application/3C9A4E96-D5D9-4F86-88CB-679133838191/Rendity.app/Frameworks/Onfido.framework/  - Table name: Localizable\", \"certificate_pinning\": \"off\", \"flow\": \"Step 0: intro ##### Step 1: document ##### Step 2: face - type: photo\", \"nfc_enabled\": \"off\"]"
Swinject: Resolution failed. Expected registration:
	{ Service: (Event) -> (), Factory: (Resolver) -> (Event) -> () }
Available registrations:
Onfido was compiled with optimization - stepping may behave oddly; variables may not be available.
Onfido was compiled with a different Swift compiler (version '1300.0.31.1') than the Swift compiler integrated into LLDB (version '5.6.0.323'). Swift expression evaluation requires a matching compiler and debugger from the same toolchain./Users/tim/Library/Developer/Xcode/DerivedData/Rendity-dmabqzohanweysagxeiebeyijiyv/Build/Products/Debug-iphoneos/Rendity.app/Frameworks/Onfido.framework/Onfido: Cannot load Swift type information; AST validation error in "Onfido": The module file format is too old to be used by this version of the debugger.
```

Please detail what was the actual behaviour

### Version info:

- Using Swift Package Manager
- Onfido SDK (Debug/Release): 14.4.0
- iOS: 15.3
- Xcode: 13.3 - Also tested on 13.2
- Device/Simulator: Device
- Device/Simulator language: en-NZ

### Integration configuration:

I have tried to follow the standard setup procedure for Onfido.
I got an SDK token for cofniguration and i used the standard configuration steps in stage 6 of the config.
try! onfidoFlow.run()
Crashes the app. 

Note that if i purposefully do not include some steps in the builder i get a fatal error saying that the onfido process is missing steps. This explicitly happens on the .run() step

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

### Steps to reproduce:

Follow the standard installation process using a fresh SwiftUI OR Storyboard app using Xcode 13.3.
I will attempt to install a lower version of LLDB to see if i can uncover more issues.

I have ran the SampleApp and I got it working.

My only other thoughts are there is something on the SwiftUI framework that is causing issues here.

**Comment by tb-rendity** [comment]
There could be something simple that i am missing in the project configuration. However because i cannot read the warnings I cannot hunt down the issue

**Comment by tb-rendity** [comment]
Using the help of https://github.com/onfido/onfido-ios-sdk/issues/270
I changed the flow of and my understanding of the issue and solved the problem.

I think that my understanding would have been increased and improved with advice on how to build and integrate onfido into a SwiftUI project. Now that more new projects are choosing SwiftUI I believe it would benefit developers to offer a combination of advice and a UIViewControllerRepresentable that can be packaged with the SDK.

**Comment by mikeger** [comment]
@tb-rendity thanks for reporting the problem, we definitely need to update our public documentation to reflect this detail.

**Comment by mairomejia96** [comment]
Hi @tb-rendity  can you help me to implement it with SwiftUI? or give me some instructions. Best Regards.

**Comment by tb-rendity** [comment]
Sure, it requires a little bit of understanding first of how this functions in UIKit - Swift or Obj-C. I would first start making a dummy implementation of that based off of the examples given in the documents.

Once you have that done. You should start adapting it to a swiftUI implementation. Our implementation is highly specific to our use case and may not suit yours. but maybe this along with #270 will help you come up with an implementation that works for you.

Our process is as follows:

We have a regular SwiftUI view - Lets call it 'CustomerVerifyView'
We have a view model for this view - Lets call it 'CustomerVerifyViewModel'

When the view model starts we fetch a token from our server (our server talks to onfido for the client app)

Once we have a token from the server we enable a button (it is disabled until a token is available) that when pressed will start the onfido process. Lets call the button 'start onfido'

When the user presses the button we will 'configure onfido'. This starts our 'onfido configuration' class that sets up the onfido flow process.
Once this is done we create an 'onfido view' this is a UIViewControllerRepresentable (provided from issue 270 on here).
This 'onfido view' is attached to an optional Published variable in the view model (CustomerVerifyViewModel). our original view 'customerVerifyView' listens to that published variable pointing to 'onfido view'. 

If the optional published variable exists and isnt nil. we will display 'onfidoView' on the CustomerVerifyView. We have an attached .onAppear call attached to this 'onfidoView' that will start the onfido process once it is visible to the user.

CustomerVerificationView:
`
// if the onfido config isnt available - it hasnt been started yet
    if viewModel.onfidoConfig != nil {
                    viewModel.onfidoConfig!.onfidoView
                        .onAppear(perform: {
                           // Onfido process has started so we display it
                            viewModel.onfidoConfig!.startOnfido()
                        })
                }
           
                    Button(action: {
                        // We only return the success case here.
                        viewModel.configureOnfido
                      }, label: {
                        Text("Start onfido"))
                    })
`

CustomerVerifyViewModel:

`
  func configureOnfido() {
         if let apiToken = apiToken {
            onfidoConfig = OnfidoConfiguration(sdkToken: apiToken) 
            // our implementation has a callback handling the response here
        } 
}
`

OnfidoConfiguration: (This was heavily built on top of the work done by #270 
`

class OnfidoConfiguration: ObservableObject {
    
    var onfidoView: OnfidoView
    var onfidoFlow: OnfidoFlow
    
    init(sdkToken: String, callback: @escaping (OnfidoResponse) -> Void) {
          // our implementation sets the appearance of onfido here

        let onfidoConfig = try! OnfidoConfig.builder()
            .withSDKToken(sdkToken)
            .withWelcomeStep()
            .withDocumentStep(ofSelectableTypes: [SelectableDocumentType.passport, SelectableDocumentType.drivingLicence])
            .withFaceStep(ofVariant: .video(withConfiguration: nil))
            .build()
        
        self.onfidoFlow = OnfidoFlow(withConfiguration: onfidoConfig)
            .with(responseHandler: { results in
                // Callback when flow ends - i removed this for simplicity for you
                callback(results)
              })
        
        self.onfidoView = OnfidoView(with: try! self.onfidoFlow.run())
    }
}

// This is called by your original view in the .onAppear - CustomerVerifyViewModel
extension OnfidoConfiguration {
    func startOnfido() {
        // Maybe we dont need this 0.1 delay
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
            self.onfidoView.start()
        }
    }
}
`

OnfidoView:
This is 100% the work of #270 here. I copied it letter for letter:
`
/**
 I built this from the following link
 https://github.com/onfido/onfido-ios-sdk/issues/270
 
 When the iOS app was originally built there was no Onfido SwiftUI advice. So this UIViewControllerRepresentable was built from the link. Then the connected parts were added based on our custom flow.
 */
struct OnfidoView: UIViewControllerRepresentable {
    typealias UIViewControllerType = UIViewController
    
    private let viewController: UIViewController
    private let presenterViewController = UIViewController()
    
    init(with viewController: UIViewController) {
        viewController.modalPresentationStyle = .overFullScreen
        self.viewController = viewController
    }
    
    func makeUIViewController(context: Context) -> UIViewController {
        presenterViewController
    }
    
    func updateUIViewController(_ uiViewController: UIViewController, context: Context) { }
}

// MARK: - External Utils
extension OnfidoView {
    func start() {
        presenterViewController.present(viewController, animated: true, completion: nil)
    }
    
    func end() {
        viewController.dismiss(animated: true, completion: nil)
    }
}
`


I hope this helps

**Comment by mairomejia96** [comment]
> 

@tb-rendity Thanks! I thing thats could works for me, I'll try to adapt to my code 😄
