### ISSUE TITLE
iOS SDK does not show permissions-needed screen if user has rejected permissions previously

### ISSUE THREAD

**Issue by 2-D** [onfido/onfido-ios-sdk#284]
### Description
The android and web onfido SDKs asks the user to provide permissions for mic & camera, if the user has already denied the app access. The iOS onfido SDK does not have this feature and should be consistent with the android and web SDKs.

In addition, the error code returned from the Onfido SDK error is not descriptive in this case. 

Web SDK Permissions Requested Screen

<img width="546" alt="Screenshot 2022-04-13 at 10 39 32 (1)" src="https://user-images.githubusercontent.com/4299249/163153187-c9377b3d-5961-4cd0-9184-ece79edbf05d.png">

### Version info:
- iOS: 22.0.0

**Comment by onfido-website-team** [comment]
Hi @2-D. Thanks for bringing this to our attention!
We are already aware of this. We cannot allow users to change permission in their settings without the SDK exiting.

This issue has already a response handler error `OnfidoFlowError.cameraPermission` 
        // It happens if the user denies permission to the sdk during the flow
        
Reference: https://github.com/onfido/onfido-ios-sdk#response-handler-errors
