### ISSUE TITLE
Import issue with Pod 1.5.0

### ISSUE THREAD

**Issue by mzealey** [onfido/onfido-ios-sdk#29]
If I do `import Onfido` it complains that framework `MBProgressHUD` is missing. This appears to be an issue with Pod 1.5.0 documented at http://blog.cocoapods.org/CocoaPods-1.5.0/ ; adding `use_modular_headers!` to the podfile fixes this issue.

**Comment by anuragajwani** [comment]
Hi @mzealey I recently created an app from scratch and imported Onfido SDK version 6.0.0, using Swift 4.1 and cocoapods 1.5.0. Everything ran ok. Check out issue https://github.com/onfido/onfido-ios-sdk/issues/27
