### ISSUE TITLE
Onfido 25.0.0 not working with simulator

### ISSUE THREAD

**Issue by zvjerka24** [onfido/onfido-ios-sdk#291]
### What was the expected behaviour?

Should be able to go through Onfido flow on simulator.

### What happened instead?

Stuck on document upload step.

### Version info:

- Cocoapods (if applicable):
- Onfido SDK (Debug/Release): Debug
- iOS: 15.5
- Xcode: 13.4
- Device/Simulator: Simulator iPhone13
- Device/Simulator language: En

### Integration configuration:

 let config = try OnfidoConfig.builder()
                .withSDKToken(token)
                .withCustomLocalization()
                .withAppearance(appearance)
                .withWelcomeStep()
                .withDocumentStep(ofType: .drivingLicence(config: DrivingLicenceConfiguration(documentFormat: .card)))
                .withFaceStep(ofVariant: .video(withConfiguration: nil))
                .build()
                
             let onfidoFlow = OnfidoFlow(withConfiguration: config).with(responseHandler: { onfidoResponse in
                switch onfidoResponse {
                case .cancel:
                    seal.reject(OnfidoError.cancelled)
                case .success(let results):
                    seal.fulfill(results)
                case .error(let error):
                    seal.reject(error)
                @unknown default:
                    seal.reject(OnfidoError.unknown)
                }
            })

        let viewController = try onfidoFlow.run()
        viewController.modalPresentationStyle = .fullScreen
        navigationController.present(viewController, animated: true)

### Steps to reproduce:

Just a simple Onfido integration that actually works on device and with previous version (18) it was working just fine on simulator. With this release we are not able to go through process flow on simulator. It stops on document upload step. As an error responseHandler returns an error (OnfidoFlowError)
▿ upload : OnfidoApiError {
    id = NULL,
    type = validation_error,
    message = There was a validation error on this request,
    fields = {"file":["has contents that are not what they are reported to be"]}
}
    - id : nil
    - type : "validation_error"
    - message : "There was a validation error on this request"
    ▿ fields : Optional<String>
      - some : "{\"file\":[\"has contents that are not what they are reported to be\"]}"

**Comment by ramprasad-parajuli** [comment]
@zvjerka24 thank you for flagging the issue. We need some information about the Macbook where this simulator is run - is it an Intel-based Macbook or an M1-based Macbook?

**Comment by zvjerka24** [comment]
It is M1-based Macbook. 
Tomorrow I will check also on Intel-based Macbook and will let you know status there.

**Comment by zvjerka24** [comment]
@ramprasad-parajuli it works on Intel-based MacBook, so it is actually "M1-based only" issue.

**Comment by ramprasad-parajuli** [comment]
@zvjerka24 thank you for your patience.

We tried to reproduce the issue using our test application on a simulator, but we were not able to reproduce the bug with the given parameters on the SDK versions 24.4.1/25.0.0/25.2.0.

Would it be possible for you to let us know your testing setup on the simulator? Are you using any third-party tools to access the camera on the simulator (like this one - https://github.com/YuigaWada/iCimulator)?

**Comment by zvjerka24** [comment]
No I'm not using any 3rd party tool for camera access. Just as regular usage on iPhone, but running on simulator. Just implementation that works on iPhone run on Simulator.

**Comment by zvjerka24** [comment]
Version v26.1.1. works fine in simulator.
