### ISSUE TITLE
User able to register with not supported document type

### ISSUE THREAD

**Issue by zvjerka24** [onfido/onfido-ios-sdk#294]
### What was the expected behaviour?

User is only able to register with driving licence.

### What happened instead?

User was able to register with ID card instead of a driving licence.

### Version info:

- Onfido SDK (Release): 25.0.0

### Integration configuration:

```
let config = try OnfidoConfig.builder()
                .withSDKToken(token)
                .withCustomLocalization()
                .withAppearance(appearance)
                .withWelcomeStep()
                .withDocumentStep(ofType: .drivingLicence(config: DrivingLicenceConfiguration(documentFormat: .card)))
                .withFaceStep(ofVariant: .video(withConfiguration: nil))
                .build()
                
let onfidoFlow = OnfidoFlow(withConfiguration: config).with(responseHandler: { onfidoResponse in
                switch onfidoResponse {
                case .cancel:
                    //...
                case .success(let results):
                    //...
                case .error(let error):
                    //...
                @unknown default:
                    //...
                }
            })

//...

let viewController = try onfidoFlow.run()
viewController.modalPresentationStyle = .fullScreen
navigationController.present(viewController, animated: true)
```

**Comment by gurpreet-onfido** [comment]
Hello Vladimir,

Greetings for the day!

The option does not restrict the users from uploading documents other than DLs. It just tells that only DL is acceptable. They still can upload the ID card and if it is from the Onfido supported documents, the check was processed accordingly.

We don’t do any on-device/real-time classification today, and don’t yet track “customer non-supported documents”.

If you have intro screens before our SDK flow you can call out that the user can only register with a DL. It still won’t block the end-user from uploading a different type but it may help.

Kind regards,
Gurpreet Singh

**Comment by zvjerka24** [comment]
Thank you @gurpreet-onfido for this info.
