### ISSUE TITLE
Missing umbrella header for version 25.1.0 at compiling

### ISSUE THREAD

**Issue by iCappsCedric** [onfido/onfido-ios-sdk#296]
### What was the expected behaviour?

We updated our Onfido SDK via cocoapods from an older version to the new 25.1.0 version. We expected it to compile at building.

### What happened instead?

The Onfido SDK gave back the following: 
Onfido/Onfido.framework/Headers/Onfido.h:33:1: error: umbrella header for module 'Onfido' does not include header 'OnfidoExtended.h'

^
<unknown>:0: error: could not build Objective-C module 'Onfido'

### Version info:

- Cocoapods (if applicable): /
- Onfido SDK (Debug/Release): /
- iOS: /
- Xcode: Xcode 13.4
- Device/Simulator: Simulator
- Device/Simulator language: English

How to recreate:
Go to Xcode builds settings > Swift compiler - warning policies > treat warnings as error: YES

If I turn this off, it does compile, but it is something that should not be turned off. Please fix it, so it compiles with it on.

**Comment by gurpreet-onfido** [comment]
Hello @iCappsCedric 

Thank you for bringing this up. I see, it is a legitimate warning arising from project generation and should be fixed.

We will let you know once the fix is rolled out. Stay tuned!

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello @iCappsCedric 

25.2.0 is not yet rolled out. I will notify you once we roll out the mentioned fix.

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello @iCappsCedric We have rolled out the release 25.2.0 that fixes this issue. Kindly check and let us know if you are still facing this problem.

Kind regards
Gurpreet Singh
