### ISSUE TITLE
Swift 2 style errors

### ISSUE THREAD

**Issue by francisjervis** [onfido/onfido-ios-sdk#3]
See https://gist.github.com/francisjervis/d3e2cd86e93613906c13bc98851c557e

This is how I had started implementing a class to access the REST API - the "failure" handling in your version is a bit unusual as it stands. -> (Applicant?, NSError?) passed to the completion handler would be more conventional; 
throws -> (Applicant?) would be the most Swift-ian ;)

**Comment by anuragajwani** [comment]
@francisjervis we have now moved now to Swift 3.0, have you checked the new docuemntation? Are still having issues ?

**Comment by anuragajwani** [comment]
Closing issue due to a lack of response
