### ISSUE TITLE
Very strange crash on app startup?

### ISSUE THREAD

**Issue by mzealey** [onfido/onfido-ios-sdk#30]
I'm using latest xcode & swift 3.3 or 4.1 with cocapods 1.5.0. I'm doing a very small (cordova) sample app (with only cordova-plugin-add-swift-support as plugin). Prior to importing Onfido pod the app loads fine in the simulator.

Then, I manually specify a Podfile like:

```
platform :ios, '8.0'

use_modular_headers!
target 'onfidoTest' do
    project 'onfidoTest.xcodeproj'
    pod 'Onfido'
end
```

I toss a .swift file in to the main project (not even referencing Onfido) in order to get it to compile without linker errors.

However the app shows the storyboard and then crashes with no crash message in the simulator logs (?!). It seems to be related to the linking when opening the app as stack trace is just `_dyld_start` and `__abort_with_payload`. I can't see any more enlightening info anywhere. Even starting from within simulator rather than via xcode it has no error message in the logs as far as I can see. Do you have any pointers as to what could be the issue here? I'm guessing it is some framework linking option hidden deep in build settings for something but I have not been able to locate it if so...

**Comment by anuragajwani** [comment]
As mentioned on the previous issue https://github.com/onfido/onfido-ios-sdk/issues/29, with a native Swift/ObjC app I am having no trouble in integrating. Could this possibly be a Cordova issue?

Anurag

**Comment by mzealey** [comment]
OK it looks like the root cause of this was using `use_modular_headers!` rather than `use_frameworks!`. I guess I trusted the 1.5.0 documentation too much when they said it was not needed. Adding `use_frameworks!` seems to fix these 3 issues. D'oh.

Fixes #28 
Fixes #29

**Comment by anuragajwani** [comment]
@TAiS46  try appending `, :modular_headers => true` to the Firebase pod(s). Let me know if that works. http://blog.cocoapods.org/CocoaPods-1.5.0/

**Comment by TAiS46** [comment]
Perfect, worked!

```
platform :ios, '9.3'
react_native_path = '../node_modules/react-native'

target 'EXAMPLE_APP' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Onfido', :modular_headers => true
  pod 'Firebase/Core'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == 'Swinject'
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '4.2'
              end
          end
      end
  end
end
```
