### ISSUE TITLE
UserConsent step always displayed

### ISSUE THREAD

**Issue by ajacquelin** [onfido/onfido-ios-sdk#303]
### What was the expected behaviour?
- When starting the OnboardingFlow:
```swift
            let config = try OnfidoConfig
                .builder()
                .withSDKToken(token)
                .withDocumentStep(ofType: documentType.toOnfidoDocumentType(countryCode: countryCode))
                .build()

```
The consent screen is always showed first when using the latest version `25.0.0`:
![Simulator Screen Shot - iPhone 13 mini - 2022-06-30 at 15 55 51](https://user-images.githubusercontent.com/1488200/176703289-99a28dde-678f-4780-af96-538c7ab7590c.png)

It is not the case on the `23.0.0`.
Is is the intended behavior ? If yes, how can I customize it ? The locale of this screen is always english. 
When passing the country code `FRA` for example I get the user consent in english and then the next step in french which seems weird.

**Comment by ramprasad-parajuli** [comment]
Hi @ajacquelin, thank you for flagging the issue. Unfortunately, we found a bug on iOS SDK version 25.0.0 that caused SDK to show a consent screen in all cases (no matter what the IP address is).
We have fixed the issue in our more recent version, i.e., 25.1.0. 
Could you please update the SDK to 25.1.0 and let me know if you experience the same issue?

> When passing the country code FRA for example I get the user consent in english and then the next step in french which seems weird.
Currently, there is no possibility of customizing language on the consent screen, and is only available in English.

**Comment by ajacquelin** [comment]
Thanks for the quick response!
- Is there any plan to not display the consent in full screen, for example accessible by a link ?
- For the localization, are you planning to localize the consent screen ?

**Comment by ramprasad-parajuli** [comment]
@ajacquelin 
> Is there any plan to not display the consent in full screen, for example, accessible by a link ?
Unfortunately, no. We have to legally call it out in the text to state the end-user saw it and read it.

> For the localization, are you planning to localize the consent screen?
No, we do not have any current plans to localize the consent screen in the near future.
