### ISSUE TITLE
NFC Crashes

### ISSUE THREAD

**Issue by davidgdoll** [onfido/onfido-ios-sdk#305]
### What was the expected behaviour?

No crashes.

### What happened instead?

Onfido SDK is crashing. 

### Version info:

- Cocoapods (if applicable): No
- Onfido SDK (Debug/Release): 24.2.0
- iOS: 15.5.0, 15.4.1, 15.1.0, 15.6.0, 15.3.0, 15.1.1
- Xcode: n/a
- Device/Simulator: Device
- Device/Simulator language: n/a

### Steps to reproduce:

This is basically a duplicate of https://github.com/onfido/onfido-ios-sdk/issues/262, since it was closed.

We have had a total of 54 crashes in the last 3 months related to Onfido and NFC.

Do you guys have any updates on this issue? 

### Crash information

`-[__NSXPCInterfaceProxy_NFCHardwareManagerInterface areFeaturesSupported:completion:]: unrecognized selector sent to instance 0x283918a00`

````
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x99288 __exceptionPreprocess
1  libobjc.A.dylib                0x16744 objc_exception_throw
2  CoreFoundation                 0x176fc4 +[NSObject(NSObject) _copyDescription]
3  CoreFoundation                 0x2de98 ___forwarding___
4  CoreFoundation                 0x2cf70 _CF_forwarding_prep_0
5  CoreNFC                        0x29014 -[NFCHardwareManager areFeaturesSupported:outError:]
6  CoreNFC                        0x26e0c +[NFCReaderSession featureAvailable:]
7  Onfido                         0x159b24 (Missing UUID 3fcae9e89b023463ad5bf95d74261f11)
8  Onfido                         0xc8250 (Missing UUID 3fcae9e89b023463ad5bf95d74261f11)
9  Onfido                         0xd29fc (Missing UUID 3fcae9e89b023463ad5bf95d74261f11)
10 Onfido                         0x1a728 (Missing UUID 3fcae9e89b023463ad5bf95d74261f11)
11 Onfido                         0x1a728 (Missing UUID 3fcae9e89b023463ad5bf95d74261f11)
12 UIKitCore                      0x3a5ab8 -[UIPresentationController transitionDidFinish:]
13 UIKitCore                      0x47fe8 -[_UICurrentContextPresentationController transitionDidFinish:]
14 UIKitCore                      0x8ef42c __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.461
15 UIKitCore                      0x23f168 -[_UIViewControllerTransitionContext completeTransition:]
16 UIKitCore                      0x3284dc -[_UIAfterCACommitBlock run]
17 UIKitCore                      0x23b864 -[_UIAfterCACommitQueue flush]
18 libdispatch.dylib              0x1e6c _dispatch_call_block_and_release
19 libdispatch.dylib              0x3a30 _dispatch_client_callout
20 libdispatch.dylib              0x11f48 _dispatch_main_queue_drain
21 libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF
22 CoreFoundation                 0x51800 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
23 CoreFoundation                 0xb704 __CFRunLoopRun
24 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific
25 GraphicsServices               0x1374 GSEventRunModal
26 UIKitCore                      0x514648 -[UIApplication _run]
27 UIKitCore                      0x295d90 UIApplicationMain
28 ott.client                     0x23c28 main + 26 (AppDelegate.swift:26)
29 ???                            0x10232dce4 (Missing)
```

**Comment by gurpreet-onfido** [comment]
Hello David,

Greetings for the day!

Could you please upgrade to the latest version of our SDK 25.1.1 and confirm us if the app still crashes for you?

I will wait for your update.

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello @davidgdoll 

Could you please let us know if you managed to upgrade the SDK to the latest version 25.2.0 of our SDK and still facing this issue? 

Looking forward to your response.

Kind regards
Gurpreet Singh

**Comment by davidgdoll** [comment]
Hey @gurpreet-onfido, we are updating this week and we gonna check the data for a few days to make sure the problem is fixed. I should come with an answer soon.
Thank you!

**Comment by davidgdoll** [comment]
Sorry for the late reply, seems like everything is great so far after upgrading to the latest versions.
