### ISSUE TITLE
Error 422 - Missing applicant location

### ISSUE THREAD

**Issue by ajacquelin** [onfido/onfido-ios-sdk#308]
### What was the expected behaviour?
In the latest API we have a mandatory `location` to add either:
- when creating an applicant 
or
- when uploading a document.
https://documentation.onfido.com/#location-create-applicant

Is there a way to add the location with the iOS SDK when uploading a document ? 
I was assuming that it was doing that with the following line:
```swift
OnfidoConfig
...
.withDocumentStep(ofType: Onfido.DocumentType.nationalIdentityCard(config: .init(country: "FRA"))
.build
```
but it does not seems to work.

Is there a way to specify it elsewhere ?

**Comment by gurpreet-onfido** [comment]
Hello Alexis,

Greetings for the day!

Please upgrade your iOS SDK to the latest version which is v25.1.1 and this will take care of the location information for you when the document is uploaded. 

Please refer to the following links for more information: 

https://developers.onfido.com/guide/migration-guide-onfido-privacy-notices-and-consent 

https://developers.onfido.com/guide/migration-guide-onfido-privacy-notices-and-consent#logic for more information. 

I hope this helps!

Let me know if there is anything else I can help you with.

Kind regards
Gurpreet Singh

**Comment by ajacquelin** [comment]
Thanks!
