### ISSUE TITLE
Error on Build about 'toIntMax()'

### ISSUE THREAD

**Issue by kuscan** [onfido/onfido-ios-sdk#31]
While doing the onfido ios sdk integration to my Xcode project I'm getting a 'Swift Compiler Error'. My project's swift language version is 4.1 It says that SDK is compatible with Swift 4.1 in readme. However, **ObjectMapper** dependency shows an error during build.

'toIntMax()' is unavailable 'toIntMax()' was obsoleted in Swift 4'

Anyone faced this issue?

Onfido sdk version 2.1.2
`pod 'Onfido', '2.1.2'`

**Comment by anuragajwani** [comment]
Hi @kuscan,

The readme is associated with Onfido SDK version 6.0.0, which is the version when we started [supporting Swift 4.1](https://github.com/onfido/onfido-ios-sdk/blob/master/CHANGELOG.md#600---2018-04-04). 

Anurag

**Comment by kuscan** [comment]
Hi @anuragajwani 

Is version 6.0.0 available to install via cocoapods. It does import version 2.1.2 when the version is not provided in podfile.

**Comment by anuragajwani** [comment]
@kuscan run `pod repo update`, remove `Podfile.lock` and the `Pods` directory and then run `pod install` again
