### ISSUE TITLE
pod install issue with checksum at Onfido 25.2.0

### ISSUE THREAD

**Issue by rick711003** [onfido/onfido-ios-sdk#311]
### What was the expected behaviour?

Just try to install  Onfido 25.2.0 from CocoaPod

### What happened instead?

I am try to using pod install the newest version but I always get below message

Installing Onfido 25.2.0 (was 23.0.0)

[!] Error installing Onfido
Verification checksum was incorrect, expected 03f6cb00cba2bab02f8d5a7c670a346d160e82787298b41010ddaff9f340b8d3, got 64f2f5ffe4902811cae4f0d0428db0ec4a9cbca6fb65b7b34c150003130d2764

### Version info:

- Cocoapods (if applicable): 1.11.3
- Onfido SDK (Debug/Release):
- iOS:
- Xcode:
- Device/Simulator:
- Device/Simulator language:

### Integration configuration:

<img width="1613" alt="截圖 2022-08-05 上午11 10 36" src="https://user-images.githubusercontent.com/582751/182993473-d6de7597-53ee-405c-a4d9-5847dcd38b0f.png">

### Steps to reproduce:

Update Podfile 
pod `Onfido`, `25.2.0`

pod install

**Comment by amansulaiman** [comment]
Same here

**Comment by vguerci** [comment]
Hello, thanks for reporting the issue and sorry for the inconvenience, we're on it.

Meanwhile don't worry about the checksum failure, this is just a CI issue on our end, our build wasn't tampered.

**Comment by vguerci** [comment]
Problem has been fixed, feel free to reopen this ticket if needed. Thank you.

**Comment by qeude** [comment]
@vguerci 👋🏻 I'm currently experiencing the exact same problem with SPM.
