### ISSUE TITLE
Error with missing billing info where billing is set

### ISSUE THREAD

**Issue by riclage** [onfido/onfido-ios-sdk#316]
### What was the expected behaviour?
We are trying to deploy our iOS app in production since everything works in our testing environment

### What happened instead?

Instead, what we get in production is the following error:

`{"error":{"type":"missing_billing_info","message":"Please provide your billing information before starting a new check","fields":{}}}
`

However, we have a contract with invoices already set and working for one of our other products. We opened a support ticket two days ago (ticket number 00097724) and so far we have not received any return. 

This is quite urgent because we are currently blocked by this issue before we can publish our app in production.

**Comment by gurpreet-onfido** [comment]
Hello @riclage 

Sorry for the delays in getting back to you!

I have checked that one of my colleagues has set your account to manual billing. So, you should no longer get this error and will be able to create checks without any issue.

Regarding the invoices and billing set up as your are requesting, this is being take care of and I will update here as soon as that is addressed. 

I appreciate your understanding & cooperation in this matter. 

Kind regards
Gurpreet Singh

**Comment by riclage** [comment]
Thank you, @gurpreet-onfido ! The service is working for us now. I will wait for your return on the invoices and billing part.

**Comment by gurpreet-onfido** [comment]
Hello @riclage Glad to know that the service is working fine now. I have spoken to your account manager and he will reach out to you for the billing issue directly via email/call. 

I am closing this thread. In case, you need any further help, please feel free to reach out to us. We will be happy to help!

Kind regards
Gurpreet Singh
