### ISSUE TITLE
25.2.0 can't be downloaded by SPM

### ISSUE THREAD

**Issue by ivan-gaydamakin** [onfido/onfido-ios-sdk#318]
### What was the expected behaviour?
Downloaded Onfido SDK by SPM

### What happened instead?

Got fatal error by Xcode:
`artifact of binary target 'Onfido' has changed checksum; this is a potential security risk so the new artifact won't be downloaded`

### Version info:

- Cocoapods (if applicable): -
- Onfido SDK (Debug/Release): 25.2.0 Release
- iOS: 15.4
- Xcode: 13.3.1
- Device/Simulator: -
- Device/Simulator language: English

### Steps to reproduce:

Just add to your project to SPM onfido sdk 25.2.0

**Comment by gurpreet-onfido** [comment]
Hello Ivan

Could you please try clearing SPMs package cache and let us know if that works for you? The package caches usually lives at:

~/Library/Caches/org.swift.swiftpm/repositories

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello @ivan-gaydamakin 

Did you get a chance to try the solution mentioned above and wondering if you have an update for us?

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello @ivan-gaydamakin 

Due to lack of response from your side, we are closing this up. Please feel free to reach out to us if the issue still persists.

Kind regards
Gurpreet Singh
