### ISSUE TITLE
Onfido 6.0.0 framework seem to not support i386 architecture

### ISSUE THREAD

**Issue by iaagg** [onfido/onfido-ios-sdk#32]
Project can't be compiled for iPhone 4s simulator after updating Onfido to 6.0.0 version. Receive Onfido - related compile errors.

**Comment by anuragajwani** [comment]
Hi @iaagg,

I will look into this.

Anurag

**Comment by iaagg** [comment]
@anuragajwani thanks!

**Comment by anuragajwani** [comment]
@iaagg the previous release had a change configuration which did not compile the i386 architecture. We have now fixed that on the version released 7.0.0. Note the API has not changed but rather the strings used in the SDK have change - this should only affect you if you use custom localisation feature. 

https://github.com/onfido/onfido-ios-sdk/blob/master/CHANGELOG.md#700---2018-04-17

Anurag

**Comment by anuragajwani** [comment]
@iaagg please let me know if your issue has been resolved.

Anurag

**Comment by iaagg** [comment]
@anuragajwani cool, thanks!
