### ISSUE TITLE
Updated to 7.0.0 build fails with " missing required architecture x86_64"

### ISSUE THREAD

**Issue by stshelton** [onfido/onfido-ios-sdk#33]
![screen shot 2018-04-17 at 1 38 59 pm](https://user-images.githubusercontent.com/11301401/38886699-b5db99dc-4244-11e8-811f-5a9c937eab54.png)

**Comment by anuragajwani** [comment]
Hello @stshelton,

I am looking into it now.

Anurag

**Comment by anuragajwani** [comment]
Hello @stshelton ,

I just checked the 7.0.0 release. The Onfido pod contains all relevant architectures. I have been able to compile against iPhone 4s simulator (i386), iPads (5th gen and pro - not sure if they use the same arch) (x86_64) as well as devices. Please check the slices contained within the Pod below. 

```
➜  SampleApp git:(release/7.0.0) ✗ file Pods/Onfido/Onfido.framework/Onfido
Pods/Onfido/Onfido.framework/Onfido: Mach-O universal binary with 4 architectures: [i386:Mach-O dynamically linked shared library i386] [arm64]
Pods/Onfido/Onfido.framework/Onfido (for architecture i386):	Mach-O dynamically linked shared library i386
Pods/Onfido/Onfido.framework/Onfido (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
Pods/Onfido/Onfido.framework/Onfido (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
Pods/Onfido/Onfido.framework/Onfido (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

Are you using Onfido-Release pod which contains only device compatible slices?

Anurag

**Comment by stshelton** [comment]
Yea I forgot I was using onfido-release, it built on the device and everything worked. Thanks for the quick response.

**Comment by alexpchin** [comment]
Hello, If I do: 

`lipo -info Pods/Onfido-Release/Onfido.framework/Onfido`

I can see: 

Architectures in the fat file: Pods/Onfido-Release/Onfido.framework/Onfido are: armv7 arm64

For Onfido 7.0.0 release? Is this correct? Are you not able to run the build on a simulator or a run tests with something like buddybuild with the release pod as I am getting the same error as @stshelton
