### ISSUE TITLE
Unable to update to 27.1.0 – Onfido.framework is 115.93 MB which exceeds GitHub's file size limit of 100.00 MB

### ISSUE THREAD

**Issue by bengilroy** [onfido/onfido-ios-sdk#337]
### What was the expected behaviour?
- To be able to update Onfido SDK to version 27.1.0 (#336)

### What happened instead?
- Able to update, but once committed to a branch I am unable to push the branch to GitHub because the Onfido framework is too large.

### Version info:

- Cocoapods (if applicable): 1.11.3
- Onfido SDK (Debug/Release): 27.1.0
- iOS: 16.1
- Xcode: 14.1
- Device/Simulator: N/A
- Device/Simulator language: N/A

### Integration configuration:
Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

Podfile:
```
pod 'Onfido', '27.1.0'
```

### Steps to reproduce:
- Install/update to #336 on a branch, and try to push the branch to GitHub.
- Compare size of the SDK between version 27.0.0 and 27.1.0

### Workaround:
- Rollback to 27.0.0

**Comment by vguerci** [comment]
Hello, @bengilroy we have just released [v27.3.0](https://github.com/onfido/onfido-ios-sdk/releases/tag/27.3.0) that reduces the binaries size.
Note that we can't guarantee in the future that our binaries won't go over that 100MB limit, you might want to consider another integration mode, like SPM or CocoaPods.
