### ISSUE TITLE
Updated to 7.0.0 build fails with " missing required architecture x86_64"

### ISSUE THREAD

**Issue by alexpchin** [onfido/onfido-ios-sdk#34]
Hello, If I do:

```
lipo -info Pods/Onfido-Release/Onfido.framework/Onfido
```

I can see:

```
Architectures in the fat file: Pods/Onfido-Release/Onfido.framework/Onfido are: armv7 arm64
```

For Onfido 7.0.0 release? Is this correct? Are you not able to run the build on a simulator or a run tests with something like buddybuild with the release pod as I am getting the same error as @stshelton in Issue #33

**Comment by anuragajwani** [comment]
Hello @alexpchin,

The pod `Onfido-Release` is specifically built for App Store submission which rejects simulator slices. We don't support running the SDK on the simulator anyhow but we have a build for simulators regardless for purpose such as is your case. Please replace `Onfido-Release` in favour of `Onfido` inside your `Podfile` for `Debug` configuration. You can find more on why we have two frameworks [here](https://github.com/onfido/onfido-ios-sdk/blob/master/docs/FAQ.md). We have a section on App Store submission on the REAME file too, more on that [here](https://github.com/onfido/onfido-ios-sdk#app-store-submission).

Anurag
