### ISSUE TITLE
Tests running via fastlane fail

### ISSUE THREAD

**Issue by kuscan** [onfido/onfido-ios-sdk#35]
We have 4 configurations for our Xcode project: **dev test stage** and **prod**

dev configuration is only used for development purposes. However, we have 3 applications created on itunesconnect for **test stage** and **prod** configurations. I mean, they all have different bundle identifiers. Also, we are using fastlane and testflight for delivery.

When we run `fastlane distribute-test` , test configuration of our application is built, its tests run and app is uploaded to Testflight (itunesconnect).

In order to run tests, fastlane uses iPhone simulator. So we need 'Onfido' pod to enable that. However, when the build is uploaded to itunesconnect's Testflight, it behaves like AppStore and it needs 'Onfido-Release' pod, not 'Onfido' pod.

What kind of workaround can we use?

**Comment by anuragajwani** [comment]
Unless anything has changed in iTunesConnect, it will reject a compiled swift framework with simulator slices, therefore a build to run tests on a Simulator has to be different from a build to upload to iTunesConnect. Therefore running tests on simulator will require the `Onfido` pod whereas as build/archive to upload to iTunesConnect will require `Onfido-Release` pod.

You might be able to achieve this by specifying on which the build configuration(s) the pod should be used. i.e.

`pod 'Onfido', :configurations => ['test']`
`pod 'Onfido-Release', :configurations => ['stage', 'prod']`

Within the same lane you might have to make two builds one for test one for stage/prod.

Anurag

**Comment by kuscan** [comment]
My podfile looks like

> pod 'Onfido', :configurations => ['dev']
> pod 'Onfido-Release', :configurations => ['test', 'stage', 'prod']

When I change it to the one you suggested, it fails to upload to Testflight.

> pod 'Onfido', :configurations => ['test']
> pod 'Onfido-Release', :configurations => ['stage', 'prod']

I found a workaround to run tests for my application in only **dev** configuration. However, this actually means that, my app is being uploaded to Testflight without being tested in correct configuration. (Actually I am testing it manually by changing the pod, but it would have been great to automate this)

Faruk

**Comment by anuragajwani** [comment]
@kuscan unfortunately until TestFlight and iTunesConnect don't auto remove simulator slices from swift frameworks it would be really hard for us to support your request (we would have to convert everything to ObjC)

**Comment by kuscan** [comment]
@anuragajwani thank you for your support though. what should we do with this issue then? close it?

**Comment by anuragajwani** [comment]
@kuscan sorry for the late reply, yes I will close the issue in the meantime

Anurag
