### ISSUE TITLE
Can't build on latest pod release

### ISSUE THREAD

**Issue by imclean** [onfido/onfido-ios-sdk#36]
Seems that this may be a duplicate, but how are we meant to integrate this in Swift 4 when ObjectMapper won't build and you have this as a dependency?

**Comment by imclean** [comment]
Is it possible you can create a new build with Version 9.3.1?  We can't even add the precompiled build you provide as it is built with 4.0.3 and you can't add older modules to 4.1

**Comment by anuragajwani** [comment]
Hey I suggest you to run `pod repo update` as Onfido pods version 6.0.0 and 7.0.0 are built with Xcode 9.3 and Swift 4.1

**Comment by imclean** [comment]
I'm afraid that won't do it.
You are still using ObjectMmapper 4.1.0 and Onfido (2.1.2)

**Comment by anuragajwani** [comment]
try running the following at the root of your project:

1. `pod repo update`
2. `rm Podfile.lock`
3. `rm -rf Pods`
4. `pod install`

the first time you run `pod install` it creates a `Podfile.lock` subsequent `pod install`'s will use the version set in your `Podfile.lock`. By removing it `pod install` will fetch the latest `Onfido` pod cached in your master specs repository.

**Comment by imclean** [comment]
Yeah the issue is you have an old dependency, I tried all that:

`[!] CocoaPods could not find compatible versions for pod "Alamofire":
  In Podfile:
    AlamofireImage (~> 3.3) was resolved to 3.3.1, which depends on
      Alamofire (~> 4.5)

    Onfido (~> 7.0) was resolved to 7.0.0, which depends on
      Alamofire (< 4.5)`

**Comment by imclean** [comment]
If you check your pod spec, you probably have Alamofire <4.5, where we need ~>4.5

**Comment by anuragajwani** [comment]
@imclean we are currently in the process of removing Alamofire as a dependency and will have removed in the next release. We expect to release within the next two weeks. Until then is it possible to use Alamofire 4.4.0?

**Comment by imclean** [comment]
The problem is more AlamofireImage which relies on the latest Alamofire, I've removed that for now until we can get a new release.

**Comment by gytismobon** [comment]
@anuragajwani Any news on that? I'm running into the same issue with AlamofireImage, as its version 3.3.1 requires Alamofire ~> 4.5.

@imclean One solution (which is not very elegant, but it works) is to use Alamofire 4.4.0 installed via pods and AlamofireImage 3.3.1 installed via carthage. The two dependency managers don't see each other and thus allow the operation.

**Comment by anuragajwani** [comment]
@gytismobon @imclean we have release Onfido iOS SDK 7.1.0 which no longer depends on Alamofire as well as MBProgressHUD I'll close this issue now but if you do encounter any issues please let us know 🙂.

Anurag
