### ISSUE TITLE
OnfidoFlowError Swift type doesn't exist anymore

### ISSUE THREAD

**Issue by qeude** [onfido/onfido-ios-sdk#360]
### What was the expected behaviour?

As explained in the README, and since there is nothing about that in migration guides and CHANGELOG, I would expect it to still exist (It seems like the ObjC side of it still exists.

### What happened instead?

The type doesn't exist anymore.

### Version info:

- Onfido SDK (Debug/Release): 28.2.0 using SPM

### Steps to reproduce:

Just try to handle `OnfidoFlowError` in a project that uses the Swift Package

**Comment by vguerci** [comment]
Hello, and thanks for your report,

These have been removed from the public namespace by error and will be reinstated in the next version soon.

Sorry for the inconvenience.

**Comment by LoicK20** [comment]
Hi!

I see the release notes for the 28.3.0: `Fixed missing OnfidoApiError and OnfidoFlowError types`

But I just update my Onfido dependency to version 28.3.0 from SPM but I still have this issue "Cannot find type 'OnfidoFlowError' in scope".

Best regard

**Comment by vguerci** [comment]
Hello,

The `28.3.0` tag was pushed by error on `28.2.0`, so you weren't using latest version.
As SPM is aggressively caching the versions, I've just pushed a `28.3.1` version tag that would solve your problem.

Sorry for this other inconvenience and thank you for your patience 🙏

**Comment by vguerci** [comment]
Closing, feel free to reopen if you still encounter issues.
