### ISSUE TITLE
Appearance API Suggestions

### ISSUE THREAD

**Issue by musiienko** [onfido/onfido-ios-sdk#372]
Hi there 👋🏻
We've been using Onfido SDK in our project for quite some time already and are really happy with the results, thank you for that! 🙏🏻
To make the user experience during the document verification even better, we'd like to have a possibility to configure some of the elements in a way to match the style guide of our app. So I was wondering if these points are somewhere on your roadmap already or could be added and maybe even implemented soon 😏

So here's a couple of things that we would find quite useful:

1. A possibility to configure the corner radius for buttons based on their size. As a possible solution for this, a closure (with the default implementation that has to be called probably on `layoutSubviews`) can be introduced:
```swift
@objc(ONAppearance) final public class Appearance : NSObject {
    ...

    @available(*, deprecated, message: "Use `buttonCornerRadiusClosure` instead")
    @objc final public var buttonCornerRadius: CGFloat
    @objc final public var buttonCornerRadiusClosure: (UIView) -> CGFloat
}

let appearance = Onfido.Appearance()
appearance.buttonCornerRadiusClosure = { $0.bounds.midY }
```
2. Navigation Bar Style. Currently, it looks like you set a custom `titleView` on the `navigationItem` which does not respect the provided `UINavigationBarAppearance` from our side (Yeah, I know there is no "open" API for that, but since a returned view controller is a navigation controller, I wanted to see what we can do with that🤭). As a possible solution, a boolean can be introduced to control the look of the navigation bar:
```swift
@objc(ONAppearance) final public class Appearance : NSObject {
    ...
    @objc final public var useCustomNavigationBarAppearance: Bool = false
}

let appearance = Onfido.Appearance()
appearance.useCustomNavigationBarAppearance = true

let viewController = onfidoFlow.run()
if let navigationController = viewController as? UINavigationController {
    let navBarAppearance = UINavigationBarAppearance()
    // configure the appearance
    navigationController.navigationBar.standardAppearance = navBarAppearance
}
```
3. More robust label configuration to have a possibility to apply different text styles (at least fonts or maybe even colors) to title/subtitle/body/button labels. In our case, we'd like to have a completely different font for the title and for the button title, but right now they are set by the `fontBold` property. In the end, it can look pretty similar to what Android offers at the moment:
```swift
@objc(ONAppearance) final public class Appearance : NSObject {
    ...
    @objc final public var titleLabelFont: String?
    @objc final public var subtitleLabelFont: String?
    @objc final public var bodyLabelFont: String?
    @objc final public var buttonFont: String?
}
```
4. One other thing I noticed is that the order of buttons on Document Photo/Selfie differs. In the first case it's a primary and then a secondary one, while on the Selfie step it's vice versa. It's reproducible on the Simulator (can't really remember though if this is also the case for the production env and the real device). If there's no business decision to make it so, it'd be awesome to have those two aligned.

Looking forward to your feedback and feel free to reach out if more information is needed! 💪🏼

**Comment by abozaidibrahimON** [comment]
@musiienko Thanks for your valuable suggestions, 
we are happy to introduce the features that you would love, please keep it up, we are keen to hear from you more. 
1. we will discuss your suggestions in the next OKR plan. 
2. we did a slight improvement in the appearance object coming soon in iOS 29.2.0, and much more is coming in the next quarter.

**Comment by abozaidibrahimON** [comment]
Will close the ticket but definitely you keep suggestions coming and will keep an eye on them.
