### ISSUE TITLE
Version without Cocoapods dependency

### ISSUE THREAD

**Issue by AndreasVerhoeven** [onfido/onfido-ios-sdk#38]
We don't use cocoapods and have no intention of doing so: is there a version available that works without having to set up cocoapods?

**Comment by anuragajwani** [comment]
@AndreasVerhoeven you can manually install the framework and its dependencies by adding them in your target within xcproj. Here is the spec for Onfido https://github.com/CocoaPods/Specs/blob/master/Specs/c/9/3/Onfido/7.0.0/Onfido.podspec.json . The file contains the location of where the framework is hosted as well as the dependencies required by our framework which will also have to be fetched manually or using another dependency manager supported by these dependencies.

**Comment by AndreasVerhoeven** [comment]
Thanks - unfortunately, it seems that the linked framework file requires all the other dependencies as dynamic frameworks as well: This influences app startup time negatively. Is there a version available which does not require the dependencies to be dynamic frameworks?

For a possible future release: It would be really nice to have a version:
 - that does not depend on any external files/libraries (bringing in external code is always a risk - who audits the code? Who is responsible for problems?)
 - does not require Cocoapods or any other package manager (our app doesn't use any package manager at all)
 - does not depend on swift. Our app doesn't use swift, so linking in this SDK requires 20MB of extra files for no benefit. (There's also no stable binary interface for swift - so one has to have an exact match between build tools)

**Comment by huangmr** [comment]
trying to use the pre-build releases (5.5.0) and it doesn't work with swift 3.3 or 4.1. currently only works with swift 4.0. and agree with @AndreasVerhoeven that it would be absolutely great if there is a single framework that doesn't require other libs/frameworks.

**Comment by rfreitas** [comment]
hey guys, the builds folder is a legacy issue, that we will clean up. Please don't use it.

In case you want to use the sdk without cocoapods then Anurag's link provides a workaround.
However, it's important to follow the spec accurately, by making sure you have the same dependencies matching the spec and that you use the binary which is at
```
"source": {
    "http": "ONFIDO_SDK_BINARY_URL"
  },
```

Here you can see the link with all the versions of the sdk and their specs: https://github.com/CocoaPods/Specs/tree/master/Specs/c/9/3/Onfido

Here you can find the link for the release specs (necessary for publishing):
https://github.com/CocoaPods/Specs/tree/master/Specs/a/3/c/Onfido-Release

**Warning**: This is by definition a hack. We cannot guarantee how Cocoapods manages this tree of files. Therefore we recommend that you don't rely on these URLs for Continuous Integration, but instead download all the necessary artefacts and host them by yourself.

With regards to the idea of having two versions without any external dependencies and one with (potentially shared) external dependencies, it's an interesting one. However, the cost will always be that no shared dependencies means a bigger size.

**Comment by AndreasVerhoeven** [comment]
That's some great and impressive work: thanks! We'll be sure to test 10.0.0 shortly! :)

**Comment by anuragajwani** [comment]
@AndreasVerhoeven awesome 😎no worries. Please let me know if we can close this issue 🙂

**Comment by anuragajwani** [comment]
@AndreasVerhoeven closing ticket. You can download releases from 10.1.0 onwards using Github releases https://github.com/onfido/onfido-ios-sdk/releases

**Comment by AndreasVerhoeven** [comment]
@anuragajwani sorry for the late response: we haven't been able to test this version, since we are stuck on Xcode 9 (because of Xcode's 10 iOS9 crash bug). Unfortunately, this version does not seem to work with Xcode 9.

**Comment by anuragajwani** [comment]
@AndreasVerhoeven it looks like this has been fixed on Xcode 10.1 https://stackoverflow.com/a/52614882/2982993

**Comment by AndreasVerhoeven** [comment]
@anuragajwani unfortunately, it hasn't been fixed (Apple later removed it from the list of fixes in the documentation)
