### ISSUE TITLE
Can't build on Xcode 10

### ISSUE THREAD

**Issue by imclean** [onfido/onfido-ios-sdk#41]
Can you please create a new release that has been built on Xcode 10?

Apps cannot be tested for future iOS 12 compatibility as your module fails:

> Module compiled with Swift 4.1 cannot be imported in Swift 4.1.50

**Comment by anuragajwani** [comment]
@imclean we have not tested the SDK using Xcode 10 unfortunately. We are planning to test it out at the end of July (estimated).

**Comment by kinejara** [comment]
Is there any update on this ? I have started testing on iOS 12 and I am getting the same issue.

**Comment by anuragajwani** [comment]
@kinejara we tried compiling the SDK at the end of July with Xcode 10. Unfortunately it did not succeed. We then proceeded with removing a bundled dependency that was not compiling which was already on the roadmap. This task is currently being reviewed. Once that is completed we will be able to compile the SDK using Xcode 10 and Swift 4.2 and release after that.

**Comment by Pikorua** [comment]
@anuragajwani 
Any idea how soon this will happen? 
Thanks

**Comment by anuragajwani** [comment]
@Pikorua we attempted releasing for Xcode 10 beta, `xcodebuild archive` for frameworks consistently fails. We will restart the release process for Xcode 10 once the general release is out. It will be our priority.

**Comment by anuragajwani** [comment]
@imclean @Pikorua @kinejara now that the general release of Xcode 10 is out we have started the release process to deploy a Swift 4.2 and Xcode 10 compatible framework. I'll keep you updated.

**Comment by Pikorua** [comment]
Great! Thank you so much for the update @anuragajwani

**Comment by anuragajwani** [comment]
@imclean @Pikorua @kinejara we have now release iOS SDK 10.0.0 which is Swift 4.2 and Xcode 10 compatible. Please let me know if you encounter any issues.

**Comment by jslew** [comment]
Is there some reason you are distributing the SDK in binary form?  We are trying to incrementally migrate from Xcode 9 to 10 and can't do it because you don't distribute SDK sources

**Comment by jslew** [comment]
That would be cool. Alternately, if there was some documented procedure to have both the Xcode 9 and Xcode 10 SDK in our codebase and be able to conditionally point to one or the other depending on which version of Xcode is being used, that'd work for the time being.   Not holding my breath for ABI stability ;)

**Comment by rfreitas** [comment]
Do you need to compile for both Xcodes at the same time, or do you just need access to the latest Xcode as soon as it's out?
We are exploring compiling to more than one swift version, but it's very early exploration and so far we only had one request. It would be interesting to know your usecase in case you need too.

**Comment by heavyskyl** [comment]
Still have same issue with Onfido 10.0.0 pod on xCode 10. Build is succeeded with 'New' and 'Legacy' build systems. But when application starts running I got "Thread 1: signal SIGABRT"

<img width="751" alt="screen shot 2018-10-04 at 14 45 57" src="https://user-images.githubusercontent.com/3448508/46474957-78535c00-c7e4-11e8-8a38-c28c8f9b8b50.png">
