### ISSUE TITLE
Custom localization issue

### ISSUE THREAD

**Issue by SergejLogis** [onfido/onfido-ios-sdk#46]
We are using custom localization for Onfido in out project. All works fine except for when app localization language is changed Onfido UI still uses localization from the previous language (the one which was active on app launch). To fix that app must be killed. Any ideas why does this happen and how to fix it?
Thanks.

**Comment by anuragajwani** [comment]
@SergejLogis What method are you using to change the app localisation language?

**Comment by SergejLogis** [comment]
We use [Lokalise](https://lokalise.co/) to manage app localization. It swizzles `NSBundle` and works fine across our screens. Onfido calls to `NSLocalizedString` pass through Lokalise SDK and it serves strings for selected locale. The only idea I have is that Onfido SDK caches strings (e.g. for performance sake). 🤓

**Comment by anuragajwani** [comment]
@SergejLogis are you still having problems with custom localisation? We encountered through another customer an issue with non localised files not working and have fixed the issue for them. It might be related to your problem. Please let me know if this is still an issue for you.

Anurag

**Comment by SergejLogis** [comment]
Thanks a lot, Anurag!
We just checked out the new SDK, and I can confirm that localization issue is now fixed (kind of). Previously, in order to change the Onfido language, we had to restart the app. With 11.0 we can change the language right away, but only once 😅In order to change it again - the app still needs to be restarted. Anyway, it's **much** better now!

**Comment by anuragajwani** [comment]
awesome news! glad I could help 🙂

I didn't quite follow the last part where you need to restart the app. Are we only talking about the SDK language? If you are using non-localised files you only need to exit the first flow and intiate a second flow with a slightly different config where you specify the non-localised file for the other language you wish to see.

Also has this solved your initial problem?

Anurag

**Comment by SergejLogis** [comment]
As mentioned before, we use `Lokalise` to handle our app localization. Whenever a user changes app language, we pass that to `Lokalise` (which has swizzled `NSLocalizedString`) and we get loacalized strings everywhere in the app. Prior to Onfido SDK 11.0 we needed to restart the app for the new language to be picked by Onfido UI. Now, the first time we change the language after app launch works just fine (I believe that covers 99% of users). However, to change language again we still need to restart the app 🤓

**Comment by anuragajwani** [comment]
OK closing issue for now then.

Thanks,
Anurag
