### ISSUE TITLE
Lots of Swift compiler warnings about missing includes in umbrella header

### ISSUE THREAD

**Issue by SergejLogis** [onfido/onfido-ios-sdk#47]
![screen shot 2018-09-17 at 10 34 18](https://user-images.githubusercontent.com/32644729/45610656-62643e00-ba65-11e8-9255-f503f5878129.png)
We are getting lots of warnings from Onfido SDK in our project. It pollutes build log and makes it harder to spot actual warnings. Is it possible to fix that? I found few articles related to that issue, but all solutions require modification of included project, that is **Onfido**.
Thanks!

**Comment by anuragajwani** [comment]
@SergejLogis which version of Onfido are you using? We have included the fixes for them on our latest version https://github.com/onfido/onfido-ios-sdk/blob/master/CHANGELOG.md#1000---2018-09-13. Let me know if you still encounter the issue on version 10.0.0.

**Comment by SergejLogis** [comment]
Thanks, @anuragajwani! We are about to migrate to the latest Onfido and Swift 4.2 :) So I believe all will be good! 👍
