### ISSUE TITLE
Cannot find Onfido objects after xcode update to 10.0

### ISSUE THREAD

**Issue by stshelton** [onfido/onfido-ios-sdk#50]
After updating Xcode to 10.0 all Onfido objects are erroring with "Use of unresolved identifier 'OnfidoConfig or 'OnfidoFlow''". Umm, I tried cleaning and rebuilding also made sure I'm importing Onfido. My Swift version is 4.0 and moved it up to 4.2 and tried to rebuild but received the same error. Any ideas on why it may not be building? 

- Onfido SDK: 10.0
- Xcode: 10.0

**Comment by stshelton** [comment]
Device, Deployment target 10.1, pod ' ondfido-release'. Sorry should have added from start will fill form fully out in future.

**Comment by stshelton** [comment]
Yea, I thought I was building for a device but my USB port isn't working correctly and I was still on the simulator. That was definitely the problem, using "onfido-release' and trying to build on the simulator. Sorry again for not filling the full thing out, your questions help me see the obvious answer anyway. So thanks!

**Comment by lucaspelloni2** [comment]
Thank @stshelton ! I was doing the same.
