### ISSUE TITLE
Missing key in Localizable.strings

### ISSUE THREAD

**Issue by atmamont** [onfido/onfido-ios-sdk#51]
There is a missing key in Localisation.strings
`onfido_message_check_readability_title` (**Check readability** in UI)
I've managed to guess the right naming and it worked.
Please add it to the repository.

**Comment by Gorbyy** [comment]
Hi Andrey,
Thanks for reporting this. We will fix it as soon as possible.
Cheers

**Comment by anuragajwani** [comment]
Hi @atmamont 

Closing this issue as this key no longer exists and Localizable.strings file gets updated on each release.

Anurag
