### ISSUE TITLE
Selfie screen label under button

### ISSUE THREAD

**Issue by lukas-tgo** [onfido/onfido-ios-sdk#54]
Selfie screen should look normal.
Instead selfie view has a UILabel which gets under a button on iPhone 7+.

- Cocoapods: Onfido 10.0.0
- Onfido SDK Debug
- iOS: 11
- Xcode: 10
- Device: iPhone 7+ 
- Device/Simulator language: English

Just try to verify id, take a selfie on a plus size device.

![image from ios 1](https://user-images.githubusercontent.com/30406165/48763986-23e23e00-ecb7-11e8-84e5-735b31ed754c.png)
![image from ios 2](https://user-images.githubusercontent.com/30406165/48763988-247ad480-ecb7-11e8-868b-90fe8310c2a7.png)

**Comment by anuragajwani** [comment]
Hi @lukas-tgo,

Thanks for reporting it. We will look into it as soon as possible.

Thanks
Anurag

**Comment by bartzet** [comment]
Hey @lukas-tgo. Just to let you know, we did the release of version 10.1.0 yesterday. Since the issue you reported was while our release was in progress, we were not able to include a fix for it. Hopefully, we will be able to do so in the next one.

Thanks,
Bart

**Comment by keremgund** [comment]
Hi @lukas-tgo , I confirmed that our latest SDK version (which is currently 11.1.1) has already fix for this issue. Could please upgrade your SDK and confirm that the issue has been fixed ?

Thanks,
Kerem

**Comment by anuragajwani** [comment]
closing due to lack of response
