### ISSUE TITLE
Machine Code vs Bitcode

### ISSUE THREAD

**Issue by mwawrusch** [onfido/onfido-ios-sdk#56]
### What was the expected behaviour?

The app should upload to the app store

### What happened instead?

"Invalid Mach-O Format. The Mach-O in bundle "OneClickICO.app/Frameworks/Onfido.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(bitcode) and arm64(bitcode), while the nested bundle Mach-O contains armv7(machine code) and arm64(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting.
### Version info:

- Cocoapods (if applicable):
- Onfido SDK (Debug/Release): release
- iOS: 10.0 + 
- Xcode: latest
- Device/Simulator:
- Device/Simulator language:

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

### Steps to reproduce:

Include onfido into a project using cocoapods

**Comment by ramprasad-parajuli** [comment]
Hi Martin, Thank you for reaching out with the issue.

After speaking to our SDK engineers, I am able to confirm some points for you. Onfido does support Bitcode. We actively contacted other clients using bitcode but have not found issues.

We did some research on Apple's website and found that support for bitcode is compulsory, hopefully this does not impact the release of your app.

Also, I see that you have included 'Onfido' into a project using cocoapods. could you please replace pod 'Onfido' with the following lines?

use_frameworks!
pod 'Onfido', '10.0.0', :configurations => ['Debug']
pod 'Onfido-Release', '10.0.0', :configurations => ['Release']

Can you please let us know if this solves the issue? I will update you once I have more information from our SDK Team on the issue.

**Comment by mwawrusch** [comment]
Looks like it works, thx.
