### ISSUE TITLE
pod install resulting in 'include of non-modular header...'  | Xcode 10.1

### ISSUE THREAD

**Issue by sree127** [onfido/onfido-ios-sdk#62]
### What was the expected behaviour?

Build the project after `pod install` without any conflicts

### What happened instead?

After `pod install` the `Onfido.h` threw the below error:
`Include of non-modular header inside framework module`

![Error](https://user-images.githubusercontent.com/3157263/50586569-45b80e80-0e7a-11e9-8222-358d61415bde.png)

### Version info:

- Cocoapods: 1.53
- Onfido SDK (Debug): 10.1.0
- iOS: 12.1
- Xcode: 10.1

### Integration configuration:

We use pod static frameworks and is configured as below: 

#### Podfile

`pod 'Onfido', :modular_headers => true`

I can remove the error by replacing the header in `Onfido.h`: 

`#import <Onfido/GlareDetection.h>`  to `#import "GlareDetection.h"`

It'd be nice if there is a stable solution for this as we have to manually update the `Onfido.h` every time we do a `pod install`

**Comment by sree127** [comment]
I see. Thanks @anuragajwani. I think we'll fork it to include the changes :)

**Comment by anuragajwani** [comment]
@sree127 what changes are you looking for? We don't publish the source code of the SDK and deliver a compiled iOS dynamic framework through Cocoapods. If you are looking for statically built Onfido SDK it will have to happen on our side.

It would be helpful to us to understand your requirements.

Anurag

**Comment by anuragajwani** [comment]
so you can use `:modular_headers => true` in Cocoapods ?

**Comment by sree127** [comment]
Tried with `:modular_headers => true` and doesn't work :(

**Comment by anuragajwani** [comment]
@sree127 I am still trying to understand what you are trying to achieve with these changes. Is there anything you can tell me about your high level objective with these changes?

**Comment by warrioru** [comment]
Hey. Any update on this? I'm getting the same error and we can't use `use_frameworks!` because the latest version of React Native 0.60 doesn't allow it.

**Comment by jamesjara** [comment]
Having the same issue
