### ISSUE TITLE
Version 10.1.0 has been built using a pre-release version of Xcode

### ISSUE THREAD

**Issue by AndreasVerhoeven** [onfido/onfido-ios-sdk#65]
Using the pre-build Onfido framework 10.1.0 from the releases page in our app, we get an upload rejection from Apple mentioning the Onfido framework specifically. 

Unfortunately, Onfido 10.1.0 has been build using a **prerelease** build of Xcode, namely 10 GM Seed 1 (10A254a) as one can see in the framework's Info.plist. The actual release version of Xcode 10 is  10A255.  Apple does not allow binaries to be submitted build with pre-release versions of Xcode, so iTunes Connect rejects our app.

### What was the expected behaviour?
We can happily use the prebuild 10.1.0 Onfido framework in our app and submit it to iTunes Connect.

### What happened instead?
Using the pre-build Onfido framework 10.1.0 from the releases page in our app, we get an upload rejection from Apple mentioning the Onfido framework specifically.

### Version info:
- Onfido SDK (Debug/Release): Release 10.1.0 (prebuild)
- iOS: 12.1
- Xcode: 10.1 (latest)
- Device/Simulator: N/A
- Device/Simulator language: N/A

### Integration configuration:
N/A
### Steps to reproduce:
- Use the prebuild 10.1.0 framework from the releases page
- Submit an app with this framework to iTunes Connect
- Get an error from Apple about the Onfido framework

**Comment by anuragajwani** [comment]
Hi @AndreasVerhoeven 

We are in the middle of a new release. We are now using Xcode 10.1.

Anurag

**Comment by AndreasVerhoeven** [comment]
@anuragajwani is there an ETA for the new release? The current version is blocking us from submitting our app to Apple and rolling back to the previous version isn't possible, because we just upgraded to Xcode 10

**Comment by anuragajwani** [comment]
@AndreasVerhoeven we have already pushed Onfido 10.2.0 to Cocoapods though not published the changelog. We are publishing the changelogs now.

**Comment by AndreasVerhoeven** [comment]
@anuragajwani thanks for the quick resolution! Issue seems resolved, we were able to upload to iTunes Connect with 10.2.0!
