### ISSUE TITLE
Can't build on Xcode 10.2

### ISSUE THREAD

**Issue by mkelley64** [onfido/onfido-ios-sdk#69]
Do you have plans to release an Xcode 10.2/Swift 5 compatible version soon?  We would like to validate our app's readiness for the next release, but currently the Onfido pod generates the following error:

"Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler"

Hopefully with the arrival of ABI stability this will not be an issue in the future.

**Comment by anuragajwani** [comment]
@mkelley64 we plan to support Xcode 10.2 once it is out of beta. Looking forward to ABI stability, however some changes are still required to be fully ABI stable https://swift.org/abi-stability/

Anurag

**Comment by borut-t** [comment]
Xcode 20.1 is [out](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes). When can we expect compatibility release?

**Comment by davideme** [comment]
@anuragajwani we are actively developing an app and would like to know the ETA for XCode 10.2

**Comment by anuragajwani** [comment]
@davideme please follow the issue https://github.com/onfido/onfido-ios-sdk/issues/77. I will update that issue as we progress along the release cycle.

Anurag

**Comment by anuragajwani** [comment]
iOS SDK 11.0.0 which is Xcode 10.2 compatible has been released.

Anurag
