### ISSUE TITLE
Podfile for sample app contains an error

### ISSUE THREAD

**Issue by dim-bon** [onfido/onfido-ios-sdk#7]
Hi, I've spend some time trying to figure out why I was getting this error:
`[!] Unable to satisfy the following requirements:

- `Onfido (= 2.0.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Onfido (= 2.0.0)`.
`
So, it turned out that this line in podfile: pod 'Onfido', '2.0.0'
needs to be replaced with this one: pod 'Onfido'
After this change, pods installed correctly with Onfido version 2.0.1

**Comment by anuragajwani** [comment]
@dim-bon Thanks for pointing it out, we did not end up releasing version 2.0.0 and jumped straight into 2.0.1. Please find it corrected now. As you pointed out pod 'Onfido' will get you the latest version of the pod. To ensure not getting unwillingly a pod with a breaking API change that can break your application please use the optimistic operator `~>`. In your case `~> 2.0`. This will update your pod with the latest features and bug fixes (up to but not including version 3.0).

We use Semantic Versioning as specified in the Cocoapods guideline. For more info please check out cocoapods documentation: https://guides.cocoapods.org/using/the-podfile.html.
