### ISSUE TITLE
How can i change Localization on run time using withCustomLocalization()

### ISSUE THREAD

**Issue by satishprasad30** [onfido/onfido-ios-sdk#70]
###How can i change Localization on run time using withCustomLocalization()
 how to change localization on run time, suppose current locale is English, but wanted to change it other(ex: Arabic). 

Was passing other language strings file in the param of withCustomLocalization()
but not working.

### What happened instead?

Please detail what was the actual behaviour

### Version info:

- Cocoapods (if applicable):
- Onfido SDK (Debug/Release):
- iOS:
- Xcode:
- Device/Simulator:
- Device/Simulator language:

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

### Steps to reproduce:

Please describe in as much detail as possible on how to reproduce the problem

**Comment by anuragajwani** [comment]
@satishprasad30 the sdk only works with Localized files. First your app must support Arabic. Next create a strings file called `Localizable.strings`. Then make sure the file is localised within Xcode.
![screen shot 2019-02-26 at 10 34 14](https://user-images.githubusercontent.com/7071488/53406781-93e91a00-39b2-11e9-87a9-c4a1f9e66e22.png)
![screen shot 2019-02-26 at 10 34 48](https://user-images.githubusercontent.com/7071488/53406782-93e91a00-39b2-11e9-85ca-036e817e14c4.png)
![screen shot 2019-02-26 at 10 35 10](https://user-images.githubusercontent.com/7071488/53406783-93e91a00-39b2-11e9-8165-c0e49b63bbc4.png)
After make sure you call `withCustomLocalization()` and thats it.

See images above, make sure you are follow standard iOS localisation.

Anurag
