### ISSUE TITLE
Initial SDK screen presentation isn't smooth

### ISSUE THREAD

**Issue by iangmaia** [onfido/onfido-ios-sdk#74]
### What was the expected behaviour?

The Onfido modal screen should be shown smoothly and then, once it's presented, the SDK can enable the camera / ask for camera permission.

### What happened instead?

The modal presentation "stutters" and looks very sluggish, presumably because of enabling the camera / asking for permission during the modal presentation.

### Version info:

- Onfido SDK (Debug/Release): Debug 10.4.0

### Steps to reproduce:

Just present modally the Onfido ViewController provided by the SDK.

**Comment by anuragajwani** [comment]
what's your configuration?

Anurag

**Comment by iangmaia** [comment]
It's a simple configuration for document scan, nothing special there I guess:

```
let configBuilder = OnfidoConfig.builder()
  .withToken(self.credentials.token)
  .withApplicantId(self.applicantId)
  .withCustomLocalization(andTableName: "OnfidoLocalizable")
  .withAppearance(Appearance()) //custom fonts and colors
  .withDocumentStep(ofType: -, andCountryCode: "") //we've been using mostly passport and nationalIdentityCard

let flow = OnfidoFlow(withConfiguration: self.onfidoConfig)
let captureViewController = try flow.run()
self.viewController.present(captureViewController, animated: animated, completion: nil)
```

The problem seems to be, as I mentioned, that the camera seems to be accessed (and even the permission requested) *during* the presentation of the Onfido ViewController, which will of course block the UI for a few milliseconds.
I can work around that by creating a separate container view controller to be presented and then just delay the presentation of the Onfido VC until the container animation is finished, but I guess this should be fixed on the SDK side.

Thanks,
Ian

**Comment by anuragajwani** [comment]
Thanks for sending over your configuration. We will investigate and get back to you.

Anurag

**Comment by iangmaia** [comment]
Another point I noticed: the background while presenting the Onfido ViewController is transparent, and this is one of the main problems that make the transition look so bad. Setting a solid color (e.g. `UIColor.black`) for the VC background improved a lot the presentation already.

Setting a solid color for the VC doesn't work, though, for the selfie screen since it is now presented after an initial introduction (that seems to be mandatory -- I've created another issue to make it optional).

![onfido transition](https://user-images.githubusercontent.com/2152244/57066565-cd991280-6ccc-11e9-80b7-9e591084ce90.gif)

**Comment by anuragajwani** [comment]
Hi @iangmaia,

Sorry for the late reply. We have a task for this in the backlog. This bug is reproduceable. I missed updating this issue.

Anurag

**Comment by thomassenkman** [comment]
Hello @anuragajwani,

We got the same issue that @iangmaia described in his last message here, when presenting modally the Onfido Controller with v13.0.0. Any news on this? Maybe you want me to create a new specific issue?

Thanks

**Comment by anuragajwani** [comment]
Hi @thomassenkman  & @iangmaia,

We have made improvements to our capture screens in our latest version. Do you still encounter this problem on the latest? (16.0.0?).

Anurag

**Comment by iangmaia** [comment]
I'll check and let you know @anuragajwani

**Comment by keremgund** [comment]
Closing the issue due to lack of response. Please open new one of you need further support.

Thanks,
Kerem
