### ISSUE TITLE
Do not display "No document found" error when testing in Sandbox environment

### ISSUE THREAD

**Issue by arielelkin** [onfido/onfido-ios-sdk#75]
### What was the expected behaviour?
Given that Onfido's sandbox environment returns pre-determined responses, an `OnfidoFlow` made against a sandbox environment should not check whether or not a captured image contains a real document.

### What happened instead?
![IMG_4973](https://user-images.githubusercontent.com/1756909/54351740-08c18280-4648-11e9-92f7-1bc1854418a7.png)

### Version info:
- Onfido SDK (Debug/Release):
10.2.0

**Comment by sonic555gr** [comment]
👍 +1

**Comment by seewah** [comment]
hi thanks for your feedback, is your primary concern that you do not want to have to use an id document during development and testing?

**Comment by arielelkin** [comment]
@seewah correct.

**Comment by sonic555gr** [comment]
@seewah Sandboxing, wether on device or simulator shouldn't really require to capture anything and it should always succeed given that the responses are pre-determined.

**Comment by seewah** [comment]
thanks for the feedback. We will add this to the backlog for future consideration. While i fully understand your challenge, accommodating this will lead to some complexity on our side, and we will discuss internally to explore options and also keep an eye out for similar feedback from others.

**Comment by seewah** [comment]
Hi we are closing this ticket for now. After some internal discussion, we have decided to keep the existing behaviour. The reason is that the majority of our customers still want to be able to experience the full set of SDK user experience, including validation feedback, when using the sandbox token during integration.
