### ISSUE TITLE
Cannot build Onfido with Swift 4.2 after XCode Update to 10.2 (10E125) 

### ISSUE THREAD

**Issue by kuzdu** [onfido/onfido-ios-sdk#77]
I updated XCode to the newest version 10.2 (10E125) which include Swift 5.0 support. 

Compiling does not work.

`Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler: /Users/my-name/myapp/Pods/Onfido/Onfido.framework/Modules/Onfido.swiftmodule/x86_64.swiftmodule
`

I use `Onfido 10.6.0` and set the pod build settings to Swift 4.2, Swift 4.0 and Swift 5. I always got the same error.

### Version info:
- Cocoapods (if applicable): 1.4.0
- Onfido SDK (Debug/Release): Release, 10.6.0
- iOS: 11.4 and 12.4
- Xcode: XCode 10.2 (10E125) 
- Device/Simulator: All 
- Device/Simulator language: englisch

**Comment by Maninder1991** [comment]
Yes, same issue happening with my code. My code is not getting compile. Please share ETA when we can expect new version of SDK.

**Comment by jlew-nevo** [comment]
Ditto

**Comment by timt** [comment]
Ditto

**Comment by JackieQi** [comment]
Ditto

**Comment by anuragajwani** [comment]
Hey all,

We have started the release process for Onfido iOS SDK version 11.0.0 which will be compatible with Xcode 10.2. We are aiming to have it released by the end of the week.

Sorry for the inconvenience,
Anurag

**Comment by capitanomikejobs** [comment]
@anuragajwani any news ?

> Hey all,
> 
> We have started the release process for Onfido iOS SDK version 11.0.0 which will be compatible with Xcode 10.2. We are aiming to have it released by the end of the week.
> 
> Sorry for the inconvenience,
> Anurag

any news?

**Comment by anuragajwani** [comment]
We are now running tests to ensure all functionality is working as expected when the SDK is built using Xcode 10.2. We are aiming for a release on Monday.

Sorry for the inconvenience,
Anurag

**Comment by Pikorua** [comment]
Any chances to get a beta build so we can actually keep on preparing the release when you have it out?

**Comment by louy** [comment]
I've also hit this issue yesterday. I think it'd be nice to say in the release notes which version of swift is the framework built with :)

**Comment by anuragajwani** [comment]
Hi all,

We have release iOS SDK 11.0.0 which is Xcode 10.2 compatible. Please let me know if you encounter any problems or whether I can close this task.

Anurag

**Comment by danieldelouya** [comment]
Getting lldb crash "Swift class extensions and categories on Swift classes are not allowed to have +load methods" right when the app starts running

**Comment by ciumexan** [comment]
hmm.. i get the same error here. 
Xcode Version 10.2 (10E125)

**Comment by ciumexan** [comment]
> Hi all,
> 
> We have release iOS SDK 11.0.0 which is Xcode 10.2 compatible. Please let me know if you encounter any problems.
> 
> Anurag
Do we need to compile the mod. separately and import it ?  It looks like is still there. 
SWIFT_VERSION in sampleApp is set to 3.
Thanks.

**Comment by anuragajwani** [comment]
@ciumexan first make sure you are using Onfido SDK 11.0.0. If you previously installed another version your Podfile.lock will be set to the previous version. Also make sure your public cocoapods specs repo in your Mac is in sync with the one in GitHub (to update `pod repo update`). When you run `pod install` make the log prints out that your using Onfido SDK `11.0.0`. Checkout the Cocoapods documentation on how to use Cocoapods.

Anurag

**Comment by anuragajwani** [comment]
@ciumexan thank you for pointing out the SampleApp issue. We will fix it in the next release.

**Comment by ciumexan** [comment]
ok, so fixed with a `pod update`. thanks @anuragajwani 
Analyzing dependencies
Downloading dependencies
Installing Onfido 11.0.0 (was 10.5.0 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing Onfido-Release 11.0.0 (was 10.5.0 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Generating Pods project

**Comment by anuragajwani** [comment]
no worries @ciumexan, glad I could help
