### ISSUE TITLE
Sample app crashes on Simulator

### ISSUE THREAD

**Issue by dim-bon** [onfido/onfido-ios-sdk#8]
Hi
I'm getting a crash while trying to use sample app on the Simulator. I hit "Verify me!" button, then allow for camera access, the action sheet pops up for a short time and then it crashes with no meaningful stacktrace, just this:
'fatal error: unexpectedly found nil while unwrapping an Optional value'

Yes, I understand that this situation with Simulator and Camera can be viewed as not real-world situation but still it would be nice if the framework would handle it gracefully and wouldn't show such a crasher. Also, worth considering, that this crasher could appear on an actual device on some conditions.

**Comment by anuragajwani** [comment]
@dim-bon yes you are right. We currently do not support Simulators given that the SDK requires camera access. We will work to get the messaging and support around that issue better.

We have tested it quite well on devices and have found no issue yet. Would you be able to gives us an example of a condition that we can reproduce on devices that this crash could appear on?

**Comment by dim-bon** [comment]
Ok, then
I don't have an example of a condition, it's just an assumption that there might be one, due to the nature of the crash

**Comment by anuragajwani** [comment]
@dim-bon we have now addressed the issue. The SDK will throw OnfidoFlowError.deviceHasNoCamera error on simulators in version `2.0.2`.
