### ISSUE TITLE
Can not build Onfido 11.0.0 on physical device

### ISSUE THREAD

**Issue by markotl88** [onfido/onfido-ios-sdk#82]
I was not able to build Onfido 11.0.0 on physical device using both Xcode 10.1 and 10.2, in Objective C project. I even tried with the sample app - SampleAppObjC, but still with no success. As soon as I switch build target from simulator to device Xcode throws the error - **Use of undeclared identifier 'ONFlowConfigBuilder'**, it looks like it doesn't see anything from _Onfido-Swift.h_ file. Building on simulator is successfully completed every time.

**Comment by anuragajwani** [comment]
Hi @markotl88 

Thanks for reporting the issue, we will look into this and get back to you.

Anurag

**Comment by anuragajwani** [comment]
@markotl88 I might have found the issue causing this. It looks like this is a known issue in Xcode 10.2. Check out this part from the [release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes):

```
Known Issues
If you're building a framework containing Swift code and using lipo to create a binary that supports both device and simulator platforms, you must also combine the generated Framework-Swift.h headers for each platform to create a header that supports both device and simulator platforms. (48635615)
```

We will be testing out whether this is in fact the culprit tomorrow an update you with any news.

Sorry for the inconvenience,
Anurag

**Comment by anuragajwani** [comment]
@markotl88 we have release iOS SDK 11.0.1 with a patch for this problem. Please upgrade to the latest and let me know if you encounter any issues.

Sorry for the inconvenience,
Anurag

**Comment by markotl88** [comment]
@anuragajwani Thanks for the quick reaction. Latest version works as expected!

**Comment by amlord** [comment]
@anuragajwani I'm seeing this issue, but have followed the _manual_ release steps, will you be updating the github releases tab (https://github.com/onfido/onfido-ios-sdk/releases) with v11.0.1, or can i get a link to it from somewhere else? Thanks...

**Comment by anuragajwani** [comment]
@amlord sorry I haven't uploaded 11.0.1 to the GitHub releases. Doing it now.

**Comment by anuragajwani** [comment]
@amlord uploaded 11.0.1 to GitHub releases

**Comment by amlord** [comment]
Brilliant, i can see it there now - thanks for the speedy response @anuragajwani ! 👍

**Comment by anuragajwani** [comment]
glad I could help
