### ISSUE TITLE
App crash in landscape only mode

### ISSUE THREAD

**Issue by hdongre-techracers** [onfido/onfido-ios-sdk#83]
### What was the expected behaviour?
My application support landscape orientation only. It should work in landscape only mode.

### What happened instead?
When I use onfido iOS SDK then after taking document picture app crashes.

'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [UIAlertController shouldAutorotate] is returning YES'

### Version info:

- Cocoapods (if applicable): 
- Onfido SDK (Debug/Release): Debug
- iOS: 11
- Xcode: 10.1
- Device/Simulator: iPhone 7
- Device/Simulator language:

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

### Steps to reproduce:

Please describe in as much detail as possible on how to reproduce the problem

**Comment by anuragajwani** [comment]
Hi @hdongre-techracers,

Thanks for raising the issue. We will investigate and get back to you.

Sorry for the late reply,
Anurag

**Comment by keremgund** [comment]
Hi @hdongre-techracers , I want to inform you that we're able to reproduce the issue and working on the fix now. I will let you know once we released the fix.

Thanks,
Kerem

**Comment by hdongre-techracers** [comment]
Hi Kerem,

Any updates on the following.

Thanks,
Harshit

**Comment by keremgund** [comment]
Hi @hdongre-techracers,

First of all, sorry for the late reply. I'm glad to say that we were able to fix this issue and aim to deliver it in our next release. Once it's released, I will inform you.

Thanks,
Kerem

**Comment by hdongre-techracers** [comment]
Hi Keremgund,

I am glad that you guys have resolved the issue. Only thing that I am
worried about is our product launch date. It is going to be launch in first
week of July.
So could you please give me a rough estimation about your release. It will
be great help if you guys can provide it in first week of July.

Thanks,
Harshit

**Comment by keremgund** [comment]
Hi @hdongre-techracers ,
We're aiming mid July to release new version. I'll inform you once we released.

Thanks,
Kerem

**Comment by keremgund** [comment]
Hi @hd , we just released new version which includes fix for this issue. You can check out 12.2.0 version from https://github.com/onfido/onfido-ios-sdk/releases/tag/12.2.0

Thanks,
Kerem

**Comment by hdongre-techracers** [comment]
Hi Keremgund,

Thank you very much for your support. I really appreciate and admire your
work as you took care of our deliverables.
Great job guys.

Thanks,
Harshit

**Comment by keremgund** [comment]
Closing the issue. Please open new one if you see the issue still exists.
