### ISSUE TITLE
Could not find module 'Onfido' for architecture 'x86_64'; found: arm64, arm, armv7

### ISSUE THREAD

**Issue by ifero** [onfido/onfido-ios-sdk#84]
### What was the expected behaviour?
Build app without problems in a simulator

### What happened instead?
Build fails to complete because:
Could not find module 'Onfido' for architecture 'x86_64'; found: arm64, arm, armv7
in `import Onfido`

### Version info:

- Cocoapods (if applicable): 
- Onfido SDK (Debug/Release): 11.0.1 Debug / Release
- iOS: 12.2
- Xcode: 10.2 (10E125)
- Device/Simulator: Simulator iPhoneX 12.2
- Device/Simulator language:

### Integration configuration:

added Onfido.framework in my Embedded Binaries list and created the wrapper to open Onfido in react-native.

### Steps to reproduce:

Try to build to target device as simulator.

**Comment by anuragajwani** [comment]
@ifero which one are you using Debug or Release? you can run the Onfido SDK on simulators on Debug but not on Release. By the looks of this error you are using the Release SDK.

Anurag

**Comment by ifero** [comment]
@anuragajwani 
First of all thanks for the quick reply.
I've worked only with Debug version.

**Comment by ifero** [comment]
Nevermind, I had import issues. sorry about that.

**Comment by raghurammahathi** [comment]
Could not find module 'VdoCipherKit' for architecture 'x86_64'; found: arm64

please help me with the import issues
 thanks
