### ISSUE TITLE
App crash when re-select document type after deny camera permission

### ISSUE THREAD

**Issue by capitanomikejobs** [onfido/onfido-ios-sdk#86]
### What was the expected behaviour?
Handle the error

### What happened instead?
App crash with this error message:

Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use Back Camera" UserInfo={NSLocalizedFailureReason=This app is not authorized to use Back Camera., AVErrorDeviceKey=<AVCaptureFigVideoDevice: 0x108f2d600 [Back Camera][com.apple.avfoundation.avcapturedevice.built-in_video:0]>, NSLocalizedDescription=Cannot use Back Camera}: file /Users/anurag.ajwani/workspace/onfido/ios/sdk/SDK/Source/Scenes/CameraCapture/CameraLayerImpl.swift, line 243

### Version info:
- Onfido SDK (Debug/Release): Onfido (11.0.1)
- iOS: 12.2
- Xcode: 10.2 (10E125)
- Device/Simulator: iPhone XR
- Device/Simulator language: EN

### Steps to reproduce:
1) Run Onfido Sdk
2) Select document type
3) Deny Camera permission
4) Go back in "Select your document"
5) Select a document
6) App crash

**Comment by anuragajwani** [comment]
Hi @capitanomikejobs 

Thanks for raising this issue. This issue might be related to another one for which we have already implemented and is currently being prepared to release. We will get back to you when we have more information.

Thanks,
Anurag

**Comment by capitanomikejobs** [comment]
> Hi @capitanomikejobs
> 
> Thanks for raising this issue. This issue might be related to another one for which we have already implemented and is currently being prepared to release. We will get back to you when we have more information.
> 
> Thanks,
> Anurag

any news?

**Comment by anuragajwani** [comment]
@capitanomikejobs we are in the release process already. We are aiming to have 11.1.0 released by early next week. It includes new camera/microphone permission screens and manages permissions altogether differently. I have been busy preparing the release so I haven't tested this issue out yet. However I have allocated time to test it tomorrow.

Sorry for the delay and the inconvenience,
Anurag

**Comment by anuragajwani** [comment]
Hi @capitanomikejobs,

We have been able to reproduce this bug and can also confirm its fixed in 11.1.0.

Anurag

**Comment by anuragajwani** [comment]
Closing issue as no response provided. I assume that `11.1.x` fixed your issue.
