### ISSUE TITLE
SDK Fails after photo step by hitting unreachable URL

### ISSUE THREAD

**Issue by dancarls0n** [onfido/onfido-ios-sdk#87]
### What was the expected behaviour?

Move past the take photo stage.

### What happened instead?

OnFidoFlow response handler called with error.

Onfido.OnfidoFlowError.exception(withError: Optional(Error Domain=NSURLErrorDomain Code=-1003 \"A server with the specified hostname could not be found.\" UserInfo={NSUnderlyingError=0x283311cb0 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 \"(null)\" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, NSErrorFailingURLStringKey=https://api.ios.onfido.com/v2/documents, NSErrorFailingURLKey=https://api.ios.onfido.com/v2/documents, _kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, NSLocalizedDescription=A server with the specified hostname could not be found.}), withMessage: nil)

### Version info:

- Cocoapods (if applicable): 11.0.0
- Onfido SDK (Debug/Release): (tried both pods, both present the same url)
- iOS: 12
- Xcode: 10.2.1
- Device/Simulator: iphone 6s
- Device/Simulator language: English-us?

### Integration configuration:
            .withToken("token")
            .withApplicantId(applicant)
            .withDocumentStep()
            .withFaceStep(ofVariant: .photo)
            .withAppearance(appearance)
            .build()

### Steps to reproduce:

happens every time after I confirm my photo

**Comment by anuragajwani** [comment]
@dancarls0n have you tested through other means (not using the SDK) that the token is valid?

**Comment by dancarls0n** [comment]
I don't believe it validates the token at all. https://api.ios.onfido.com/v2/documents doesn't seem to be a real url.

**Comment by anuragajwani** [comment]
@dancarls0n part of the url is composed by the token, if the token is wrong it could lead to the url being incorrect

**Comment by dancarls0n** [comment]
It could lead to the domain being completely wrong? Try and navigate to https://api.ios.onfido.com/v2/documents in your browser. Are you able to hit that on the public internet?

**Comment by anuragajwani** [comment]
the `.ios` part is being injected based on the token.  `https://api.ios.onfido.com/` is in fact incorrect as you pointed but that url is composed from different parts. It looks like your token has `ios` somewhere inside of it. Which leads me to believe that the token is incorrect.

The url is something like `https://api[SOME_VARIABLE_BASED_ON_THE_TOKEN].onfido.com/`. If the token is incorrect it can lead to the url being incorrect.

**Comment by dancarls0n** [comment]
Thanks very much for your followup answer. I was using the wrong key to lookup the token from a plist. The (wrong token) it was erroneously returning happened to start with "ios". Thanks very much for your help and sorry for my confusion.

**Comment by anuragajwani** [comment]
No worries
