### ISSUE TITLE
Release Pod was built without full bitcode

### ISSUE THREAD

**Issue by novemberborn** [onfido/onfido-ios-sdk#89]
### What was the expected behaviour?

I can archive my app.

### What happened instead?

An error occurred.

### Version info:

- Cocoapods (if applicable):
- Onfido SDK (Debug/Release): 11.1.0
- iOS:
- Xcode: 10.2.1
- Device/Simulator:
- Device/Simulator language:

### Integration configuration:

N/A

### Steps to reproduce:

I've installed the 11.1.0 pod. It's selected for the Release scheme. When I archive my app, I get the following build error:

> bitcode bundle could not be generated because '/path/to/app/Pods/Onfido-Release/Onfido.framework/Onfido' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/path/to/app/Pods/Onfido-Release/Onfido.framework/Onfido' for architecture arm64

It works when I revert to 11.0.0.

**Comment by anuragajwani** [comment]
Hi @novemberborn,

Thanks for raising the issue. We can confirm that bitcode is missing.

Anurag

**Comment by anuragajwani** [comment]
@novemberborn we are issuing a fix for this. I will update you when we have released it.

Anurag

**Comment by anuragajwani** [comment]
Hi @novemberborn 

We have release iOS SDK 11.1.1 with full bitcode now. Please let me know if this fixes your problem.

Sorry for the inconvenience,
Anurag

**Comment by novemberborn** [comment]
Archiving the app works with 11.1.1, thanks @anuragajwani!
