### ISSUE TITLE
Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1

### ISSUE THREAD

**Issue by AshleyRudland** [onfido/onfido-ios-sdk#9]
Hey @tpinto & @anuragajwani!

We've recently updated to xcode 8.3 and it's broken our build process. Unfortunately the new update (to xcode) has caused any dependencies built in older version of Swift to fail.

The error received on build is `module compiled with Swift 3.0.2 cannot be imported in Swift 3.1: Pods/Onfido/Onfido.framework/Modules/Onfido.swiftmodule/x86_64.swiftmodule`.

We did try to build with Swift 3.0.2 toolchain (on xcode 8.3) but received runtime errors such as `Reason: Incompatible library version: Onfido requires version 1.0.0 or later, but libswiftAVFoundation.dylib provides version 0.0.0`. Thus we didn't try further.

If this repo was open source we'd be more than happy to contribute to it, I'm pretty sure Onfido's IP is held within it's backend infrastructure not front end UI.

Could you release a new version compiled with Swift 3.1 please?

Thanks!
Ash.

**Comment by anuragajwani** [comment]
@AshleyRudland We're looking into this as priority. Thanks for raising the issue 🙂.

**Comment by anuragajwani** [comment]
@AshleyRudland version 2.0.3 has been pushed to cocoapods build with Swift 3.1. Lets hope Swift 4 becomes binary compatible 🤞🏽

**Comment by AshleyRudland** [comment]
@anuragajwani thank you!
