### ISSUE TITLE
Selfie Intro not optional?

### ISSUE THREAD

**Issue by iangmaia** [onfido/onfido-ios-sdk#91]
### What was the expected behaviour?

Selfie intro screen should be optional. We (and I suppose other companies would also like to) have our own introduction for it.

### What happened instead?

Haven't seen in the API to not show it.

### Version info:

- Onfido SDK 10.6.0

**Comment by seewah** [comment]
Hi thanks for the feedback

We will likely consider this going forward as we make our SDK more granular. However, for now, can i ask what is it about the selfie intro that you dislike? I am asking because our current selfie intro screen is based on the insights that we have gained from user testing and is designed to address some key user questions/concerns that we have noticed.

Thanks

See Wah

**Comment by iangmaia** [comment]
Hi @seewah . It's less about disliking the screen itself and more about providing our own information (and UI) about that step. I agree that the info there is important, but we'd rather have the option to provide that ourselves with our own info and UI.

Also, currently there's a glitch in the transition of the intro screen to the Live Selfie itself: I've provided a .gif with the problem in slow motion here: https://github.com/onfido/onfido-ios-sdk/issues/74#issuecomment-488607817

**Comment by atmamont** [comment]
Would be awesome to have an option to skip live selfie intro screen for photo mode.

**Comment by seewah** [comment]
Thanks for the feedback, and sorry for the delayed response. This idea is still in our backlog for future consideration, but given its relative impact, it is not something we will implement in the very near term I am afraid.

**Comment by anuragajwani** [comment]
Hi @atmamont, @iangmaia,

You can now disable selfie intro from [version 18.9.0](https://github.com/onfido/onfido-ios-sdk/blob/master/CHANGELOG.md#1890---2020-10-27).

Swift:
```
let config = try! OnfidoConfig.builder()
    ....
    .withFaceStep(ofVariant: .photo(withConfiguration: PhotoStepConfiguration(showSelfieIntroScreen: true)))  // specify the face capture variant here
    .build()
```

ObjC:
```
NSError *variantError = NULL;
Builder * variantBuilder = [ONFaceStepVariantConfig builder];
[variantBuilder withVideoCaptureWithConfig: [[VideoStepConfiguration alloc] initWithShowIntroVideo: YES]];
[configBuilder withFaceStepOfVariant: [variantBuilder buildAndReturnError: &variantError]];
```

Let me know if this solves your problem. Please close the issue if it does.
Anurag

**Comment by keremgund** [comment]
Closing the issue due to lack of response. If you need further support please open new one.

Thanks,
Kerem
