### ISSUE TITLE
Support Swift 5.0.1

### ISSUE THREAD

**Issue by iangmaia** [onfido/onfido-ios-sdk#92]
I guess this should be already coming up, but I'm creating an issue just in case since the last two versions are still 5.0.0.

**Comment by anuragajwani** [comment]
Hi @iangmaia,

I have tested out iOS SDK 11.1.1 using Xcode 10.2.1 and the SampleApp contained within this repo. I didn't get any build errors. Are you unable to build?

Anurag

**Comment by iangmaia** [comment]
I get `Incompatible Swift version - framework was built with 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) and the local version is 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5).`.

**Comment by anuragajwani** [comment]
Are you able to reproduce this with the SampleApp? Results:

```
➜  SampleApp git:(master) ✗ cat Podfile.lock
PODS:
  - Alamofire (4.8.2)
  - Onfido (11.1.1)
```

```
➜  SampleApp git:(master) ✗ xcodebuild -version
Xcode 10.2.1
Build version 10E1001
```

```
➜  SampleApp git:(master) ✗ xcodebuild -workspace SampleApp.xcworkspace -scheme SampleApp
...
** BUILD SUCCEEDED **
```

**Comment by keremgund** [comment]
Closing this issue due to lack of response, if you think there is still an issue about it, you can open new ticket.

Thanks,
Kerem
