### ISSUE TITLE
OnfidoSDK not loading on react-native

### ISSUE THREAD

**Issue by v-fernandez** [onfido/onfido-ios-sdk#94]
### What was the expected behaviour?

Load OnfidoSDK into react-native's NativeModules

### What happened instead?

OnfidoSDK not loaded.

### Version info:

- Cocoapods (if applicable): 
  * 1.6.1
- Onfido SDK (Debug/Release): 
  * Onfido (11.1.1)
  * Onfido-Release (11.1.1)
- iOS:
  * 12.2
- Xcode:
  * 10.2.1 (10E1001)
- Device/Simulator:
  * iPhone 8 Plus (12.2)
- Device/Simulator language:
- React Native
  * 0.59.4 

### Integration configuration:

Podfile

```
pod 'Onfido', :configurations => ['Debug']
pod 'Onfido-Release', :configurations => ['Release']
```

### Steps to reproduce:

Try call `NativeModules.OnfidoSDK.startSDK`, `NativeModules.OnfidoSDK` is null.

**Comment by dgobaud** [comment]
@anuragajwani can you look at this one please. this is now the new issue from #93 we still can't deploy :(

**Comment by v-fernandez** [comment]
The problem was that the needed swift file was not correctly added to the project. After adding it Onfido worked as expected.
