### ISSUE TITLE
Onfido 11.* crashes on earlier versions of iOS

### ISSUE THREAD

**Issue by markotl88** [onfido/onfido-ios-sdk#95]
We have a problem with apps built with Onfido 11.*, they can't be run on earlier versions of iOS. We had a problem with iOS 12.1 and 12.2 as well - both with debug and release versions. Application crashes on launch, with this message: 

<img width="538" alt="Screen Shot 2019-05-31 at 4 55 02 PM" src="https://user-images.githubusercontent.com/10500753/58714822-dfea9700-83c5-11e9-8b87-10cbd223977e.png">

**Comment by anuragajwani** [comment]
Hi @markotl88,

Make sure the option `Always Embed Swift Standard Libraries` is set to `Yes` in your app. Then delete your app. Wipe clean our derived data and run again.

Please try it out and let me know. I am unable to reproduce your issue with the given description.
Anurag

**Comment by compyman** [comment]
Hey we are also seeing this exact error and we do have that checkbox checked (we saw the error on our users from the crash reporter)

**Comment by mdesjardins** [comment]
Hi @anuragajwani 

We are experiencing a similar, if not identical issue. We have set the Always Embed Swift Standard Libraries flag to Yes as described:

<img width="971" alt="Screenshot 2019-06-04 11 09 52" src="https://user-images.githubusercontent.com/19634/58890791-508cfe80-86b9-11e9-8f90-59e57c983541.png">

Despite this, the app seems to crash immediately on startup - so far, the only devices I've encountered that have had the problem have been running iOS older than version 12.2, but I do not know for certain whether that is related.

Attached is a crash log:

[2019-06-03_06-37-47.9414_-0600-a5dc8ef993770b9de0a7b4fe5d1e4378ef419d81.txt](https://github.com/onfido/onfido-ios-sdk/files/3253142/2019-06-03_06-37-47.9414_-0600-a5dc8ef993770b9de0a7b4fe5d1e4378ef419d81.txt)

I looked at our archive directory to see what was included for dylibs, and `libswiftAVFoundationAV.dylib` is not there - I do know know if this is related:

    (remit) ~/Library/Developer/Xcode/Archives/2019-06-04/AppStore 6-4-19, 10.51 AM.xcarchive> find ./* -name "*dylib"
    ./Products/Applications/waveremit.app/Frameworks/libswiftCoreImage.dylib
    ./Products/Applications/waveremit.app/Frameworks/libswiftObjectiveC.dylib
    ./Products/Applications/waveremit.app/Frameworks/libswiftCore.dylib
    ./Products/Applications/waveremit.app/Frameworks/libswiftCoreGraphics.dylib
    ./Products/Applications/waveremit.app/Frameworks/libswiftUIKit.dylib
    ./Products/Applications/waveremit.app/Frameworks/libswiftMetal.dylib
    ./Products/Applications/waveremit.app/Frameworks/libswiftDispatch.dylib
    ./Products/Applications/waveremit.app/Frameworks/libswiftos.dylib
    ./Products/Applications/waveremit.app/Frameworks/libswiftCoreFoundation.dylib
    ./Products/Applications/waveremit.app/Frameworks/libswiftDarwin.dylib
    ./Products/Applications/waveremit.app/Frameworks/libswiftContacts.dylib
    ./Products/Applications/waveremit.app/Frameworks/libswiftQuartzCore.dylib
    ./Products/Applications/waveremit.app/Frameworks/libswiftAccelerate.dylib
    ./Products/Applications/waveremit.app/Frameworks/libswiftFoundation.dylib
    ./SwiftSupport/iphoneos/libswiftCoreImage.dylib
    ./SwiftSupport/iphoneos/libswiftObjectiveC.dylib
    ./SwiftSupport/iphoneos/libswiftCore.dylib
    ./SwiftSupport/iphoneos/libswiftCoreGraphics.dylib
    ./SwiftSupport/iphoneos/libswiftUIKit.dylib
    ./SwiftSupport/iphoneos/libswiftMetal.dylib
    ./SwiftSupport/iphoneos/libswiftDispatch.dylib
    ./SwiftSupport/iphoneos/libswiftos.dylib
    ./SwiftSupport/iphoneos/libswiftCoreFoundation.dylib
    ./SwiftSupport/iphoneos/libswiftDarwin.dylib
    ./SwiftSupport/iphoneos/libswiftContacts.dylib
    ./SwiftSupport/iphoneos/libswiftQuartzCore.dylib
    ./SwiftSupport/iphoneos/libswiftAccelerate.dylib
    ./SwiftSupport/iphoneos/libswiftFoundation.dylib

The Framework in the CocoaPod seems to be referencing the missing dylib:

    (remit) ~/_work/wave/src/remit-ios (dev *)> find ./* -type f -exec grep -Hi libswiftAVFoundation {} \;
    Binary file ./Pods/Onfido/Onfido.framework/Onfido matches
    Binary file ./Pods/Onfido-Release/Onfido.framework/Onfido matches
    (remit) ~/_work/wave/src/remit-ios (dev *)>

**Comment by mdesjardins** [comment]
@anuragajwani I am now able to reproduce this in an iPhone 8 simulator running iOS 11.1 with a Release build. It crashes in `dyld__abort_with_payload`

**Comment by mdesjardins** [comment]
@anuragajwani I was able to get this working again by downgrading the SDK from version 11.1.2 back to 11.0.1. After downgrading to 11.0.1, the app no longer crashes in my iOS 11.1 simulator, and `libswiftAVFoundation.dylib` is included in the archive.

**Comment by keremgund** [comment]
Hi @mdesjardins, I was able to test 11.1.2 SDK version with XCode 10.2.1 on iPhone 8 11.1 simulator successfully. 
As far as I understood from your previous comment, you tried to run release build on simulator which expected to doesn't work. You should use debug version of SDK to test it out on simulator. Can you share your podfile to understand how you integrated with SDK (assuming you're using cocoapod) ? 

Thanks,
Kerem

**Comment by markotl88** [comment]
> Hi @markotl88,
> 
> Make sure the option `Always Embed Swift Standard Libraries` is set to `Yes` in your app. Then delete your app. Wipe clean our derived data and run again.
> 
> Please try it out and let me know. I am unable to reproduce your issue with the given description.
> Anurag

@anuragajwani I can confirm that the `Always Embed Swift Standard Libraries` is set to `Yes`, in Build Settings/Build Options. I tried to clean the derived data folder, clean build folder, delete the app, but it's still the same.

**Comment by mdesjardins** [comment]
@keremgund I tried two different sets values in my Podfile, both the pre-11.1.x deprecated setup with a separate Releases pod:

    source 'https://github.com/CocoaPods/Specs.git'
    
    workspace 'waveremit.xcworkspace'
    project 'waveremit/waveremit.xcodeproj'
    
    platform :ios, '9.0'
    
    target :waveremit do
      pod 'AFNetworking', '~> 2.6.3'
      pod 'MCSwipeTableViewCell', '>= 2.1.2'
      pod 'Mixpanel', '~> 3.4'
      pod 'libPhoneNumber-iOS', '>= 0.7'
      pod 'FMDB', '>= 2.5'
      pod 'Stripe', '>= 1.0.2'
      pod 'Braintree', '>= 3.9.3'
      pod 'ActionSheetPicker-3.0', '>= 1.3.4'
      pod 'Rollbar', '~> 0.2.0'
      pod 'FBSDKCoreKit', '~> 4.33'
      pod 'BEMCheckBox'
      pod 'Onfido', '~> 11.1.2', :configurations => ['adhocstaging', 'debuglocal', 'debugstaging',     'adhocprod']
      pod 'Onfido-Release', '~> 11.1.2', :configurations => ['appstore']
      target 'Unit Tests' do
          inherit! :search_paths
      end
    
      target 'UITests' do
          inherit! :search_paths
          pod 'KIF'
          pod 'OHHTTPStubs/Swift'
          pod 'EnvoyAmbassador'
          pod 'Embassy'
      end
    end

as well as the "new" way with a single pod for all builds:

    source 'https://github.com/CocoaPods/Specs.git'
    
    workspace 'waveremit.xcworkspace'
    project 'waveremit/waveremit.xcodeproj'
    
    platform :ios, '9.0'
    
    target :waveremit do
      pod 'AFNetworking', '~> 2.6.3'
      pod 'MCSwipeTableViewCell', '>= 2.1.2'
      pod 'Mixpanel', '~> 3.4'
      pod 'libPhoneNumber-iOS', '>= 0.7'
      pod 'FMDB', '>= 2.5'
      pod 'Stripe', '>= 1.0.2'
      pod 'Braintree', '>= 3.9.3'
      pod 'ActionSheetPicker-3.0', '>= 1.3.4'
      pod 'Rollbar', '~> 0.2.0'
      pod 'FBSDKCoreKit', '~> 4.33'
      pod 'BEMCheckBox'
      pod 'Onfido', '~> 11.1.2'
      target 'Unit Tests' do
          inherit! :search_paths
      end
    
      target 'UITests' do
          inherit! :search_paths
          pod 'KIF'
          pod 'OHHTTPStubs/Swift'
          pod 'EnvoyAmbassador'
          pod 'Embassy'
      end
    end

**Comment by keremgund** [comment]
Thanks for reply @mdesjardins. Is that error disappeared if you manually add AVFoundation framework to your app target ? 
Can you also check our latest SDK version to confirm whether the issue still exists on latest version or not ?
Thanks,
Kerem

**Comment by mdesjardins** [comment]
@keremgund I attempted to add the AVFoundation framework manually but the error did not go away. I'll try a newer version of the SDK when I prepare our next release.

**Comment by keremgund** [comment]
@mdesjardins Thanks for reply. What's your app development language, Objective C or Swift ?
Also, is there a reason to not use `use_frameworks` in your podfile ?

**Comment by mdesjardins** [comment]
@keremgund allegedly, there is a reason, but I don't know what it is... that decision pre-dates me and I was warned by superstitious colleagues not to change it, but perhaps I should try that anyway.

Our app, like many these days, is a unpredicable mix of both Swift and Objective C, but there's more Objective C than Swift.

**Comment by anuragajwani** [comment]
@mdesjardins I tried reproducing your issue. I copied and pasted your Podfile in an Objective-C project. I erased the contents of the simulator (12.2). Still wasn't able to reproduce this issue. Please find attached the sample project 
[GithubIssue95.zip](https://github.com/onfido/onfido-ios-sdk/files/3306783/GithubIssue95.zip)

Please check the sample project. If it works with you please send us a sample project where we can reproduce this issue.

Anurag

**Comment by mdesjardins** [comment]
@anuragajwani did you try with an 11.1 version of the simulator as I did above? https://github.com/onfido/onfido-ios-sdk/issues/95#issuecomment-498791276

**Comment by anuragajwani** [comment]
@mdesjardins sorry I missed that out. Got the crash. Thanks for responding quick.

I will update you once we have some more news on the fix for this.

Anurag

**Comment by cpetzel** [comment]
We are also experiencing this issue. Looking forward to a resolution soon!

**Comment by anuragajwani** [comment]
Hey all @cpetzel, @mdesjardins, @markotl88, @compyman,

We have found how to fix this issue on your side. We are still investigation on how to solve this on our side. For now we will update the README file with the following instructions for non-Swift apps integration with the Onfido iOS SDK:

Create a new Swift file. Name it however you wish i.e. `OnfidoSwiftRuntimeLibrariesImport.swift` and copy&paste the following inside your file:
```
/*
 This file is required to force Xcode to package Swift runtime libraries required for
 the Onfido iOS SDK to run
 */
import Foundation
import AVFoundation
import CoreImage
import UIKit
import Vision

func fixLibSwiftOnoneSupport() {
    // from https://stackoverflow.com/a/54511127/2982993
    print("Fixes dyld: Library not loaded: @rpath/libswiftSwiftOnoneSupport.dylib")
}
```

Additionally make sure `Always Embed Swift Standard Libraries` in your app configuration is set to `Yes`.

Sorry for the inconvenience this is causing,
Anurag

**Comment by kevinkong91** [comment]
Thanks @anuragajwani, your suggested fix resolved the issue for us.

**Comment by anuragajwani** [comment]
glad to hear that @kevinkong91 ! 😄

**Comment by markotl88** [comment]
Thanks, @anuragajwani, this has resolved our problem as well!
