### ISSUE TITLE
Retrieve image without having to download

### ISSUE THREAD

**Issue by TYRONEMICHAEL** [onfido/onfido-ios-sdk#99]
Would it be possible to grab the image after it has been captured without having to download it using the href? Is there a reason why this functionality is not provided?

**Comment by keremgund** [comment]
Hello @TYRONEMICHAEL , We want our customers to use our SDK for end to end verification/process, not for a partial process. 

You can use Onfido API to do that operation.

Thanks,
Kerem

**Comment by keremgund** [comment]
Closing the issue due to lack of response. Please open new one if you still need assistance.
